/* Bobby · Maths KOC — submissions. */
KOC.works('maths', 'bobby', [
  {
    id: 'jm25-factorization-game',
    title: 'JM25 · Factorization Game',
    type: 'interactive',
    chapter: 'JM25',
    submitted: '2026-09-29',
    status: 'pending',
    tags: ['Interactive', 'Game', 'Factorization'],
    cover: 'content/maths/bobby/comics/jm25/factorization-chapter-1-color.png',
    src: 'https://uniunipluskoc-blip.github.io/comics/lessons/jm25/index.html#game',
    notes: 'JM25 lesson page, opened on the game section.'
  },
  {
    id: 'jm24-law-of-indices',
    title: 'JM24 · Law of Indices',
    type: 'gallery',
    chapter: 'JM24',
    submitted: '2026-08-28',
    status: 'pending',
    tags: ['Comics', 'Indices', 'Scientific notation', 'Binary'],
    cover: 'content/maths/bobby/comics/jm24/indices-club-chapter-1-color.png',
    srcs: [
      'content/maths/bobby/comics/jm24/indices-club-chapter-1-color.png',
      'content/maths/bobby/comics/jm24/indices-club-chapter-2-color.png',
      'content/maths/bobby/comics/jm24/indices-club-chapter-3-color.png',
      'content/maths/bobby/comics/jm24/indices-club-laws-card-color.png',
      'content/maths/bobby/comics/jm24/magnitude-express-chapter-1-color.png',
      'content/maths/bobby/comics/jm24/magnitude-express-chapter-2-color.png',
      'content/maths/bobby/comics/jm24/magnitude-express-chapter-3-color.png',
      'content/maths/bobby/comics/jm24/magnitude-express-chapter-4-color.png',
      'content/maths/bobby/comics/jm24/magnitude-express-laws-card-color.png',
      'content/maths/bobby/comics/jm24/bitspire-chapter-1-color.png',
      'content/maths/bobby/comics/jm24/bitspire-chapter-2-color.png',
      'content/maths/bobby/comics/jm24/bitspire-chapter-3-color.png',
      'content/maths/bobby/comics/jm24/bitspire-chapter-4-color.png',
      'content/maths/bobby/comics/jm24/bitspire-laws-card-color.png'
    ],
    notes: 'S3 manga for Law of Indices: Indices Club (rules), Magnitude Express (scientific notation), and Bitspire Tower (binary), each with a law card.'
  },
  {
    id: 'jm25-factorization',
    title: 'JM25 · Factorization and Polynomials',
    type: 'gallery',
    chapter: 'JM25',
    submitted: '2026-08-28',
    status: 'pending',
    tags: ['Comics', 'Factorization', 'Cross method'],
    cover: 'content/maths/bobby/comics/jm25/factorization-chapter-1-color.png',
    srcs: [
      'content/maths/bobby/comics/jm25/factorization-chapter-1-color.png',
      'content/maths/bobby/comics/jm25/factorization-chapter-2-color.png',
      'content/maths/bobby/comics/jm25/factorization-chapter-3-color.png',
      'content/maths/bobby/comics/jm25/factorization-chapter-4-color.png',
      'content/maths/bobby/comics/jm25/factorization-laws-card-color.png',
      'content/maths/bobby/comics/jm25/cross-method-chapter-1-color.png',
      'content/maths/bobby/comics/jm25/cross-method-laws-card-color.png'
    ],
    notes: 'The Bracket Labyrinth (Ch. 1–4 + factor law card) and Cross Method classroom guide.'
  },
  {
    id: 'jm26-inequalities',
    title: 'JM26 · Inequalities I',
    type: 'gallery',
    chapter: 'JM26',
    submitted: '2026-08-28',
    status: 'pending',
    tags: ['Comics', 'Inequalities'],
    cover: 'content/maths/bobby/comics/jm26/inequalities-chapter-1-color.png',
    srcs: [
      'content/maths/bobby/comics/jm26/inequalities-chapter-1-color.png',
      'content/maths/bobby/comics/jm26/inequalities-chapter-2-color.png',
      'content/maths/bobby/comics/jm26/inequalities-chapter-3-color.png',
      'content/maths/bobby/comics/jm26/inequalities-laws-card-color.png'
    ],
    notes: 'Classroom manga for linear, fraction, and double inequalities, plus a quick-reference card.'
  },
  {
    id: 'jm28-triangles',
    title: 'JM28 · Special Lines in Triangles',
    type: 'gallery',
    chapter: 'JM28',
    submitted: '2026-08-28',
    status: 'pending',
    tags: ['Comics', 'Triangles', 'Angle pairs', 'Similar', 'Congruent'],
    cover: 'content/maths/bobby/comics/jm28/triangle-lines-chapter-1-color.png',
    srcs: [
      'content/maths/bobby/comics/jm28/triangle-lines-chapter-1-color.png',
      'content/maths/bobby/comics/jm28/triangle-lines-chapter-2-color.png',
      'content/maths/bobby/comics/jm28/triangle-lines-chapter-3-color.png',
      'content/maths/bobby/comics/jm28/triangle-lines-chapter-4-color.png',
      'content/maths/bobby/comics/jm28/triangle-centres-chapter-5-orthocentre-color.png',
      'content/maths/bobby/comics/jm28/triangle-centres-chapter-6-centroid-color.png',
      'content/maths/bobby/comics/jm28/triangle-centres-chapter-7-incentre-color.png',
      'content/maths/bobby/comics/jm28/triangle-centres-chapter-8-circumcentre-color.png',
      'content/maths/bobby/comics/jm28/triangle-lines-laws-card-color.png',
      'content/maths/bobby/comics/jm28/triangle-centres-quick-reference-color.png',
      'content/maths/bobby/comics/jm28/angle-pairs-chapter-1-color.png',
      'content/maths/bobby/comics/jm28/angle-pairs-chapter-2-color.png',
      'content/maths/bobby/comics/jm28/angle-pairs-chapter-3-color.png',
      'content/maths/bobby/comics/jm28/angle-pairs-chapter-4-color.png',
      'content/maths/bobby/comics/jm28/angle-pairs-quick-reference-color.png',
      'content/maths/bobby/comics/jm28/similar-congruent-chapter-1-labels-fixed.png',
      'content/maths/bobby/comics/jm28/similar-congruent-chapter-2-layout-fixed.png',
      'content/maths/bobby/comics/jm28/similar-congruent-chapter-3-layout-fixed.png',
      'content/maths/bobby/comics/jm28/similar-congruent-chapter-4-layout-fixed.png',
      'content/maths/bobby/comics/jm28/similar-congruent-chapter-5-layout-fixed.png',
      'content/maths/bobby/comics/jm28/similar-congruent-chapter-6-layout-fixed.png',
      'content/maths/bobby/comics/jm28/similar-congruent-quick-reference-color.png'
    ],
    notes: 'Classroom manga: four special lines and centres, angle pairs, and similar and congruent triangles, with quick-reference cards.'
  },
  {
    id: 'vectors-in-3-minutes',
    title: 'Vectors in 3 Minutes',
    type: 'video',
    chapter: 'Maths Ch. 11',
    submitted: '2026-08-16',
    status: 'pending',
    tags: ['Video', 'Awaiting upload'],
    cover: 'content/maths/bobby/vectors-cover.svg',
    src: 'content/maths/bobby/vectors-in-3-minutes.mp4',
    notes: 'Card created ahead of the render finishing — the mp4 is not committed yet, so the viewer will report the file as missing.'
  }
]);
