const COPY = {
  home: "Home",
  trackLearn: "Classification of matter",
  catAll: "All",
  qtypeHit: "Shoot the formula",
  qtypePass: "Name the class",
  qtypePair: "Compare a pair",
  pickSpeed: "Difficulty",
  speedSlow: "Easy",
  speedNormal: "Normal",
  speedFast: "Hard",
  speedNoteSlow: "5 hearts. Enemies do not shoot.",
  speedNoteNormal: "5 hearts. Enemies shoot slowly.",
  speedNoteFast: "3 hearts. Enemies shoot often.",
  speedNoteFastSolo: "3 hearts. Enemies shoot often.",
  setupNext: "Next",
  setupBack: "Back",
  setupStart: "Enter the dungeon",
  howtoTitle: "How to play",
  howto1: "WASD moves. The mouse aims. Click shoots.",
  howto2: "Press 1, 2, or 3 to switch ammo. 1 is a pure element, 2 a pure compound, 3 a mixture of elements.",
  howto3: "Matching ammo kills that formula. Wrong ammo costs a heart and the monster stays.",
  howto4: "Stone walls block you and your bullets.",
  howtoBoss: "The boss shows a formula. Only the matching ammo damages it.",
  howto5: "Space pauses. Esc returns home.",
  pauseHint: "Space to pause",
  paused: "Paused",
  countGo: "Go",
  next: "Next floor",
  nextCard: "Next card",
  nextLast: "Finish",
  mixCat: "Mixed",
  again: "Play again",
  retryWeak: "Retry missed floors",
  resumeWeak: "Continue missed floors",
  recapTitle: "Dungeon clear",
  firstHits: "Clean floors",
  misses: "Misses",
  keys: "WASD to move, mouse to aim, click to shoot. 1 pure element, 2 pure compound, 3 mixture of elements. Wrong ammo costs a heart. Stone walls block you and bullets.",
  keysPass: "WASD to move, mouse to aim, click to shoot. Collect the correct formulas and avoid the others. Stone walls block you and bullets.",
  keysPair: "WASD to move, mouse to aim, click to shoot. Collect the correct formulas and avoid the others. Stone walls block you and bullets.",
  keysHint: "1 pure element · 2 pure compound · 3 mixture · WASD move · click shoot · Space pause",
  fragments: "Formulas",
  leaveTitle: "This dungeon is not finished. Return home?",
  leaveStay: "Stay",
  leaveHome: "Home",
  round: "Floor ",
  floorUnit: "",
  of: " / ",
  clean: "All correct.",
  keep: "Practice these floors again",
  timeUsed: "Time",
  accuracy: "Accuracy",
  hearts: "Hearts",
  healLabel: "Heal on hit",
  healOff: "Off",
  healOn: "On",
  pickBoss: "Boss",
  bossOff: "Off",
  bossOn: "On",
  buffGotHp: "Heart gained",
  buffGotAtk: "Attack gained",
  pickTip: "Hint target",
  tipOff: "Off",
  tipOn: "On",
  tipReveal: "Hint: ",
  fullscreen: "Full screen",
  fullscreenExit: "Exit full screen",
  mobileOn: "Phone",
  mobileOff: "Keys",
  mobilePause: "Pause",
  outOfHearts: "Fell on floor ",
  floorClear: " cleared",
  teachWhat: "What this is",
  teachEffect: "Shoot these",
  teachExample: "Classic example",
  teachVs: "Do not mix with",
  teachWrite: "You try",
  showAnswer: "Show one answer",
  recapMix: "Easy to mix up",
  recapCat: "Class hits",
  recapHome: "Take home",
  jia: "A",
  yi: "B",
};

const BOSS_BY_CAT = {
  "Pure element": {
    name: "Element examiner",
    fight: "One kind of atom",
    line: "Fe is a pure element. FeS has already combined. Fe + S has not.",
    hits: [
      "That formula has more than one element.",
      "A plus sign means a mixture, not a pure element.",
      "O2 is still an element. Every particle is the same.",
    ],
  },
  "Pure compound": {
    name: "Compound examiner",
    fight: "Chemically combined",
    line: "FeS is one compound. Fe + S is still two elements.",
    hits: [
      "A plus sign means they have not combined.",
      "One symbol alone is an element.",
    ],
  },
  "Mixture of elements": {
    name: "Mixture examiner",
    fight: "Not combined",
    line: "Fe + S stays two elements. FeS is already one compound.",
    hits: [
      "No plus sign means it is not this mixture.",
      "FeS is a compound, not Fe + S.",
    ],
  },
  All: {
    name: "Matter examiner",
    fight: "Sort the formula",
    line: "Fe is an element, FeS is a compound, Fe + S is a mixture of elements.",
    hits: [
      "Check the plus sign first.",
      "One symbol is an element. Two symbols joined are a compound.",
    ],
  },
};

const TECHNIQUES = [
  {
    id: "pure-element",
    cat: "Pure element",
    name: "Pure element",
    hits: ["Fe", "Cu", "Zn", "S", "C", "Mg", "Al", "Na", "Ag", "He", "O2", "N2", "H2", "Cl2"],
    decoys: ["FeS", "Fe + S"],
    plain: "A pure element is one kind of atom only. It cannot be broken down into anything simpler by chemical methods. O2 is one element. Every atom in it is oxygen.",
    vs: "FeS is iron and sulfur joined as one compound. Fe + S is iron and sulfur still separate.",
    example: "Fe",
    mark: "One symbol, or the same atom only, such as O2. No plus sign.",
    passage: "Fe",
    writeStem: "Name one more pure element.",
    writeModel: "Cu",
    twins: ["pure-compound", "mixture-elements"],
  },
  {
    id: "pure-compound",
    cat: "Pure compound",
    name: "Pure compound",
    hits: ["FeS", "NaCl", "H2O", "CO2", "CuO", "MgO", "ZnS", "CaO", "SO2", "NH3", "CH4", "Fe2O3"],
    decoys: ["Fe", "Fe + S"],
    plain: "A pure compound is two or more elements chemically combined. The formula has no plus sign.",
    vs: "FeS is not Fe + S. The plus sign means they have not combined. Fe alone is a pure element.",
    example: "FeS",
    mark: "Two or more element symbols written as one formula, with no +.",
    passage: "FeS",
    writeStem: "Name one more pure compound.",
    writeModel: "NaCl",
    twins: ["pure-element", "mixture-elements"],
  },
  {
    id: "mixture-elements",
    cat: "Mixture of elements",
    name: "Mixture of elements",
    hits: ["Fe + S", "Cu + Zn", "C + S", "Na + Cl2", "H2 + O2", "Mg + S", "Al + Cu", "Zn + S", "Fe + Cu", "C + Fe"],
    decoys: ["Fe", "FeS"],
    plain: "A mixture of elements is two or more elements that have not chemically combined. Write them with a plus sign. Ammo 3 is only elements that have not joined. Salt water and Fe + FeS are mixtures too, but they are not this ammo.",
    vs: "Fe + S is not FeS. FeS is a compound. Fe alone is a pure element. A magnet pulls iron out of Fe + S, not out of FeS.",
    example: "Fe + S",
    mark: "A plus sign between element formulas.",
    passage: "Fe + S",
    writeStem: "Name one more mixture of elements.",
    writeModel: "Cu + Zn",
    twins: ["pure-element", "pure-compound"],
  },
];

const COMBOS = [];

const PAIRS = [];

const TECH_BY_ID = {};
TECHNIQUES.forEach(function (tech) {
  TECH_BY_ID[tech.id] = tech;
});

const HIT_OWNER = {};
TECHNIQUES.forEach(function (tech) {
  tech.hits.forEach(function (hit) {
    if (!HIT_OWNER[hit]) HIT_OWNER[hit] = tech.name;
  });
});
