const COPY = {
  title: "跳高高",
  kicker: "背書 · 李白《送友人》",
  lead: "①溫書 ②跳高高 ③默寫 ④貪吃蛇。粵語／普通話逐句朗讀。Esc 回主頁。",
  home: "主頁",
  trackPoem: "背書",
  studyName: "溫書",
  studyLead: "看全詩、難字和語譯。",
  jumpName: "跳高高",
  jumpLead: "選對的字詞。連對就跳得更高。",
  writeName: "默寫",
  writeLead: "一聯一聯默寫，對答案後才看下一聯。",
  snakeName: "貪吃蛇",
  snakeLead: "吃對的字詞，累積成句。吃錯或撞牆要再練。",
  snakeKeys: "方向鍵 · WASD",
  snakeWall: "撞牆了",
  snakeSelf: "咬到自己",
  snakeGotIt: "明白了，再走",
  snakeDiff: "貪吃蛇難度",
  snakeSetupHint: "先選難度，再開始走蛇",
  snakeSetupStart: "開始",
  snakeSetupBack: "上一步",
  pickMode: "模式",
  snakeNoteNormal: "一般速度，正確字詞加一個干擾。",
  snakeNoteHard: "走得較快，正確字詞加兩個干擾。",
  normal: "普通",
  hard: "困難",
  again: "再來一局",
  recapTitle: "本局結果",
  hits: "第一下答對",
  misses: "打錯",
  clean: "全對",
  keep: "再練這些",
  round: "第",
  of: "/",
  yue: "粵語",
  cmn: "普通話",
  voice: "朗讀",
  listenFull: "逐句朗讀",
  listenCouplet: "朗讀本聯",
  noVoice: "找不到中文朗讀聲。請用 Google Chrome，並在 macOS「系統設定 → 輔助使用 → 朗讀內容」加入廣東話或國語。",
  nextCouplet: "下一聯",
  seeResult: "看結果",
  retryWrong: "只練打錯",
  retrySaved: "續練錯題",
  confirmMsg: "進度會清掉。確定回主頁？",
  confirmYes: "確定",
  confirmNo: "繼續",
  writeIntro: "看不見原句。聽朗讀或看語譯都是提示，能默就不要用。標點漏了也不算錯。",
  checkAnswers: "對答案",
  picked: "你寫了",
  jumpPicked: "你選了",
  shouldBe: "應是",
  fullPoem: "全詩",
  yiyi: "語譯",
  duizhang: "對仗／寫作",
  keysHint: "1 · 2 選擇",
  lian: "聯",
  writeHits: "對了",
  writeMiss: "未對",
  ticai: "體裁",
  zhuzhi: "主旨",
  nanzi: "難字",
  streak: "連對",
  yunjiao: "韻腳",
  goJump: "去跳高高",
  goWrite: "去默寫",
  gotIt: "明白了，再選",
  peekYiyi: "看語譯提示",
  upperLine: "上句",
  lowerLine: "下句",
  extraChars: "多寫了",
  koujue: "口訣",
  sibu: "四步",
  coach: "對症複習",
  skeleton: "口頭骨架",
  coachKind: {
    順序: "開篇先山後水。白水是下句。",
    對仗: "對着唸：橫對繞，浮雲對落日，遊子意對故人情。",
    他詩: "不要混進別首。這首是此地一為別、孤蓬萬里征、蕭蕭班馬鳴。",
    近義: "要用原字。白水不是白雲，浮雲不是白雲，落日不是夕陽。",
    用字: "青山是「橫」北郭，不是倚。",
    口語: "原句是揮手自茲去，不要寫成招手從此。",
  },
};

const POEM = {
  title: "送友人",
  author: "李白",
  form: "五言律詩",
  theme: "即景抒情，由眼前山水寫到萬里飄泊，再收到不忍離別。",
  rhyme: "城、征、情、鳴",
  koujue: "先山後水，此地孤蓬，浮雲對落日，揮手班馬。",
  steps: [
    { name: "首聯", focus: "眼前山水（空間）", line: "青山橫北郭，白水繞東城。" },
    { name: "頷聯", focus: "一別就遠走", line: "此地一為別，孤蓬萬里征。" },
    { name: "頸聯", focus: "景比情，最工整", line: "浮雲遊子意，落日故人情。" },
    { name: "尾聯", focus: "動作加聲音收束", line: "揮手自茲去，蕭蕭班馬鳴。" },
  ],
  full: "青山橫北郭，白水繞東城。此地一為別，孤蓬萬里征。浮雲遊子意，落日故人情。揮手自茲去，蕭蕭班馬鳴。",
  words: [
    { word: "橫", gloss: "橫亙、橫躺在那裏" },
    { word: "繞", gloss: "環繞。和上句「橫」相對" },
    { word: "郭", gloss: "外城" },
    { word: "征", gloss: "遠行，不是打仗的征" },
    { word: "孤蓬", gloss: "隨風飄轉的蓬草，比喻漂泊的人" },
    { word: "遊子", gloss: "遠行的友人" },
    { word: "故人", gloss: "送行的人，這裏指詩人自己" },
    { word: "茲", gloss: "此、這裏" },
    { word: "蕭蕭", gloss: "馬鳴聲" },
    { word: "班馬", gloss: "離群的馬，不是斑馬" },
  ],
  couplets: [
    {
      id: "shou",
      name: "首聯",
      line: "青山橫北郭，白水繞東城。",
      yiyi: "青翠的山巒橫亙在北面的外城，清澈的河水環繞着東邊的城。",
      duizhang: "青山對白水，橫對繞，北郭對東城。寫景起興，以山水對舉寫出送別的空間。",
      blanks: [
        {
          id: "s1a",
          hint: "開篇先寫什麼景色？",
          scene: { top: "城郭", bottom: "？" },
          kind: "順序",
          why: "白水是下句。開篇先寫山，再寫水。",
          choices: [
            { text: "青山", ok: true },
            { text: "白水", ok: false },
          ],
          add: "青山",
        },
        {
          id: "s1b",
          hint: "青山怎樣接到城郭？",
          scene: { top: "北郭", bottom: "青山" },
          kind: "用字",
          why: "原句用「橫」，是山橫亙在北郭，不是倚靠。",
          choices: [
            { text: "橫北郭", ok: true },
            { text: "倚北郭", ok: false },
          ],
          add: "橫北郭，",
        },
        {
          id: "s1c",
          hint: "和下句相對、對着山的是什麼？",
          scene: { top: "北郭", bottom: "？" },
          kind: "近義",
          why: "對着青山的是白水，不是白雲。",
          choices: [
            { text: "白水", ok: true },
            { text: "白雲", ok: false },
          ],
          add: "白水",
        },
        {
          id: "s1d",
          hint: "和「橫」相對，寫水的那個說法是哪一個？",
          scene: { top: "東城", bottom: "白水" },
          kind: "對仗",
          why: "橫對繞：山是橫，水是繞。不能兩句都用橫。",
          choices: [
            { text: "繞東城", ok: true },
            { text: "橫東城", ok: false },
          ],
          add: "繞東城。",
        },
      ],
    },
    {
      id: "han",
      name: "頷聯",
      line: "此地一為別，孤蓬萬里征。",
      yiyi: "就在這裏一分別，友人便如一團孤蓬，踏上萬里征途。",
      duizhang: "頷聯近流水對、寬對，不必字字工整。由眼前的分別，寫到此後的飄泊。",
      blanks: [
        {
          id: "s2a",
          hint: "送別從哪裏說起？",
          scene: { top: "送別", bottom: "？" },
          kind: "他詩",
          why: "這裏是「此地一為別」，不要寫成別首詩的「此夜」「為客」。",
          choices: [
            { text: "此地一為別", ok: true },
            { text: "此夜一為客", ok: false },
          ],
          add: "此地一為別，",
        },
        {
          id: "s2b",
          hint: "友人這一別被寫成怎樣遠行？",
          scene: { top: "征途", bottom: "此地一為別" },
          kind: "他詩",
          why: "這首用孤蓬，比漂泊。孤帆是《黃鶴樓送孟浩然之廣陵》的意象。",
          choices: [
            { text: "孤蓬萬里征", ok: true },
            { text: "孤帆萬里行", ok: false },
          ],
          add: "孤蓬萬里征。",
        },
      ],
    },
    {
      id: "jing",
      name: "頸聯",
      line: "浮雲遊子意，落日故人情。",
      yiyi: "飄浮的雲，比友人漂泊的心意；將落的太陽，比送行者不捨的情誼。",
      duizhang: "浮雲對落日，遊子意對故人情。以景喻情，是全詩最工整的一聯。",
      blanks: [
        {
          id: "s3a",
          hint: "上句用什麼景物來比心意？",
          scene: { top: "遊子", bottom: "？" },
          kind: "近義",
          why: "原句是浮雲，取其飄不定，不是泛寫白雲。",
          choices: [
            { text: "浮雲", ok: true },
            { text: "白雲", ok: false },
          ],
          add: "浮雲",
        },
        {
          id: "s3b",
          hint: "這種景物比的是哪一種心意？",
          scene: { top: "心意", bottom: "浮雲" },
          kind: "對仗",
          why: "浮雲比的是遊子意（友人遠行）。故人情在下句，對落日。",
          choices: [
            { text: "遊子意", ok: true },
            { text: "故人情", ok: false },
          ],
          add: "遊子意，",
        },
        {
          id: "s3c",
          hint: "下句對着浮雲的是什麼？",
          scene: { top: "故人", bottom: "？" },
          kind: "近義",
          why: "對仗要用落日，不能換成意思相近的夕陽。",
          choices: [
            { text: "落日", ok: true },
            { text: "夕陽", ok: false },
          ],
          add: "落日",
        },
        {
          id: "s3d",
          hint: "這種景物比的是哪一種情誼？",
          scene: { top: "情誼", bottom: "落日" },
          kind: "對仗",
          why: "落日比的是故人情（送行者不捨）。遊子意已在上句。",
          choices: [
            { text: "故人情", ok: true },
            { text: "遊子意", ok: false },
          ],
          add: "故人情。",
        },
      ],
    },
    {
      id: "wei",
      name: "尾聯",
      line: "揮手自茲去，蕭蕭班馬鳴。",
      yiyi: "揮一揮手，從此離去；只聽見離群的馬蕭蕭長鳴。",
      duizhang: "以動作收束，再用馬鳴寫出不忍離別。尾聯以情韻作結，不必字字對仗。",
      blanks: [
        {
          id: "s4a",
          hint: "臨別時怎樣離開這裏？",
          scene: { top: "離別", bottom: "？" },
          kind: "口語",
          why: "原句是「揮手自茲去」，不要寫成口語的招手、從此。",
          choices: [
            { text: "揮手自茲去", ok: true },
            { text: "招手從此去", ok: false },
          ],
          add: "揮手自茲去，",
        },
        {
          id: "s4b",
          hint: "離去時聽見什麼聲音？",
          scene: { top: "馬鳴", bottom: "揮手自茲去" },
          kind: "他詩",
          why: "這裏是蕭蕭班馬鳴。班馬是離群的馬；不要和胡馬、依依那些句子混在一起。",
          choices: [
            { text: "蕭蕭班馬鳴", ok: true },
            { text: "依依胡馬嘶", ok: false },
          ],
          add: "蕭蕭班馬鳴。",
        },
      ],
    },
  ],
};
