/** Ch5 Food and humans — pages 1–16 (bilingual EN + 中文) */
export const FLASHCARD_TAGS = ["Biology", "Ch5", "FoodAndHumans", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "有機與縮合水解",
    front: "Condensation 縮合 = which type of metabolism 代謝？縮合屬於哪一類代謝？",
    back: "<strong>Anabolism 合成代謝</strong>（build-up 合成）",
  },
  {
    id: 2,
    subtopic: "有機與縮合水解",
    front: "In condensation 縮合, what happens to water <strong>per bond</strong>？縮合時每形成一鍵，水怎樣？",
    back: "<strong>Lose 1 H₂O</strong> per bond　每鍵失去 1 分子水",
    image: "./assets/page01_condensation.png",
    imageAlt: "Condensation loses water; hydrolysis gains water 縮合失水、水解得水",
  },
  {
    id: 3,
    subtopic: "有機與縮合水解",
    front: "Hydrolysis 水解 = which type of metabolism 代謝？水解屬於哪一類代謝？",
    back: "<strong>Catabolism 分解代謝</strong>（breakdown 分解）",
  },
  {
    id: 4,
    subtopic: "有機與縮合水解",
    front: "In hydrolysis 水解, what happens to water <strong>per bond</strong>？水解時每斷開一鍵，水怎樣？",
    back: "<strong>Gain 1 H₂O</strong> per bond　每鍵獲得 1 分子水",
  },
  {
    id: 5,
    subtopic: "有機與縮合水解",
    front: "Prolonged starvation 長期饑餓: fuel use order？能量使用次序？",
    back: "<strong>Carbohydrates 碳水化合物 → Lipids 脂質 → Proteins 蛋白質</strong>（last resort 最後手段）",
    image: "./assets/page02_starvation.png",
    imageAlt: "Starvation graph: glycogen then lipids then proteins 饑餓時先用肝醣再脂質最後蛋白質",
  },
  {
    id: 6,
    subtopic: "有機與縮合水解",
    front: "Two monosaccharides 單醣 join by ____ to form a disaccharide 雙醣。兩分子單醣以____結合形成雙醣。",
    back: "<strong>Condensation 縮合</strong>（lose H₂O 失去水）",
  },
  {
    id: 7,
    subtopic: "碳水化合物",
    front: "Monosaccharides 單醣 vs polysaccharides 多醣: solubility 溶解性？",
    back: "Monosaccharides 單醣: <strong>soluble 可溶</strong>；Polysaccharides 多醣: <strong>insoluble 不溶</strong>",
  },
  {
    id: 8,
    subtopic: "碳水化合物",
    front: "Monosaccharides 單醣 vs polysaccharides 多醣: sweet 甜味？",
    back: "Monosaccharides 單醣: <strong>sweet 甜</strong>；Polysaccharides 多醣: <strong>not sweet 不甜</strong>",
  },
  {
    id: 9,
    subtopic: "碳水化合物",
    front: "What do reducing sugars 還原糖 do? Exception 例外？還原糖有何作用？例外是什麼？",
    back: "<strong>Donate electrons 捐出電子</strong>；★except <strong>sucrose 蔗糖</strong>除外",
  },
  {
    id: 10,
    subtopic: "碳水化合物",
    front: "Main respiratory fuel monosaccharide 主要呼吸燃料單醣？Why “FAST”？為何快？",
    back: "<strong>Glucose 葡萄糖</strong> — directly absorbed and used 可直接吸收及使用",
  },
  {
    id: 11,
    subtopic: "碳水化合物",
    front: "Name 5 monosaccharides 單醣 in the notes. 寫出筆記中的五種單醣。",
    back: "Glucose 葡萄糖, fructose 果糖, galactose 半乳糖, <strong>ribose 核糖</strong>, <strong>deoxyribose 脱氧核糖</strong>（DNA）",
  },
  {
    id: 12,
    subtopic: "碳水化合物",
    front: "Maltose 麥芽糖 can form from? 麥芽糖可由什麼形成？",
    back: "<strong>Starch hydrolysis 澱粉水解</strong>",
  },
  {
    id: 13,
    subtopic: "碳水化合物",
    front: "Sucrose 蔗糖: reducing 還原性？Role in plants 植物中角色？",
    back: "<strong>Non-reducing 非還原糖</strong>；<strong>transport form 運輸形式</strong> in plants 在植物中",
  },
  {
    id: 14,
    subtopic: "碳水化合物",
    front: "Glycogen 肝醣 vs starch 澱粉: storage in? 貯存於？",
    back: "Glycogen 肝醣 → <strong>animals 動物</strong>；Starch 澱粉 → <strong>plants 植物</strong>",
  },
  {
    id: 15,
    subtopic: "碳水化合物",
    front: "Cellulose 纖維素 role in <strong>plants 植物</strong>？纖維素在植物中的功能？",
    back: "Support <strong>plant cell wall 植物細胞壁</strong>　支撐植物細胞壁",
  },
  {
    id: 16,
    subtopic: "碳水化合物",
    front: "Cellulose as dietary fibre 膳食纖維 in humans: energy 能量？2 benefits 益處？",
    back: "<strong>No energy value 無能量</strong>；fullness 飽腹感 + promote gut <strong>peristalsis 蠕動</strong>",
  },
  {
    id: 17,
    subtopic: "脂質",
    front: "Triglyceride 三酸甘油酯 composition 組成？",
    back: "<strong>1 glycerol 甘油 + 3 fatty acids 脂肪酸</strong>",
    image: "./assets/page06_triglyceride.png",
    imageAlt: "Triglyceride: one glycerol and three fatty acids 一甘油三脂肪酸",
  },
  {
    id: 18,
    subtopic: "脂質",
    front: "Phospholipid 磷脂 composition 組成？",
    back: "<strong>1 glycerol 甘油 + 2 fatty acids 脂肪酸 + phosphate 磷酸基團</strong>",
    image: "./assets/page06_phospholipid_icon.png",
    imageAlt: "Phospholipid: phosphate, glycerol, two fatty acids 磷酸基甘油兩脂肪酸",
  },
  {
    id: 19,
    subtopic: "脂質",
    front: "Steroids 類固醇 basic structure 基本結構？Examples 例子？",
    back: "<strong>Four carbon rings 四個碳環</strong>；cholesterol 膽固醇, sex hormones 性荷爾蒙",
    image: "./assets/page06_steroid.png",
    imageAlt: "Steroid four fused carbon rings 類固醇四個碳環",
  },
  {
    id: 20,
    subtopic: "脂質",
    front: "Phospholipid 磷脂: hydrophilic vs hydrophobic parts？親水／疏水部分？",
    back: "★<strong>Hydrophilic (polar) head 親水（極性）頭</strong>；★<strong>hydrophobic (non-polar) tails 疏水（非極性）尾</strong> → bilayer 雙層",
    image: "./assets/page07_phospholipid.jpeg",
    imageAlt: "Phospholipid 磷脂 structure diagram 結構圖",
  },
  {
    id: 21,
    subtopic: "脂質",
    front: "Energy per gram of lipids 脂質 vs carbohydrates 碳水化合物 / proteins 蛋白質？每克脂質相對碳水化合物／蛋白質的能量？",
    back: "<strong>About twice 約兩倍</strong>（×2）",
  },
  {
    id: 22,
    subtopic: "脂質",
    front: "Name 4 triglyceride 三酸甘油酯 functions besides energy. 除能量外四項功能？",
    back: "Organ protection 保護器官；insulating nerve 絕緣神經；waterproofing 防水；reduce heat loss 減少熱量散失（subcutaneous fat 皮下脂肪）",
  },
  {
    id: 23,
    subtopic: "脂質",
    front: "Saturated fatty acids 飽和脂肪酸: state at room temperature 室溫狀態？Health 健康？",
    back: "<strong>Solid 固態</strong>；less healthy 較不健康 → clot 凝血 / <strong>cardiovascular diseases 心血管疾病</strong>",
  },
  {
    id: 24,
    subtopic: "脂質",
    front: "Unsaturated fatty acids 不飽和脂肪酸: state 狀態？Health 健康？",
    back: "<strong>Liquid 液態</strong>；more healthy 較健康",
  },
  {
    id: 25,
    subtopic: "脂質",
    front: "Trans fatty acids 反式脂肪酸: why worst 為何最差？",
    back: "Force unsaturated toward saturated-like 迫使不飽和似飽和；enzymes <strong>unfit to hydrolyze 酶難以水解</strong>",
  },
  {
    id: 26,
    subtopic: "脂質",
    front: "Before summing food energy, lipids need what multiplier？計算總能量前脂質要乘？",
    back: "<strong>×2</strong>　乘以 2",
  },
  {
    id: 27,
    subtopic: "脂質",
    front: "Subcutaneous fat 皮下脂肪: 3 roles 三項作用？",
    back: "Energy storage 貯能；absorb shock 緩衝撞擊；<strong>reduce heat loss 減少熱量散失</strong>",
  },
  {
    id: 28,
    subtopic: "蛋白質",
    front: "Elements in proteins 蛋白質含哪些元素？",
    back: "<strong>C + H + O + N</strong>（+ <strong>S</strong> in some 部分含硫）",
    image: "./assets/page02_condensation_eq.png",
    imageAlt: "Organic molecules element table including proteins C H O N S 有機物元素表",
  },
  {
    id: 29,
    subtopic: "蛋白質",
    front: "How many types of amino acids 胺基酸？Why 為何？胺基酸有多少種？原因？",
    back: "<strong>20</strong>（20 types of side chain 20 種側鏈）",
  },
  {
    id: 30,
    subtopic: "蛋白質",
    front: "Three groups on an amino acid 胺基酸的三個基團？",
    back: "<strong>Amino group 氨基</strong>（N）；<strong>carboxyl group 羧基</strong>（C）；<strong>side chain 側鏈</strong>（R）",
    image: "./assets/page09_amino_acid.png",
    imageAlt: "Amino acid: amino group, carboxyl group, side chain 胺基酸三基團",
  },
  {
    id: 31,
    subtopic: "蛋白質",
    front: "Condensation of 2 amino acids joins which groups？Product 產物？兩分子胺基酸縮合連接哪些基團？",
    back: "★Between <strong>amino group 氨基 + carboxyl group 羧基</strong> → <strong>dipeptide 二肽</strong>",
    image: "./assets/page11_dipeptide.png",
    imageAlt: "Dipeptide with peptide bond and water lost 二肽肽鍵失水",
  },
  {
    id: 32,
    subtopic: "蛋白質",
    front: "Polypeptide 多肽 vs protein 蛋白質: key difference 關鍵分別？",
    back: "Polypeptide 多肽 = <strong>linear chain 線性鏈</strong>；Protein 蛋白質 = <strong>3D conformation 三維構象</strong>（folding 摺疊）",
    image: "./assets/page12_folding.png",
    imageAlt: "Polypeptide folding into protein 多肽摺疊成蛋白質",
  },
  {
    id: 33,
    subtopic: "蛋白質",
    front: "What bonds hold the folded 3D conformation？維持摺疊構象的鍵？",
    back: "<strong>Hydrogen bonds 氫鍵</strong> between amino acids 胺基酸之間",
  },
  {
    id: 34,
    subtopic: "蛋白質",
    front: "What determines a protein’s 3D fold / function？決定蛋白質摺疊／功能的是？",
    back: "<strong>Amino acid sequence 胺基酸序列</strong>（by DNA 由 DNA 決定）",
  },
  {
    id: 35,
    subtopic: "蛋白質",
    front: "Essential vs non-essential amino acids 必需／非必需胺基酸？",
    back: "Essential 必需: <strong>only via food 只能從食物獲得</strong>；Non-essential 非必需: <strong>body can make 身體可合成</strong>",
  },
  {
    id: 36,
    subtopic: "蛋白質",
    front: "Name 5 protein functions 蛋白質五項功能 from notes. 寫出筆記中蛋白質的五項功能。",
    back: "Cell membrane proteins 細胞膜蛋白；growth and repair 生長與修復；<strong>enzymes 酶</strong>；hormones 激素；<strong>antibodies 抗體</strong>",
  },
  {
    id: 37,
    subtopic: "蛋白質",
    front: "Antibodies 抗體 & antigens 抗原 vs antibiotics 抗生素 — which are proteins？何者是蛋白質？",
    back: "Antibodies 抗體 & antigens 抗原 = <strong>proteins 蛋白質</strong>；antibiotics 抗生素 = <strong>NOT proteins 不是蛋白質</strong>",
  },
  {
    id: 38,
    subtopic: "蛋白質",
    front: "Denature 變性: reversible 可逆？Caused by 成因？",
    back: "<strong>Irreversible 不可逆</strong>；high temperature 高溫 / sub-optimal <strong>pH</strong> 非最適 pH",
    image: "./assets/page12_denature.png",
    imageAlt: "Native protein unfolds when denatured 變性失去構象",
  },
  {
    id: 39,
    subtopic: "蛋白質",
    front: "Denature 變性 → loss of ____ → loss of ____　變性失去____再失去____",
    back: "Loss of <strong>conformation 構象</strong> → loss of <strong>function 功能</strong>",
  },
  {
    id: 40,
    subtopic: "食物分類與礦物質",
    front: "Energy values 能量值: carbohydrates 碳水化合物 / proteins 蛋白質 / lipids 脂質 (kJ/g)？",
    back: "~<strong>17</strong> / ~<strong>17</strong> / ~<strong>37</strong>（~2 times 約兩倍）",
  },
  {
    id: 41,
    subtopic: "食物分類與礦物質",
    front: "Primary vs protective food substances 主要／保護性食物 — examples 例子？",
    back: "Primary 主要: carbohydrates 碳水化合物, proteins 蛋白質, lipids 脂質；Protective 保護性: dietary fibre 膳食纖維, vitamins 維生素, minerals 礦物質, ions 離子, water 水",
  },
  {
    id: 42,
    subtopic: "食物分類與礦物質",
    front: "Minerals 礦物質: energy value 能量？Amount needed 需要量？",
    back: "<strong>No energy 無能量</strong>；needed in <strong>small amounts 少量</strong>；regulate metabolism 調節代謝 & build tissues 建構組織",
  },
  {
    id: 43,
    subtopic: "食物分類與礦物質",
    front: "Calcium 鈣: storage 貯存？★main component of？主要組成？",
    back: "<strong>Bones and teeth 骨與牙齒 (99%)</strong>；★<strong>component of bones and teeth 骨與牙齒的組成成分</strong>",
  },
  {
    id: 44,
    subtopic: "食物分類與礦物質",
    front: "Calcium 鈣 deficiency 缺乏: children 兒童 vs adults 成人？",
    back: "Children 兒童: <strong>rickets 佝僂病</strong>；Adults 成人: <strong>osteoporosis 骨質疏鬆</strong>",
  },
  {
    id: 45,
    subtopic: "食物分類與礦物質",
    front: "Iron 鐵: key function 主要功能？Deficiency disease 缺乏症？",
    back: "Oxygen transport 氧氣運輸（<strong>hemoglobin 血紅蛋白</strong>）；<strong>anemia 貧血</strong>",
  },
  {
    id: 46,
    subtopic: "無機離子",
    front: "Nitrate NO₃⁻ main plant roles 植物主要作用？Deficiency look 缺乏表徵？",
    back: "Protein synthesis 蛋白質合成 + chlorophyll 葉綠素；poor growth 生長差 / <strong>yellowing leaves 葉黃</strong>",
  },
  {
    id: 47,
    subtopic: "無機離子",
    front: "Iodine I⁻ function 功能？Classic deficiency 典型缺乏？",
    back: "Thyroid hormone 甲狀腺激素 / metabolism 代謝；<strong>goiter 甲狀腺腫大</strong>",
  },
];
