/** Ch5 Food and humans — pages 1–16 (bilingual EN + 中文) */
export const FLASHCARD_TAGS = ["Biology", "Ch5", "FoodAndHumans", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "有機與縮合水解",
    front: "What type of metabolism is condensation?<br>縮合屬於哪一類代謝？",
    back: "It is <strong>anabolism</strong> (build-up).<br>它是<strong>合成代謝</strong>（合成）。",
  },
  {
    id: 2,
    subtopic: "有機與縮合水解",
    front: "When two small molecules join by condensation, what happens to water?<br>兩個小分子以縮合結合時，水會怎樣？",
    back: "Water is <strong>removed</strong>: one H₂O is lost for each new bond.<br>水被<strong>除去</strong>：每形成一個新鍵就失去一分子水。",
    image: "./assets/page01_condensation.png",
    imageAlt: "Diagram of condensation losing water and hydrolysis gaining water.",
  },
  {
    id: 3,
    subtopic: "有機與縮合水解",
    front: "What type of metabolism is hydrolysis?<br>水解屬於哪一類代謝？",
    back: "It is <strong>catabolism</strong> (breakdown).<br>它是<strong>分解代謝</strong>（分解）。",
  },
  {
    id: 4,
    subtopic: "有機與縮合水解",
    front: "When a large molecule is split by hydrolysis, what happens to water?<br>大分子被水解拆開時，水會怎樣？",
    back: "Water is <strong>added</strong>: one H₂O is used to break each bond.<br>水被<strong>加入</strong>：每打斷一個鍵就用掉一分子水。",
  },
  {
    id: 5,
    subtopic: "有機與縮合水解",
    front: "In prolonged starvation, in what order are fuels used?<br>長期饑餓時，能量來源的使用次序是什麼？",
    back: "<strong>Carbohydrates → lipids → proteins</strong> (proteins are the last resort).<br><strong>碳水化合物 → 脂質 → 蛋白質</strong>（蛋白質是最後手段）。",
    image: "./assets/page02_starvation.png",
    imageAlt: "Starvation graph showing glycogen, then lipids, then proteins.",
  },
  {
    id: 6,
    subtopic: "有機與縮合水解",
    front: "Two monosaccharides join by ____ to form a disaccharide.<br>兩分子單醣以____結合形成雙醣。",
    back: "They join by <strong>condensation</strong> (water is lost).<br>它們以<strong>縮合</strong>結合（失去水）。",
  },
  {
    id: 7,
    subtopic: "碳水化合物",
    front: "How does the solubility of monosaccharides compare with polysaccharides?<br>單醣與多醣的溶解性有何分別？",
    back: "Monosaccharides are <strong>soluble</strong>; polysaccharides are <strong>insoluble</strong>.<br>單醣<strong>可溶</strong>；多醣<strong>不溶</strong>。",
  },
  {
    id: 8,
    subtopic: "碳水化合物",
    front: "How does the sweetness of monosaccharides compare with polysaccharides?<br>單醣與多醣的甜味有何分別？",
    back: "Monosaccharides are <strong>sweet</strong>; polysaccharides are <strong>not sweet</strong>.<br>單醣<strong>甜</strong>；多醣<strong>不甜</strong>。",
  },
  {
    id: 9,
    subtopic: "碳水化合物",
    front: "What do reducing sugars do, and which sugar is the exception?<br>還原糖有何作用？例外是哪一種糖？",
    back: "They <strong>donate electrons</strong>, except <strong>sucrose</strong>.<br>它們會<strong>捐出電子</strong>，但<strong>蔗糖</strong>除外。",
  },
  {
    id: 10,
    subtopic: "碳水化合物",
    front: "Which monosaccharide is the main respiratory fuel, and why is it used fast?<br>哪一種單醣是主要呼吸燃料？為何用得快？",
    back: "<strong>Glucose</strong>, because it is directly absorbed and used.<br><strong>葡萄糖</strong>，因為它可以即時被吸收和使用。",
  },
  {
    id: 11,
    subtopic: "碳水化合物",
    front: "Name the five monosaccharides listed in the notes.<br>寫出筆記中的五種單醣。",
    back: "Glucose, fructose, galactose, <strong>ribose</strong>, and <strong>deoxyribose</strong> (in DNA).<br>葡萄糖、果糖、半乳糖、<strong>核糖</strong>和<strong>脱氧核糖</strong>（在 DNA 中）。",
  },
  {
    id: 12,
    subtopic: "碳水化合物",
    front: "How can maltose be formed?<br>麥芽糖可以怎樣形成？",
    back: "It can form from <strong>starch hydrolysis</strong>.<br>它可以由<strong>澱粉水解</strong>形成。",
  },
  {
    id: 13,
    subtopic: "碳水化合物",
    front: "Is sucrose a reducing sugar, and what is its role in plants?<br>蔗糖是還原糖嗎？它在植物中有何角色？",
    back: "It is a <strong>non-reducing sugar</strong> and is the <strong>transport form</strong> of sugar in plants.<br>它是<strong>非還原糖</strong>，也是植物中糖的<strong>運輸形式</strong>。",
  },
  {
    id: 14,
    subtopic: "碳水化合物",
    front: "Where are glycogen and starch stored?<br>肝醣和澱粉分別貯存在哪裏？",
    back: "Glycogen is stored in <strong>animals</strong>; starch is stored in <strong>plants</strong>.<br>肝醣貯存在<strong>動物</strong>；澱粉貯存在<strong>植物</strong>。",
  },
  {
    id: 15,
    subtopic: "碳水化合物",
    front: "What job does cellulose do inside a plant cell?<br>纖維素在植物細胞內有什麼工作？",
    back: "It is a strong, insoluble fibre that <strong>builds and stiffens the cell wall</strong> so the cell keeps its shape.<br>它是堅韌而不溶的纖維，用來<strong>建造並鞏固細胞壁</strong>，使細胞保持形狀。",
  },
  {
    id: 16,
    subtopic: "碳水化合物",
    front: "As dietary fibre in humans, does cellulose give energy, and what two benefits does it have?<br>作為人體膳食纖維，纖維素有沒有能量？有哪兩項益處？",
    back: "It has <strong>no energy value</strong>; it gives fullness and promotes gut <strong>peristalsis</strong>.<br>它<strong>沒有能量</strong>；它能增加飽腹感，並促進腸道<strong>蠕動</strong>。",
  },
  {
    id: 17,
    subtopic: "脂質",
    front: "What is a triglyceride made of?<br>三酸甘油酯由什麼組成？",
    back: "It is made of <strong>1 glycerol and 3 fatty acids</strong>.<br>它由<strong>1 分子甘油和 3 分子脂肪酸</strong>組成。",
    image: "./assets/page06_triglyceride.png",
    imageAlt: "Triglyceride made of one glycerol and three fatty acids.",
  },
  {
    id: 18,
    subtopic: "脂質",
    front: "What is a phospholipid made of?<br>磷脂由什麼組成？",
    back: "It is made of <strong>1 glycerol, 2 fatty acids, and a phosphate group</strong>.<br>它由<strong>1 分子甘油、2 分子脂肪酸和一個磷酸基團</strong>組成。",
    image: "./assets/page06_phospholipid_icon.png",
    imageAlt: "Phospholipid made of phosphate, glycerol, and two fatty acids.",
  },
  {
    id: 19,
    subtopic: "脂質",
    front: "What is the basic structure of steroids, and what are two examples?<br>類固醇的基本結構是什麼？試舉兩個例子。",
    back: "They have <strong>four carbon rings</strong>; examples are cholesterol and sex hormones.<br>它們有<strong>四個碳環</strong>；例子是膽固醇和性荷爾蒙。",
    image: "./assets/page06_steroid.png",
    imageAlt: "Steroid structure with four fused carbon rings.",
  },
  {
    id: 20,
    subtopic: "脂質",
    front: "Which parts of a phospholipid are hydrophilic and which are hydrophobic?<br>磷脂的哪些部分親水？哪些部分疏水？",
    back: "The <strong>head is hydrophilic (polar)</strong> and the <strong>tails are hydrophobic (non-polar)</strong>, so they form a bilayer.<br><strong>頭部親水（極性）</strong>，<strong>尾部疏水（非極性）</strong>，因此會形成雙層。",
    image: "./assets/page07_phospholipid.jpeg",
    imageAlt: "Phospholipid structure showing a hydrophilic head and hydrophobic tails.",
  },
  {
    id: 21,
    subtopic: "脂質",
    front: "How does the energy per gram of lipids compare with carbohydrates and proteins?<br>每克脂質的能量與碳水化合物和蛋白質相比如何？",
    back: "Lipids give about <strong>twice</strong> as much energy (×2).<br>脂質提供約<strong>兩倍</strong>能量（×2）。",
  },
  {
    id: 22,
    subtopic: "脂質",
    front: "Besides energy, name four functions of triglycerides.<br>除能量外，寫出三酸甘油酯的四項功能。",
    back: "They protect organs, insulate nerves, waterproof surfaces, and reduce heat loss (subcutaneous fat).<br>它們保護器官、絕緣神經、防水，並減少熱量散失（皮下脂肪）。",
  },
  {
    id: 23,
    subtopic: "脂質",
    front: "At room temperature, what state are saturated fatty acids, and how do they affect health?<br>室溫下飽和脂肪酸是什麼狀態？對健康有何影響？",
    back: "They are <strong>solid</strong> and less healthy, because they can cause clots and <strong>cardiovascular disease</strong>.<br>它們是<strong>固態</strong>而且較不健康，因為可導致凝血和<strong>心血管疾病</strong>。",
  },
  {
    id: 24,
    subtopic: "脂質",
    front: "At room temperature, what state are unsaturated fatty acids, and how do they affect health?<br>室溫下不飽和脂肪酸是什麼狀態？對健康有何影響？",
    back: "They are <strong>liquid</strong> and more healthy.<br>它們是<strong>液態</strong>而且較健康。",
  },
  {
    id: 25,
    subtopic: "脂質",
    front: "Why are trans fatty acids the worst type?<br>為何反式脂肪酸最差？",
    back: "They force unsaturated fats to behave like saturated fats, so enzymes are <strong>unfit to hydrolyze</strong> them.<br>它們使不飽和脂肪變得像飽和脂肪，因此酶<strong>難以水解</strong>它們。",
  },
  {
    id: 26,
    subtopic: "脂質",
    front: "Before you add up food energy, what multiplier must you use for lipids?<br>計算食物總能量前，脂質要乘以多少？",
    back: "Multiply lipids by <strong>×2</strong>.<br>脂質要乘以<strong>2</strong>。",
  },
  {
    id: 27,
    subtopic: "脂質",
    front: "What are three roles of subcutaneous fat?<br>皮下脂肪有哪三項作用？",
    back: "It stores energy, absorbs shock, and <strong>reduces heat loss</strong>.<br>它貯存能量、緩衝撞擊，並<strong>減少熱量散失</strong>。",
  },
  {
    id: 28,
    subtopic: "蛋白質",
    front: "Which elements are found in proteins?<br>蛋白質含有哪些元素？",
    back: "Proteins contain <strong>C, H, O, and N</strong>, and some also contain <strong>S</strong>.<br>蛋白質含有<strong>碳、氫、氧和氮</strong>，部分還含有<strong>硫</strong>。",
    image: "./assets/page02_condensation_eq.png",
    imageAlt: "Table of elements in organic molecules, including proteins.",
  },
  {
    id: 29,
    subtopic: "蛋白質",
    front: "How many types of amino acids are there, and why?<br>胺基酸有多少種？原因是什麼？",
    back: "There are <strong>20</strong> types, because there are 20 types of side chain.<br>共有<strong>20</strong>種，因為有 20 種側鏈。",
  },
  {
    id: 30,
    subtopic: "蛋白質",
    front: "What three groups are found on an amino acid?<br>胺基酸上有哪三個基團？",
    back: "An <strong>amino group</strong> (N), a <strong>carboxyl group</strong> (C), and a <strong>side chain</strong> (R).<br><strong>氨基</strong>（N）、<strong>羧基</strong>（C）和<strong>側鏈</strong>（R）。",
    image: "./assets/page09_amino_acid.png",
    imageAlt: "Amino acid showing the amino group, carboxyl group, and side chain.",
  },
  {
    id: 31,
    subtopic: "蛋白質",
    front: "When two amino acids condense, which groups join, and what is the product?<br>兩分子胺基酸縮合時，哪些基團相連？產物是什麼？",
    back: "The <strong>amino group</strong> joins the <strong>carboxyl group</strong> to form a <strong>dipeptide</strong>.<br><strong>氨基</strong>與<strong>羧基</strong>相連，形成<strong>二肽</strong>。",
    image: "./assets/page11_dipeptide.png",
    imageAlt: "Dipeptide forming with a peptide bond as water is lost.",
  },
  {
    id: 32,
    subtopic: "蛋白質",
    front: "What is the key difference between a polypeptide and a protein?<br>多肽與蛋白質的關鍵分別是什麼？",
    back: "A polypeptide is a <strong>linear chain</strong>; a protein has a <strong>3D conformation</strong> after folding.<br>多肽是<strong>線性鏈</strong>；蛋白質摺疊後具有<strong>三維構象</strong>。",
    image: "./assets/page12_folding.png",
    imageAlt: "A polypeptide folding into a protein.",
  },
  {
    id: 33,
    subtopic: "蛋白質",
    front: "What bonds hold the folded 3D conformation of a protein?<br>甚麼鍵維持蛋白質摺疊後的三維構象？",
    back: "<strong>Hydrogen bonds</strong> between amino acids hold the fold.<br>胺基酸之間的<strong>氫鍵</strong>維持摺疊。",
  },
  {
    id: 34,
    subtopic: "蛋白質",
    front: "What determines a protein’s 3D fold and function?<br>甚麼決定蛋白質的三維摺疊和功能？",
    back: "The <strong>amino acid sequence</strong>, which is set by DNA.<br><strong>胺基酸序列</strong>，而序列由 DNA 決定。",
  },
  {
    id: 35,
    subtopic: "蛋白質",
    front: "What is the difference between essential and non-essential amino acids?<br>必需胺基酸與非必需胺基酸有何分別？",
    back: "Essential amino acids come <strong>only from food</strong>; non-essential ones can be <strong>made by the body</strong>.<br>必需胺基酸<strong>只能從食物獲得</strong>；非必需胺基酸<strong>可由身體合成</strong>。",
  },
  {
    id: 36,
    subtopic: "蛋白質",
    front: "Name five protein functions from the notes.<br>寫出筆記中蛋白質的五項功能。",
    back: "Cell membrane proteins, growth and repair, <strong>enzymes</strong>, hormones, and <strong>antibodies</strong>.<br>細胞膜蛋白、生長與修復、<strong>酶</strong>、激素和<strong>抗體</strong>。",
  },
  {
    id: 37,
    subtopic: "蛋白質",
    front: "Among antibodies, antigens, and antibiotics, which are proteins?<br>抗體、抗原和抗生素之中，哪些是蛋白質？",
    back: "Antibodies and antigens are <strong>proteins</strong>; antibiotics are <strong>not proteins</strong>.<br>抗體和抗原是<strong>蛋白質</strong>；抗生素<strong>不是蛋白質</strong>。",
  },
  {
    id: 38,
    subtopic: "蛋白質",
    front: "Is denaturation reversible, and what causes it?<br>變性可否逆轉？成因是什麼？",
    back: "It is <strong>irreversible</strong>, and is caused by high temperature or a sub-optimal <strong>pH</strong>.<br>它是<strong>不可逆</strong>的，成因是高溫或非最適的<strong>pH</strong>。",
    image: "./assets/page12_denature.png",
    imageAlt: "A native protein unfolding when it is denatured.",
  },
  {
    id: 39,
    subtopic: "蛋白質",
    front: "Denaturation causes loss of ____, which then causes loss of ____.<br>變性會失去____，接着會失去____。",
    back: "Loss of <strong>conformation</strong> causes loss of <strong>function</strong>.<br>失去<strong>構象</strong>會導致失去<strong>功能</strong>。",
  },
  {
    id: 40,
    subtopic: "食物分類與礦物質",
    front: "What are the energy values of carbohydrates, proteins, and lipids in kJ/g?<br>碳水化合物、蛋白質和脂質的能量值（kJ/g）分別是多少？",
    back: "About <strong>17</strong>, <strong>17</strong>, and <strong>37</strong> kJ/g (lipids are about twice as much).<br>約 <strong>17</strong>、<strong>17</strong> 和 <strong>37</strong> kJ/g（脂質約為兩倍）。",
  },
  {
    id: 41,
    subtopic: "食物分類與礦物質",
    front: "What are examples of primary and protective food substances?<br>主要食物和保護性食物的例子是什麼？",
    back: "Primary: carbohydrates, proteins, and lipids. Protective: dietary fibre, vitamins, minerals, ions, and water.<br>主要：碳水化合物、蛋白質、脂質。保護性：膳食纖維、維生素、礦物質、離子和水。",
  },
  {
    id: 42,
    subtopic: "食物分類與礦物質",
    front: "Do minerals give energy, and how much is needed?<br>礦物質有沒有能量？需要量多少？",
    back: "Minerals give <strong>no energy</strong> and are needed in <strong>small amounts</strong> to regulate metabolism and build tissues.<br>礦物質<strong>沒有能量</strong>，只需<strong>少量</strong>，用以調節代謝和建構組織。",
  },
  {
    id: 43,
    subtopic: "食物分類與礦物質",
    front: "Where is calcium stored, and what is it a main component of?<br>鈣貯存在哪裏？它是甚麼的主要組成？",
    back: "About 99% is stored in <strong>bones and teeth</strong>, and it is a <strong>component of bones and teeth</strong>.<br>約 99% 貯存在<strong>骨與牙齒</strong>，它是<strong>骨與牙齒的組成成分</strong>。",
  },
  {
    id: 44,
    subtopic: "食物分類與礦物質",
    front: "What calcium-deficiency disease occurs in children and in adults?<br>兒童和成人缺乏鈣會分別患上甚麼病？",
    back: "Children get <strong>rickets</strong>; adults get <strong>osteoporosis</strong>.<br>兒童會患<strong>佝僂病</strong>；成人會患<strong>骨質疏鬆</strong>。",
  },
  {
    id: 45,
    subtopic: "食物分類與礦物質",
    front: "What is the key function of iron, and what deficiency disease results?<br>鐵的主要功能是什麼？缺乏會引致甚麼病？",
    back: "Iron is used for oxygen transport in <strong>hemoglobin</strong>; deficiency causes <strong>anemia</strong>.<br>鐵用於<strong>血紅蛋白</strong>運送氧氣；缺乏會引致<strong>貧血</strong>。",
  },
  {
    id: 46,
    subtopic: "無機離子",
    front: "What are the main roles of nitrate (NO₃⁻) in plants, and how does deficiency look?<br>硝酸根離子在植物中的主要作用是什麼？缺乏時外表如何？",
    back: "It is used for protein synthesis and chlorophyll; deficiency causes poor growth and <strong>yellowing leaves</strong>.<br>它用於蛋白質合成和葉綠素；缺乏會令生長差和<strong>葉片變黃</strong>。",
  },
  {
    id: 47,
    subtopic: "無機離子",
    front: "What is the function of iodine (I⁻), and what is the classic deficiency disease?<br>碘離子的功能是什麼？典型缺乏症是甚麼？",
    back: "It is needed for thyroid hormone and metabolism; deficiency causes <strong>goiter</strong>.<br>它用於甲狀腺激素和代謝；缺乏會引致<strong>甲狀腺腫大</strong>。",
  },
];
