/** Ch4 Enzymes — pages 1–8 (bilingual EN + 中文) */
export const FLASHCARD_TAGS = ["Biology", "Ch4", "Enzymes", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "代謝與反應速率",
    front: "How do anabolism and catabolism differ in energy?<br>合成代謝和分解代謝在能量上有何分別？",
    back: "Anabolism <strong>absorbs</strong> energy (simple → complex); catabolism <strong>releases</strong> energy (complex → simple).<br>合成代謝<strong>吸收</strong>能量（簡單→複雜）；分解代謝<strong>釋放</strong>能量（複雜→簡單）。",
    image: "./assets/img001.jpg",
    imageAlt: "Energy graphs of anabolic (energy absorbed) and catabolic (energy released) reactions.",
  },
  {
    id: 2,
    subtopic: "代謝與反應速率",
    front: "Give one example of anabolism and one of catabolism.<br>各舉一例合成代謝和分解代謝。",
    back: "Anabolism: <strong>condensation / photosynthesis</strong>. Catabolism: <strong>hydrolysis / respiration</strong>.<br>合成代謝：<strong>縮合／光合作用</strong>。分解代謝：<strong>水解／呼吸作用</strong>。",
  },
  {
    id: 3,
    subtopic: "代謝與反應速率",
    front: "Name two ways to measure an enzyme reaction rate.<br>寫出兩種量度酶反應速率的方法。",
    back: "Rate of <strong>using substrate</strong>, or rate of <strong>forming product</strong>.<br><strong>消耗底物</strong>的速率，或<strong>形成產物</strong>的速率。",
  },
  {
    id: 4,
    subtopic: "代謝與反應速率",
    front: "Why does an enzyme graph often level off?<br>為何酶反應曲線常常變平？",
    back: "The rate is <strong>limited by another factor</strong>, such as substrate amount or number of active sites.<br>速率被<strong>其他因素限制</strong>，例如底物量或活性部位數目。",
  },
  {
    id: 5,
    subtopic: "代謝與反應速率",
    front: "In anabolism, how does product energy compare with reactant energy?<br>合成代謝中，產物能量與反應物相比如何？",
    back: "Product energy is <strong>higher</strong> than reactant energy.<br>產物能量<strong>高於</strong>反應物。",
    image: "./assets/img001.jpg",
    imageAlt: "Energy graphs of anabolic (energy absorbed) and catabolic (energy released) reactions.",
  },
  {
    id: 6,
    subtopic: "酶的特性",
    front: "What type of molecule are enzymes?<br>酶是哪一類分子？",
    back: "Enzymes are <strong>proteins</strong> with a specific <strong>3D conformation</strong>.<br>酶是具特定<strong>三維構象</strong>的<strong>蛋白質</strong>。",
  },
  {
    id: 7,
    subtopic: "酶的特性",
    front: "Why does denaturation stop enzyme function?<br>為何變性會使酶失去功能？",
    back: "The active site <strong>loses its 3D shape</strong>, so no enzyme–substrate complex can form.<br>活性部位<strong>失去三維形狀</strong>，無法形成酶－底物複合物。",
  },
  {
    id: 8,
    subtopic: "酶的特性",
    front: "Why can amylase act on starch but not on glucose?<br>為何澱粉酶能作用於澱粉卻不能作用於葡萄糖？",
    back: "Enzyme action is <strong>specific</strong>: the active site fits starch, not glucose.<br>酶作用具<strong>專一性</strong>：活性部位配合澱粉，不配合葡萄糖。",
  },
  {
    id: 9,
    subtopic: "酶的特性",
    front: "How do enzymes speed up a reaction?<br>酶如何加快反應？",
    back: "They <strong>lower activation energy</strong> when an enzyme–substrate complex forms.<br>形成酶－底物複合物時，它們會<strong>降低活化能</strong>。",
  },
  {
    id: 10,
    subtopic: "酶的特性",
    front: "In lock-and-key, what binds the active site?<br>鎖鑰假說中，甚麼結合活性部位？",
    back: "A substrate with a <strong>complementary shape</strong>, by random collision.<br>具<strong>互補形狀</strong>的底物，以隨機碰撞結合。",
    image: "./assets/img004.jpg",
    imageAlt: "Lock-and-key enzyme cycle: substrate binds the active site, products leave, enzyme is reused.",
  },
  {
    id: 11,
    subtopic: "酶的特性",
    front: "Why are enzymes needed only in small amounts?<br>為何只需少量酶？",
    back: "They are <strong>unchanged</strong> after the reaction, so they can be <strong>reused</strong>.<br>反應後酶<strong>不變</strong>，因此可以<strong>重用</strong>。",
  },
  {
    id: 12,
    subtopic: "酶的特性",
    front: "Should you write “the enzyme digests starch”?<br>可否寫「酶消化澱粉」？",
    back: "<strong>No.</strong> Write “the enzyme <strong>catalyses</strong> the digestion of starch”.<br><strong>不可。</strong>應寫「酶<strong>催化</strong>澱粉的消化」。",
  },
  {
    id: 13,
    subtopic: "酶的特性",
    front: "Can one enzyme catalyse both forward and reverse reactions?<br>一種酶能否同時催化正向和逆向反應？",
    back: "<strong>Yes</strong>, until equilibrium; direction depends on concentrations.<br><strong>可以</strong>，直至平衡；方向取決於濃度。",
  },
  {
    id: 14,
    subtopic: "酶的特性",
    front: "Why is a boiled enzyme used as a control?<br>為何用煮過的酶作對照？",
    back: "Boiling <strong>denatures</strong> it, so any change must be due to the working enzyme.<br>煮沸會使它<strong>變性</strong>，因此變化必來自有效的酶。",
  },
  {
    id: 15,
    subtopic: "溫度與pH",
    front: "Why is enzyme activity low at low temperature?<br>為何低溫時酶活性低？",
    back: "<strong>Low kinetic energy</strong> means fewer collisions, so fewer enzyme–substrate complexes.<br><strong>動能低</strong>使碰撞較少，酶－底物複合物也較少。",
  },
  {
    id: 16,
    subtopic: "溫度與pH",
    front: "What happens as temperature rises towards the optimum?<br>溫度升向最適溫度時會怎樣？",
    back: "Collision chance <strong>rises</strong>, so the reaction rate <strong>increases</strong>.<br>碰撞機會<strong>增加</strong>，反應速率也<strong>加快</strong>。",
  },
  {
    id: 17,
    subtopic: "溫度與pH",
    front: "What happens far above the optimum temperature?<br>遠高於最適溫度時會怎樣？",
    back: "The enzyme is <strong>irreversibly denatured</strong> and the rate falls.<br>酶會<strong>不可逆變性</strong>，速率下降。",
  },
  {
    id: 18,
    subtopic: "溫度與pH",
    front: "Is denaturation reversible?<br>變性可否逆轉？",
    back: "<strong>No. Denaturation is irreversible.</strong><br><strong>不可。變性是不可逆的。</strong>",
  },
  {
    id: 19,
    subtopic: "溫度與pH",
    front: "At what pH do pepsin, salivary amylase, and intestinal enzymes work best?<br>胃蛋白酶、唾液澱粉酶和腸酶的最適 pH 分別如何？",
    back: "Pepsin: <strong>acidic</strong>. Salivary amylase: <strong>about neutral</strong>. Intestinal enzymes: <strong>alkaline</strong>.<br>胃蛋白酶：<strong>酸性</strong>。唾液澱粉酶：<strong>近中性</strong>。腸酶：<strong>鹼性</strong>。",
  },
  {
    id: 20,
    subtopic: "溫度與pH",
    front: "What two conditions commonly denature enzymes?<br>哪兩種條件常使酶變性？",
    back: "<strong>High temperature (boiling)</strong> and <strong>sub-optimal pH</strong>.<br><strong>高溫（煮沸）</strong>和<strong>非最適 pH</strong>。",
  },
  {
    id: 21,
    subtopic: "實驗與曲線",
    front: "Why is there a clear zone around a well in an agar plate?<br>為何瓊脂平板的小井周圍會有透明圈？",
    back: "Enzyme <strong>diffuses out</strong> and <strong>catalyses breakdown</strong> of the substrate into simpler molecules.<br>酶<strong>擴散出來</strong>並<strong>催化</strong>底物分解成較簡單分子。",
  },
  {
    id: 22,
    subtopic: "實驗與曲線",
    front: "Why is a clear zone larger?<br>為何透明圈會較大？",
    back: "<strong>Higher enzyme concentration</strong>, so more enzyme diffuses out in the same time.<br><strong>酶濃度較高</strong>，相同時間擴散出來的酶較多。",
  },
  {
    id: 23,
    subtopic: "實驗與曲線",
    front: "Why is there no clear zone?<br>為何沒有透明圈？",
    back: "The enzyme is <strong>denatured</strong> or <strong>inactive</strong>, so it cannot catalyse breakdown.<br>酶已<strong>變性</strong>或<strong>不活躍</strong>，不能催化分解。",
  },
  {
    id: 24,
    subtopic: "實驗與曲線",
    front: "On a time graph, which curve is the substrate?<br>時間曲線中，哪一條是底物？",
    back: "The curve that <strong>starts high and falls</strong> as product forms.<br><strong>開始高然後下降</strong>的那條，因為產物在形成。",
    image: "./assets/img008.jpg",
    imageAlt: "Time graph of substrate falling and product rising during an enzyme reaction.",
  },
  {
    id: 25,
    subtopic: "實驗與曲線",
    front: "How should you state the optimum if the graph peak is not sharp?<br>若曲線高峰不尖，應如何說最適溫度？",
    back: "Say the optimum is <strong>around</strong> that temperature, not exactly that value.<br>應說最適溫度<strong>大約</strong>是該值，不要說剛好是該值。",
  },
  {
    id: 26,
    subtopic: "實驗與曲線",
    front: "What stays the same in a fair enzyme control?<br>酶對照實驗中哪些要保持不變？",
    back: "All conditions except the enzyme, which is replaced by <strong>water or boiled enzyme</strong>.<br>除酶以外的條件都相同；酶改為<strong>水或煮過的酶</strong>。",
  },
  {
    id: 27,
    subtopic: "實驗與曲線",
    front: "Substrate is used at the same rate as product is formed. Why?<br>為何底物消耗速率與產物形成速率相同？",
    back: "Each substrate molecule becomes product in the same reaction.<br>每個底物分子在同一反應中變成產物。",
  },
  {
    id: 28,
    subtopic: "抑制劑",
    front: "How does a competitive inhibitor work?<br>競爭性抑制劑如何作用？",
    back: "It has a <strong>similar shape</strong> to the substrate and <strong>competes for the active site</strong>.<br>它與底物<strong>形狀相似</strong>，並<strong>爭奪活性部位</strong>。",
  },
  {
    id: 29,
    subtopic: "抑制劑",
    front: "How does a non-competitive inhibitor work?<br>非競爭性抑制劑如何作用？",
    back: "It binds elsewhere and <strong>alters the active-site shape</strong>, so substrate cannot fit.<br>它結合在其他位置並<strong>改變活性部位形狀</strong>，使底物無法嵌入。",
  },
  {
    id: 30,
    subtopic: "抑制劑",
    front: "How can you reduce competitive inhibition?<br>如何減輕競爭性抑制？",
    back: "<strong>Increase substrate</strong> (or increase enzyme).<br><strong>增加底物</strong>（或增加酶）。",
  },
  {
    id: 31,
    subtopic: "抑制劑",
    front: "How can you reduce non-competitive inhibition?<br>如何減輕非競爭性抑制？",
    back: "<strong>Increase enzyme</strong> (more active sites). Raising substrate does not help.<br><strong>增加酶</strong>（更多活性部位）。增加底物沒有幫助。",
  },
  {
    id: 32,
    subtopic: "抑制劑",
    front: "Why can inhibitors kill bacteria?<br>為何抑制劑能殺死細菌？",
    back: "They can <strong>inhibit respiration</strong>, so active transport and other processes stop.<br>它們能<strong>抑制呼吸</strong>，使主動運輸等過程停止。",
  },
  {
    id: 33,
    subtopic: "應用",
    front: "Which enzyme makes fruit juice clearer, and how?<br>哪種酶使果汁更清澈？如何做到？",
    back: "<strong>Pectinase</strong> breaks down cell walls.<br><strong>果膠酶</strong>分解細胞壁。",
  },
  {
    id: 34,
    subtopic: "應用",
    front: "Which enzyme tenderises meat?<br>哪種酶使肉變嫩？",
    back: "<strong>Proteases</strong> such as papain break down meat proteins.<br><strong>蛋白酶</strong>（如木瓜蛋白酶）分解肉類蛋白質。",
  },
  {
    id: 35,
    subtopic: "應用",
    front: "Which enzyme is used in stonewashed jeans?<br>水洗牛仔褲使用哪種酶？",
    back: "<strong>Cellulase</strong> breaks down cellulose fibres.<br><strong>纖維素酶</strong>分解纖維素纖維。",
  },
  {
    id: 36,
    subtopic: "應用",
    front: "How does lysozyme act as an antibacterial drug?<br>溶菌酶如何作為抗菌藥物？",
    back: "It <strong>breaks down bacterial cell walls</strong>.<br>它<strong>分解細菌細胞壁</strong>。",
  },
  {
    id: 37,
    subtopic: "應用",
    front: "Which enzyme is used to clean protein off contact lenses?<br>哪種酶用來清除隱形眼鏡上的蛋白質？",
    back: "<strong>Proteases</strong>.<br><strong>蛋白酶</strong>。",
  },
  {
    id: 38,
    subtopic: "應用",
    front: "Which enzyme helps clean oil spills?<br>哪種酶有助清理漏油？",
    back: "<strong>Lipases</strong> break down the oil.<br><strong>脂肪酶</strong>分解油。",
  },
];
