/** Ch3 Membrane transport — pages 1–13 (bilingual EN + 中文) */
export const FLASHCARD_TAGS = ["Biology", "Ch3", "Membrane", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "流動鑲嵌與磷脂",
    front: "What two ideas does the fluid mosaic model describe?<br>流動鑲嵌模型描述哪兩個概念？",
    back: "<strong>Fluid</strong> means the phospholipid bilayer can move; <strong>mosaic</strong> means proteins are interspersed in the membrane.<br><strong>流動</strong>指磷脂雙層可以移動；<strong>鑲嵌</strong>指蛋白質穿插在膜中。",
    image: "./assets/img001.jpg",
    imageAlt: "Phospholipid hydrophilic head and hydrophobic tails compared with a triglyceride.",
  },
  {
    id: 2,
    subtopic: "流動鑲嵌與磷脂",
    front: "Why can a cell membrane fold in during phagocytosis?<br>細胞膜為何能在吞噬時向內摺入？",
    back: "Because the phospholipid bilayer is <strong>fluid</strong> and can move laterally.<br>因為磷脂雙層具<strong>流動性</strong>，可以橫向移動。",
  },
  {
    id: 3,
    subtopic: "流動鑲嵌與磷脂",
    front: "Why is the phospholipid head hydrophilic?<br>磷脂頭部為何親水？",
    back: "It has a <strong>polar phosphate group</strong>, which faces towards water.<br>它有<strong>極性磷酸基團</strong>，面向水。",
  },
  {
    id: 4,
    subtopic: "流動鑲嵌與磷脂",
    front: "Why are the phospholipid tails hydrophobic?<br>磷脂尾部為何疏水？",
    back: "They are <strong>non-polar fatty acids</strong>, which face away from water.<br>它們是<strong>非極性脂肪酸</strong>，背向水。",
  },
  {
    id: 5,
    subtopic: "流動鑲嵌與磷脂",
    front: "In water, how do phospholipids arrange to form a cell membrane?<br>在水中，磷脂如何排列形成細胞膜？",
    back: "They form a <strong>tail-to-tail bilayer</strong>.<br>它們形成<strong>尾對尾的雙層</strong>。",
    image: "./assets/img001.jpg",
    imageAlt: "Phospholipid hydrophilic head and hydrophobic tails compared with a triglyceride.",
  },
  {
    id: 6,
    subtopic: "流動鑲嵌與磷脂",
    front: "Does “mosaic” explain membrane fluidity?<br>「鑲嵌」能否解釋膜的流動性？",
    back: "<strong>No.</strong> Mosaic is about protein distribution, not fluidity.<br><strong>不能。</strong>鑲嵌是關於蛋白質分布，與流動性無關。",
  },
  {
    id: 7,
    subtopic: "膜蛋白",
    front: "What do membrane enzymes do, and how are they often inserted?<br>膜上的酶有何作用？通常如何插入？",
    back: "They <strong>catalyse</strong> reactions and are often <strong>half-inserted</strong>.<br>它們<strong>催化</strong>反應，通常是<strong>半插入</strong>。",
  },
  {
    id: 8,
    subtopic: "膜蛋白",
    front: "Do channel proteins need a shape change?<br>通道蛋白需要改變形狀嗎？",
    back: "<strong>No.</strong> They are fully inserted and need no shape change.<br><strong>不需要。</strong>它們全插入，不必改變形狀。",
  },
  {
    id: 9,
    subtopic: "膜蛋白",
    front: "How do carrier proteins move substances?<br>輸運蛋白如何運送物質？",
    back: "They need <strong>binding and a shape change</strong>, and often work with active transport.<br>它們需要<strong>結合並改變形狀</strong>，常與主動運輸一起出現。",
  },
  {
    id: 10,
    subtopic: "膜蛋白",
    front: "What do receptor proteins bind, and what is one example?<br>受體蛋白結合什麼？試舉一例。",
    back: "They bind <strong>chemical messengers</strong>; for example a bacterial antigen binds a WBC receptor.<br>它們結合<strong>化學訊息</strong>；例如細菌抗原結合白血球受體。",
  },
  {
    id: 11,
    subtopic: "膜蛋白",
    front: "What is a glycoprotein used as in ABO blood groups?<br>糖蛋白在 ABO 血型中作什麼用途？",
    back: "It acts as an <strong>antigen</strong> (an “ID card”) on the cell surface.<br>它作為細胞表面的<strong>抗原</strong>（「身份證」）。",
  },
  {
    id: 12,
    subtopic: "通透性與膜損傷",
    front: "How do oxygen and carbon dioxide cross the membrane?<br>氧氣和二氧化碳如何穿過細胞膜？",
    back: "They are small and non-polar, so they cross the <strong>phospholipid bilayer</strong>.<br>它們細小且非極性，因此穿過<strong>磷脂雙層</strong>。",
  },
  {
    id: 13,
    subtopic: "通透性與膜損傷",
    front: "How do glucose, amino acids, and ions cross the membrane?<br>葡萄糖、胺基酸和離子如何穿過細胞膜？",
    back: "They use <strong>channel or carrier proteins</strong>.<br>它們使用<strong>通道蛋白或輸運蛋白</strong>。",
  },
  {
    id: 14,
    subtopic: "通透性與膜損傷",
    front: "How do starch and proteins enter a cell?<br>澱粉和蛋白質如何進入細胞？",
    back: "They are too large, so they enter by <strong>membrane folding</strong> (phagocytosis).<br>它們太大，因此以<strong>膜摺疊</strong>（吞噬作用）進入。",
  },
  {
    id: 15,
    subtopic: "通透性與膜損傷",
    front: "What happens to a fully damaged cell membrane?<br>細胞膜完全受損後會怎樣？",
    back: "It becomes <strong>fully permeable</strong>, so everything can pass.<br>它變成<strong>全透性</strong>，所有物質都能通過。",
  },
  {
    id: 16,
    subtopic: "通透性與膜損傷",
    front: "If beetroot tissue leaks colour, what does that show?<br>若甜菜根組織漏出顏色，代表什麼？",
    back: "The cell membrane is <strong>damaged</strong>.<br>細胞膜已<strong>受損</strong>。",
  },
  {
    id: 17,
    subtopic: "通透性與膜損傷",
    front: "Name two treatments that can damage membranes.<br>寫出兩種會損傷細胞膜的處理。",
    back: "<strong>Boiling</strong> and <strong>organic solvents</strong> (also detergents, extreme pH).<br><strong>煮沸</strong>和<strong>有機溶劑</strong>（也有清潔劑、極端 pH）。",
  },
  {
    id: 18,
    subtopic: "擴散",
    front: "What is diffusion, and when does net movement stop?<br>甚麼是擴散？淨移動何時停止？",
    back: "It is net movement <strong>down a concentration gradient</strong>; net movement stops at <strong>equilibrium</strong>.<br>它是沿<strong>濃度梯度</strong>的淨移動；達到<strong>平衡</strong>時淨移動停止。",
  },
  {
    id: 19,
    subtopic: "擴散",
    front: "Does diffusion need energy or a living membrane?<br>擴散需要能量或活膜嗎？",
    back: "<strong>No.</strong> It is passive and can occur with or without a membrane.<br><strong>不需要。</strong>它是被動的，有沒有膜都可以發生。",
  },
  {
    id: 20,
    subtopic: "擴散",
    front: "Name three factors that make diffusion faster.<br>寫出三個使擴散加快的因素。",
    back: "A <strong>steeper gradient</strong>, <strong>larger surface area</strong>, and a <strong>shorter distance</strong> (also higher temperature or smaller particles).<br><strong>更陡的梯度</strong>、<strong>更大表面積</strong>和<strong>更短距離</strong>（還有較高溫度或較小粒子）。",
  },
  {
    id: 21,
    subtopic: "擴散",
    front: "Why are villi and air sacs one cell thick?<br>為何絨毛和氣囊只有一層細胞厚？",
    back: "A short distance makes <strong>diffusion faster</strong>.<br>距離短使<strong>擴散更快</strong>。",
  },
  {
    id: 22,
    subtopic: "擴散",
    front: "Why does a blood supply keep diffusion fast?<br>為何血液供應能保持擴散快速？",
    back: "It <strong>removes products</strong>, so a steep concentration gradient is maintained.<br>它會<strong>運走產物</strong>，從而維持陡的濃度梯度。",
  },
  {
    id: 23,
    subtopic: "滲透",
    front: "What two conditions are needed for osmosis?<br>滲透需要哪兩個條件？",
    back: "A <strong>differentially permeable membrane</strong> and a <strong>water potential difference</strong>.<br><strong>差異滲透膜</strong>和<strong>水勢差</strong>。",
  },
  {
    id: 24,
    subtopic: "滲透",
    front: "Define osmosis.<br>定義滲透。",
    back: "It is the net movement of water across a differentially permeable membrane from <strong>higher to lower water potential</strong>.<br>水分子穿過差異滲透膜，從<strong>水勢較高</strong>處向<strong>水勢較低</strong>處淨移動。",
    image: "./assets/img005.jpg",
    imageAlt: "Osmosis diagram: water moves from higher to lower water potential across a differentially permeable membrane.",
  },
  {
    id: 25,
    subtopic: "滲透",
    front: "Does osmosis need energy?<br>滲透需要能量嗎？",
    back: "<strong>No.</strong> It is a <strong>passive</strong> process.<br><strong>不需要。</strong>它是<strong>被動</strong>過程。",
  },
  {
    id: 26,
    subtopic: "滲透",
    front: "Does “no net movement” mean water has stopped moving?<br>「沒有淨移動」是否代表水已停止移動？",
    back: "<strong>No.</strong> Water still moves both ways, but the two rates are equal.<br><strong>不是。</strong>水仍雙向移動，只是兩邊速率相等。",
  },
  {
    id: 27,
    subtopic: "滲透",
    front: "What happens to an animal cell in distilled water?<br>動物細胞在蒸餾水中會怎樣？",
    back: "Water enters by osmosis, so the cell <strong>swells and may burst</strong>.<br>水以滲透進入，細胞會<strong>膨脹甚至破裂</strong>。",
    image: "./assets/img012.jpg",
    imageAlt: "Animal and plant cells in isotonic, hypotonic, and hypertonic solutions.",
  },
  {
    id: 28,
    subtopic: "滲透",
    front: "What happens to a plant cell in distilled water?<br>植物細胞在蒸餾水中會怎樣？",
    back: "Water enters by osmosis and the cell becomes <strong>turgid</strong>; the cell wall stops it bursting.<br>水以滲透進入，細胞變得<strong>膨脹</strong>；細胞壁防止它破裂。",
    image: "./assets/img012.jpg",
    imageAlt: "Animal and plant cells in isotonic, hypotonic, and hypertonic solutions.",
  },
  {
    id: 29,
    subtopic: "滲透",
    front: "What happens to a plant cell in concentrated sucrose solution?<br>植物細胞在濃蔗糖溶液中會怎樣？",
    back: "Water leaves by osmosis and the cell becomes <strong>plasmolysed</strong> (membrane pulls off the wall).<br>水以滲透離開，細胞發生<strong>質壁分離</strong>（細胞膜離開細胞壁）。",
    image: "./assets/img012.jpg",
    imageAlt: "Animal and plant cells in isotonic, hypotonic, and hypertonic solutions.",
  },
  {
    id: 30,
    subtopic: "滲透",
    front: "What does hypotonic, hypertonic, and isotonic mean for a cell?<br>對細胞而言，低滲、高滲和等滲代表什麼？",
    back: "Hypotonic: water <strong>in</strong>. Hypertonic: water <strong>out</strong>. Isotonic: <strong>no net</strong> water movement.<br>低滲：水<strong>進入</strong>。高滲：水<strong>離開</strong>。等滲：<strong>沒有淨</strong>水移動。",
  },
  {
    id: 31,
    subtopic: "滲透",
    front: "A peeled potato cylinder does not change length in 6% salt. What does this mean?<br>去皮馬鈴薯柱在 6% 鹽溶液中長度不變，代表什麼？",
    back: "The potato is <strong>isotonic</strong> to 6% salt, so water potentials are equal.<br>馬鈴薯與 6% 鹽溶液<strong>等滲</strong>，兩邊水勢相等。",
  },
  {
    id: 32,
    subtopic: "滲透",
    front: "Why can a potato with skin not show osmosis?<br>為何帶皮馬鈴薯不能顯示滲透？",
    back: "The skin is <strong>impermeable</strong>, so water cannot cross.<br>表皮<strong>不能透</strong>，水無法通過。",
  },
  {
    id: 33,
    subtopic: "滲透",
    front: "Why does a boiled potato not show osmosis?<br>為何煮過的馬鈴薯不能顯示滲透？",
    back: "Boiling <strong>destroys</strong> the membrane, so it is fully permeable.<br>煮沸會<strong>破壞</strong>細胞膜，使它變成全透性。",
  },
  {
    id: 34,
    subtopic: "滲透",
    front: "How do some freshwater protozoa avoid bursting?<br>一些淡水原生動物如何避免脹破？",
    back: "They use <strong>contractile vacuoles</strong> to pump out extra water.<br>它們用<strong>伸縮泡</strong>把多餘的水排出。",
  },
  {
    id: 35,
    subtopic: "主動運輸與吞噬",
    front: "What does active transport need that diffusion does not?<br>主動運輸需要擴散所沒有的什麼？",
    back: "It needs <strong>energy from respiration</strong> and a <strong>living membrane</strong>.<br>它需要<strong>呼吸提供能量</strong>和<strong>活膜</strong>。",
  },
  {
    id: 36,
    subtopic: "主動運輸與吞噬",
    front: "Can active transport go against a concentration gradient?<br>主動運輸能否逆濃度梯度進行？",
    back: "<strong>Yes</strong>, and it can also go along the gradient <strong>faster than diffusion</strong>.<br><strong>可以</strong>，也可以沿梯度但比擴散<strong>更快</strong>。",
  },
  {
    id: 37,
    subtopic: "主動運輸與吞噬",
    front: "Cyanide is added to root cells. Which process stops first?<br>把氰化物加到根細胞，哪個過程會先停止？",
    back: "<strong>Active transport</strong> stops, because respiration is inhibited; <strong>diffusion</strong> can continue.<br><strong>主動運輸</strong>停止，因為呼吸被抑制；<strong>擴散</strong>仍可繼續。",
  },
  {
    id: 38,
    subtopic: "主動運輸與吞噬",
    front: "Why are mitochondria abundant in cells that do much active transport?<br>為何進行大量主動運輸的細胞有很多粒線體？",
    back: "Mitochondria make <strong>ATP</strong> by aerobic respiration.<br>粒線體以有氧呼吸製造 <strong>ATP</strong>。",
  },
  {
    id: 39,
    subtopic: "主動運輸與吞噬",
    front: "What are the first two steps of phagocytosis?<br>吞噬作用的首兩步是什麼？",
    back: "The membrane <strong>infolds</strong> to form pseudopodia, then the particle is <strong>engulfed</strong> into a vacuole.<br>細胞膜<strong>內摺</strong>形成偽足，然後把粒子<strong>吞入</strong>液泡。",
  },
  {
    id: 40,
    subtopic: "主動運輸與吞噬",
    front: "After a food vacuole forms, what do lysosomes do?<br>食物液泡形成後，溶酶體做什麼？",
    back: "They fuse and release <strong>enzymes</strong> to digest the particle.<br>它們融合並釋放<strong>酶</strong>來消化粒子。",
  },
  {
    id: 41,
    subtopic: "主動運輸與吞噬",
    front: "Does phagocytosis need energy?<br>吞噬作用需要能量嗎？",
    back: "<strong>Yes.</strong> It needs ATP and a living membrane, like active transport.<br><strong>需要。</strong>它像主動運輸一樣需要 ATP 和活膜。",
  },
  {
    id: 42,
    subtopic: "主動運輸與吞噬",
    front: "When soil nutrient concentration equals the cell, can uptake still occur?<br>土壤養分濃度等於細胞時，還能吸收嗎？",
    back: "<strong>Yes, by active transport</strong>; diffusion has no gradient then.<br><strong>可以，靠主動運輸</strong>；那時擴散沒有梯度。",
  },
];
