const COPY = {
  title: "射擊",
  kicker: "學習重點",
  lead: "選類別和難度。WASD 開車、滑鼠轉炮、點擊開火。空白鍵暫停。Esc 回主頁。",
  home: "主頁",
  trackLearn: "學習重點",
  catAll: "全部",
  pickCat: "類別",
  pickHint: "先選類別和難度，再開始",
  pickSpeed: "難度",
  speedSlow: "簡單",
  speedNormal: "普通",
  speedFast: "困難",
  poolCount: "本題庫",
  poolUnit: "題",
  emptyPool: "此篩選沒有題目。請改選類別。",
  setupNext: "下一步",
  setupBack: "上一步",
  howtoTitle: "怎麼玩",
  howto1: "WASD 開車，滑鼠轉炮。",
  howto2: "點擊開火，打中屬於這手法的作用。",
  howto3: "其他坦克不要打。",
  howto4: "空白鍵暫停。",
  howto5: "Esc 回主頁。",
  howto6: "提示目標只在簡單、普通可開，困難沒有。",
  pauseHint: "空白鍵暫停",
  paused: "已暫停",
  next: "下一題",
  again: "再來一局",
  retryWeak: "再練錯題",
  recapTitle: "本局結果",
  firstHits: "首擊答對",
  misses: "打錯",
  prompt: "出題",
  keys: "WASD 開車、滑鼠轉炮、點擊開火。打中屬於它的作用，避開其他",
  remaining: "還要打中",
  example: "例句",
  leaveTitle: "本局尚未完成，確定回主頁？",
  leaveStay: "留下",
  leaveHome: "回主頁",
  round: "第",
  of: "/",
  clean: "全對",
  keep: "再練這幾題",
  cleared: "本題完成",
  timeUsed: "用時",
  accuracy: "命中率",
  ammo: "彈藥",
  hearts: "生命",
  healLabel: "擊中回血",
  healOff: "關",
  healOn: "開",
  pickTip: "提示目標",
  tipOff: "關",
  tipOn: "開",
  tipLead: "打中黃色方塊五次，揭示一個正確作用。",
  tipReveal: "提示：",
  fullscreen: "全螢幕",
  fullscreenExit: "離開全螢幕",
  outOfHearts: "生命歸零",
};

const TECHNIQUES = [
  {
    id: "shunxu",
    cat: "敘事",
    name: "順敘法",
    hits: ["清楚來龍去脈"],
    decoys: ["親歷其境", "引起共鳴"],
    example: "早上出門，中午到校，傍晚回家。",
  },
  {
    id: "daoxu",
    cat: "敘事",
    name: "倒敘法",
    hits: ["製造懸念"],
    decoys: ["清楚來龍去脈", "親歷其境"],
    example: "先寫公布成績的那一刻，再回想備考的日子。",
  },
  {
    id: "chaxu",
    cat: "敘事",
    name: "插敘法",
    hits: ["補充相關事件"],
    decoys: ["製造懸念", "清楚來龍去脈"],
    example: "寫這次旅行途中，插入去年同遊的一段回憶。",
  },
  {
    id: "first",
    cat: "人稱",
    name: "第一人稱",
    hits: ["親歷其境", "引起共鳴"],
    decoys: ["製造懸念"],
    example: "我走進課室，心裡又喜又怕。",
  },
  {
    id: "second",
    cat: "人稱",
    name: "第二人稱",
    hits: ["拉近距離"],
    decoys: ["視角客觀", "親歷其境"],
    example: "你還記得那天的雨嗎？",
  },
  {
    id: "third",
    cat: "人稱",
    name: "第三人稱",
    hits: ["視角客觀"],
    decoys: ["親歷其境", "拉近距離"],
    example: "他站在窗前，一句話也不說。",
  },
  {
    id: "buyi",
    cat: "寫景",
    name: "步移法",
    hits: ["移步換景"],
    decoys: ["定格同一視點", "隨時間變化"],
    example: "轉過長廊，又見荷塘，再走上小丘。",
  },
  {
    id: "suishi",
    cat: "寫景",
    name: "隨時推移法",
    hits: ["隨時間變化"],
    decoys: ["移步換景", "定格同一視點"],
    example: "春花開了，夏雨來了，秋葉落下。",
  },
  {
    id: "dingdian",
    cat: "寫景",
    name: "定點描寫法",
    hits: ["定格同一視點"],
    decoys: ["移步換景", "五感立體"],
    example: "坐在山頂，只寫眼前這一幅城景。",
  },
  {
    id: "wugan",
    cat: "寫景",
    name: "五感描寫",
    hits: ["視聽嗅味觸"],
    decoys: ["移步換景", "製造懸念"],
    example: "海風帶鹹，浪聲拍岸，沙粒扎腳。",
  },
  {
    id: "zhijie",
    cat: "寫景",
    name: "直接描寫",
    hits: ["正面刻畫景物"],
    decoys: ["側面烘托", "視角客觀"],
    example: "這座山又高又陡，岩石呈鐵灰色。",
  },
  {
    id: "jianjie",
    cat: "寫景",
    name: "間接描寫",
    hits: ["側面烘托"],
    decoys: ["正面刻畫景物", "清楚來龍去脈"],
    example: "路人紛紛拭汗，可見天氣酷熱。",
  },
  {
    id: "dongtai",
    cat: "寫景",
    name: "動態描寫",
    hits: ["景物有生命感"],
    decoys: ["定格畫面", "列出數據"],
    example: "柳枝隨風擺動，溪水不斷奔流。",
  },
  {
    id: "jingtai",
    cat: "寫景",
    name: "靜態描寫",
    hits: ["定格畫面"],
    decoys: ["景物有生命感", "移步換景"],
    example: "古塔矗立湖心，水面平靜如鏡。",
  },
  {
    id: "dingyi",
    cat: "說明",
    name: "下定義",
    hits: ["揭示本質"],
    decoys: ["舉出實例", "列出數據"],
    example: "光合作用是植物把光能轉成化學能的過程。",
  },
  {
    id: "fenlei",
    cat: "說明",
    name: "分類別",
    hits: ["按類劃分"],
    decoys: ["揭示本質", "打比方"],
    example: "文具可分為書寫、修正、繪畫三類。",
  },
  {
    id: "lizi",
    cat: "說明",
    name: "舉例子",
    hits: ["舉出實例"],
    decoys: ["列出數據", "引用資料"],
    example: "可再生能源如風能、太陽能、水力發電。",
  },
  {
    id: "bijiao",
    cat: "說明",
    name: "作比較",
    hits: ["同異對照"],
    decoys: ["揭示本質", "打比方"],
    example: "火車較慢但平穩，飛機較快但票貴。",
  },
  {
    id: "shuzi",
    cat: "說明",
    name: "列數字",
    hits: ["列出數據"],
    decoys: ["舉出實例", "打比方"],
    example: "全班四十二人，達標率百分之九十五。",
  },
  {
    id: "bifang",
    cat: "說明",
    name: "打比方",
    hits: ["以熟喻生"],
    decoys: ["揭示本質", "列出數據"],
    example: "互聯網像一條無形的公路，連接各地。",
  },
  {
    id: "yinyong",
    cat: "說明",
    name: "引資料",
    hits: ["引用資料"],
    decoys: ["舉出實例", "按類劃分"],
    example: "據氣象台報告，本週降雨量超過一百毫米。",
  },
  {
    id: "quanshi",
    cat: "說明",
    name: "作詮釋",
    hits: ["解釋說明"],
    decoys: ["揭示本質", "列出數據"],
    example: "所謂堅持，是每天進步一點，不輕易放棄。",
  },
  {
    id: "biyu",
    cat: "修辭",
    name: "比喻",
    hits: ["化抽象為具體"],
    decoys: ["賦予事物人情", "增強語勢"],
    example: "希望是黑夜裡的一盞燈。",
  },
  {
    id: "niren",
    cat: "修辭",
    name: "擬人",
    hits: ["賦予事物人情"],
    decoys: ["化抽象為具體", "突出特點"],
    example: "小草探出頭來，向春天打招呼。",
  },
  {
    id: "kuazhang",
    cat: "修辭",
    name: "誇張",
    hits: ["突出特點"],
    decoys: ["句式整齊", "引起思考"],
    example: "他的聲音大得能把屋頂掀翻。",
  },
  {
    id: "paibi",
    cat: "修辭",
    name: "排比",
    hits: ["增強語勢"],
    decoys: ["句式整齊", "強調重點"],
    example: "我愛山，愛水，愛這片安靜的土地。",
  },
  {
    id: "duiou",
    cat: "修辭",
    name: "對偶",
    hits: ["句式整齊"],
    decoys: ["增強語勢", "突出差異"],
    example: "青山橫北郭，白水繞東城。",
  },
  {
    id: "fanwen",
    cat: "修辭",
    name: "反問",
    hits: ["加強語氣"],
    decoys: ["引起思考", "強調重點"],
    example: "這樣的機會，難道你要放棄嗎？",
  },
  {
    id: "shewen",
    cat: "修辭",
    name: "設問",
    hits: ["引起思考"],
    decoys: ["加強語氣", "直抒胸臆"],
    example: "什麼才是真正的勇敢？是面對恐懼仍向前走。",
  },
  {
    id: "fanfu",
    cat: "修辭",
    name: "反覆",
    hits: ["強調重點"],
    decoys: ["增強語勢", "加強語氣"],
    example: "加油，加油，加油！我們沒有放棄。",
  },
  {
    id: "jiedai",
    cat: "修辭",
    name: "借代",
    hits: ["突出特徵"],
    decoys: ["化抽象為具體", "突出主體"],
    example: "以「白袍」代醫生，突出職業特徵。",
  },
  {
    id: "duibi",
    cat: "修辭",
    name: "對比",
    hits: ["突出差異"],
    decoys: ["突出主體", "同異對照"],
    example: "一邊是燈火通明，一邊是漆黑小巷。",
  },
  {
    id: "chentuan",
    cat: "修辭",
    name: "襯托",
    hits: ["突出主體"],
    decoys: ["突出差異", "烘托氣氛"],
    example: "滿堂笑聲裡，只有他低頭不語。",
  },
  {
    id: "waimao",
    cat: "描寫",
    name: "外貌描寫",
    hits: ["刻畫外形"],
    decoys: ["展現性格", "揭示內心"],
    example: "她梳着短髮，戴一副圓框眼鏡。",
  },
  {
    id: "yuyan",
    cat: "描寫",
    name: "語言描寫",
    hits: ["展現性格"],
    decoys: ["刻畫外形", "表現行為性格"],
    example: "「我再試一次。」他低聲說。",
  },
  {
    id: "dongzuo",
    cat: "描寫",
    name: "動作描寫",
    hits: ["表現行為性格"],
    decoys: ["揭示內心", "神情傳神"],
    example: "他握緊拳頭，一步步走上講台。",
  },
  {
    id: "xinli",
    cat: "描寫",
    name: "心理描寫",
    hits: ["揭示內心"],
    decoys: ["刻畫外形", "烘托氣氛"],
    example: "我心裡七上八下，生怕答錯。",
  },
  {
    id: "shentai",
    cat: "描寫",
    name: "神態描寫",
    hits: ["神情傳神"],
    decoys: ["刻畫外形", "展現性格"],
    example: "老師微微皺眉，隨即又露出微笑。",
  },
  {
    id: "huanjing",
    cat: "描寫",
    name: "環境描寫",
    hits: ["烘托氣氛"],
    decoys: ["揭示內心", "寓情於景"],
    example: "課室靜得只聽見風扇轉動。",
  },
  {
    id: "zhijie-shuqing",
    cat: "抒情",
    name: "直接抒情",
    hits: ["直抒胸臆"],
    decoys: ["寓情於景", "開篇點題"],
    example: "我真的很想念外婆。",
  },
  {
    id: "jiejing",
    cat: "抒情",
    name: "借景抒情",
    hits: ["寓情於景"],
    decoys: ["直抒胸臆", "烘托氣氛"],
    example: "看着落葉飄下，我心裡也跟着沉了。",
  },
  {
    id: "lili-lunzheng",
    cat: "議論",
    name: "舉例論證",
    hits: ["增強說服力"],
    decoys: ["突出是非", "化深為淺"],
    example: "愛迪生失敗多次仍發明電燈，可見堅持有效。",
  },
  {
    id: "duibi-lunzheng",
    cat: "議論",
    name: "對比論證",
    hits: ["突出是非"],
    decoys: ["增強說服力", "增加可信度"],
    example: "勤奮的人進步，懶惰的人停滯，是非分明。",
  },
  {
    id: "yinyong-lunzheng",
    cat: "議論",
    name: "引用論證",
    hits: ["增加可信度"],
    decoys: ["增強說服力", "化深為淺"],
    example: "古語云「讀萬卷書，行萬里路」，可見實踐重要。",
  },
  {
    id: "biyu-lunzheng",
    cat: "議論",
    name: "比喻論證",
    hits: ["化深為淺"],
    decoys: ["化抽象為具體", "突出是非"],
    example: "知識如梯子，讓我們一步步升高。",
  },
  {
    id: "kaimen",
    cat: "結構",
    name: "開門見山",
    hits: ["開篇點題"],
    decoys: ["結構完整", "先抑後揚"],
    example: "開篇就寫：這次旅行改變了我。",
  },
  {
    id: "shouwei",
    cat: "結構",
    name: "首尾呼應",
    hits: ["結構完整"],
    decoys: ["開篇點題", "埋下線索"],
    example: "開頭寫想家，結尾再回到想家。",
  },
  {
    id: "yuyang",
    cat: "結構",
    name: "欲揚先抑",
    hits: ["先抑後揚"],
    decoys: ["開篇點題", "埋下線索"],
    example: "先寫他平凡，再寫他在關鍵時刻很勇敢。",
  },
  {
    id: "fubi",
    cat: "結構",
    name: "伏筆",
    hits: ["埋下線索"],
    decoys: ["結構完整", "補充相關事件"],
    example: "前文寫鑰匙落在抽屜，後文才揭開秘密。",
  },
];

const HIT_OWNER = {};
TECHNIQUES.forEach(function (tech) {
  tech.hits.forEach(function (hit) {
    HIT_OWNER[hit] = tech.name;
  });
});
