/**
 * Word-equation worksheet database
 * Topics: lime-cycle | acid-rain | metal-extraction | silver-nitrate
 */
window.EQUATIONS_DB = {
  topics: [
    {
      id: "lime-cycle",
      title: "Lime cycle",
      blurb: "Calcium carbonate and the limestone cycle",
    },
    {
      id: "acid-rain",
      title: "Acid rain and limestone",
      blurb: "Carbonic acid and weathering of limestone",
    },
    {
      id: "metal-extraction",
      title: "Extraction of metals from their ores",
      blurb: "Methods and word equations for extracting metals",
    },
    {
      id: "silver-nitrate",
      title: "Silver nitrate test",
      blurb: "Chloride, carbonate and sulphite with AgNO₃ then HNO₃",
    },
  ],

  methods: [
    {
      id: "mechanical",
      label: "Mechanical separation (e.g. panning)",
    },
    {
      id: "heating-alone",
      label: "Heating the metal ore alone",
    },
    {
      id: "heating-carbon",
      label: "Heating the metal ore with carbon",
    },
    {
      id: "electrolysis",
      label: "Electrolysis of molten metal ore",
    },
  ],

  /** Shared word pool for distractors in drag banks */
  wordPool: [
    "Calcium carbonate",
    "Calcium oxide",
    "Calcium hydroxide",
    "Calcium hydroxide solution",
    "Calcium hydrogencarbonate",
    "Calcium chloride",
    "Carbon dioxide",
    "Carbonic acid",
    "Water",
    "Hydrochloric acid",
    "Oxygen",
    "Carbon",
    "Silver",
    "Silver oxide",
    "Mercury",
    "Mercury oxide",
    "Zinc",
    "Zinc oxide",
    "Iron",
    "Iron oxide",
    "Lead",
    "Lead(II) oxide",
    "Copper",
    "Copper oxide",
    "Potassium",
    "Potassium oxide",
    "Sodium",
    "Sodium oxide",
    "Calcium",
    "Magnesium",
    "Magnesium oxide",
    "Aluminium",
    "Aluminium oxide",
    "Gold",
    "Sodium chloride solution",
    "Sodium carbonate solution",
    "Sodium sulphite solution",
    "Silver nitrate solution",
    "Silver nitrate",
    "Silver chloride",
    "Silver carbonate",
    "Silver sulphite",
    "Sodium nitrate",
    "Nitric acid",
    "Sulphur dioxide",
    "No reaction",
  ],

  equations: [
    // —— Lime cycle ——
    {
      id: "lime-1",
      topic: "lime-cycle",
      goal: "Thermal decomposition of calcium carbonate (limestone) to make calcium oxide",
      reactants: ["Calcium carbonate"],
      products: ["Calcium oxide", "Carbon dioxide"],
    },
    {
      id: "lime-2",
      topic: "lime-cycle",
      goal: "Reacting calcium oxide (quicklime) with water to form calcium hydroxide (slaked lime)",
      reactants: ["Calcium oxide", "Water"],
      products: ["Calcium hydroxide"],
    },
    {
      id: "lime-3",
      topic: "lime-cycle",
      goal: "Dissolving solid calcium hydroxide to form calcium hydroxide solution (limewater) — a physical change",
      reactants: ["Calcium hydroxide"],
      products: ["Calcium hydroxide solution"],
    },
    {
      id: "lime-4",
      topic: "lime-cycle",
      goal: "Passing carbon dioxide into limewater to form calcium carbonate (limewater turns milky)",
      reactants: ["Calcium hydroxide", "Carbon dioxide"],
      products: ["Calcium carbonate", "Water"],
    },
    {
      id: "lime-5",
      topic: "lime-cycle",
      goal: "Forming soluble calcium hydrogencarbonate from calcium carbonate, water and carbon dioxide",
      reactants: ["Calcium carbonate", "Water", "Carbon dioxide"],
      products: ["Calcium hydrogencarbonate"],
    },
    {
      id: "lime-6",
      topic: "lime-cycle",
      goal: "Reacting calcium carbonate (limestone) with hydrochloric acid",
      reactants: ["Calcium carbonate", "Hydrochloric acid"],
      products: ["Calcium chloride", "Carbon dioxide", "Water"],
    },

    // —— Acid rain ——
    {
      id: "acid-1",
      topic: "acid-rain",
      goal: "Formation of carbonic acid that makes rainwater slightly acidic",
      reactants: ["Carbon dioxide", "Water"],
      products: ["Carbonic acid"],
    },
    {
      id: "acid-2",
      topic: "acid-rain",
      goal: "Carbonic acid reacting with calcium carbonate in limestone (limestone slowly worn away)",
      reactants: ["Calcium carbonate", "Carbonic acid"],
      products: ["Calcium hydrogencarbonate"],
    },

    // —— Metal extraction ——
    {
      id: "metal-gold",
      topic: "metal-extraction",
      goal: "Extraction of gold from its ore",
      reactants: [],
      products: [],
      noEquation: true,
      note: "Physical change — no new substances are produced (e.g. panning).",
      method: "mechanical",
    },
    {
      id: "metal-silver",
      topic: "metal-extraction",
      goal: "Extraction of silver from silver oxide",
      reactants: ["Silver oxide"],
      products: ["Silver", "Oxygen"],
      method: "heating-alone",
    },
    {
      id: "metal-mercury",
      topic: "metal-extraction",
      goal: "Extraction of mercury from mercury oxide",
      reactants: ["Mercury oxide"],
      products: ["Mercury", "Oxygen"],
      method: "heating-alone",
    },
    {
      id: "metal-zinc",
      topic: "metal-extraction",
      goal: "Extraction of zinc from zinc oxide",
      reactants: ["Zinc oxide", "Carbon"],
      products: ["Zinc", "Carbon dioxide"],
      method: "heating-carbon",
    },
    {
      id: "metal-iron",
      topic: "metal-extraction",
      goal: "Extraction of iron from iron oxide",
      reactants: ["Iron oxide", "Carbon"],
      products: ["Iron", "Carbon dioxide"],
      method: "heating-carbon",
    },
    {
      id: "metal-lead",
      topic: "metal-extraction",
      goal: "Extraction of lead from lead(II) oxide",
      reactants: ["Lead(II) oxide", "Carbon"],
      products: ["Lead", "Carbon dioxide"],
      method: "heating-carbon",
    },
    {
      id: "metal-copper",
      topic: "metal-extraction",
      goal: "Extraction of copper from copper oxide",
      reactants: ["Copper oxide", "Carbon"],
      products: ["Copper", "Carbon dioxide"],
      method: "heating-carbon",
    },
    {
      id: "metal-potassium",
      topic: "metal-extraction",
      goal: "Extraction of potassium from potassium oxide",
      reactants: ["Potassium oxide"],
      products: ["Potassium", "Oxygen"],
      method: "electrolysis",
    },
    {
      id: "metal-sodium",
      topic: "metal-extraction",
      goal: "Extraction of sodium from sodium oxide",
      reactants: ["Sodium oxide"],
      products: ["Sodium", "Oxygen"],
      method: "electrolysis",
    },
    {
      id: "metal-calcium",
      topic: "metal-extraction",
      goal: "Extraction of calcium from calcium oxide",
      reactants: ["Calcium oxide"],
      products: ["Calcium", "Oxygen"],
      method: "electrolysis",
    },
    {
      id: "metal-magnesium",
      topic: "metal-extraction",
      goal: "Extraction of magnesium from magnesium oxide",
      reactants: ["Magnesium oxide"],
      products: ["Magnesium", "Oxygen"],
      method: "electrolysis",
    },
    {
      id: "metal-aluminium",
      topic: "metal-extraction",
      goal: "Extraction of aluminium from aluminium oxide",
      reactants: ["Aluminium oxide"],
      products: ["Aluminium", "Oxygen"],
      method: "electrolysis",
    },

    // —— Silver nitrate test (one question = full two-step sequence) ——
    {
      id: "agno3-nacl",
      topic: "silver-nitrate",
      multiStep: true,
      goal: "Complete the silver nitrate test for sodium chloride solution (add silver nitrate, then nitric acid).",
      steps: [
        {
          title: "Step 1 — Add silver nitrate solution",
          reactants: ["Sodium chloride solution", "Silver nitrate solution"],
          products: ["Silver chloride", "Sodium nitrate"],
          observation: "White precipitate forms",
        },
        {
          title: "Step 2 — Add nitric acid",
          reactants: ["Silver chloride", "Nitric acid"],
          products: ["No reaction"],
          observation: "No observable change",
        },
      ],
    },
    {
      id: "agno3-na2co3",
      topic: "silver-nitrate",
      multiStep: true,
      goal: "Complete the silver nitrate test for sodium carbonate solution (add silver nitrate, then nitric acid).",
      steps: [
        {
          title: "Step 1 — Add silver nitrate solution",
          reactants: ["Sodium carbonate solution", "Silver nitrate solution"],
          products: ["Silver carbonate", "Sodium nitrate"],
          observation: "White precipitate forms",
        },
        {
          title: "Step 2 — Add nitric acid",
          reactants: ["Silver carbonate", "Nitric acid"],
          products: ["Silver nitrate", "Carbon dioxide", "Water"],
          observation: "White precipitate dissolves",
        },
      ],
    },
    {
      id: "agno3-na2so3",
      topic: "silver-nitrate",
      multiStep: true,
      goal: "Complete the silver nitrate test for sodium sulphite solution (add silver nitrate, then nitric acid).",
      steps: [
        {
          title: "Step 1 — Add silver nitrate solution",
          reactants: ["Sodium sulphite solution", "Silver nitrate solution"],
          products: ["Silver sulphite", "Sodium nitrate"],
          observation: "White precipitate forms",
        },
        {
          title: "Step 2 — Add nitric acid",
          reactants: ["Silver sulphite", "Nitric acid"],
          products: ["Silver nitrate", "Sulphur dioxide", "Water"],
          observation: "White precipitate dissolves",
        },
      ],
    },
  ],

  /** Observation options for silver nitrate (and distractors) */
  observationPool: [
    "White precipitate forms",
    "White precipitate dissolves",
    "No observable change",
    "Brown precipitate forms",
    "Yellow precipitate forms",
    "Gas evolved",
  ],
};
