const COPY = {
  title: "打太鼓",
  kicker: "學習重點",
  lead: "看例句，敲鼓上正確的手法。音符從右向左，重合判定圈時敲咚／咔／大。1 或 F 咚，2 或 J 咔，3 或空白鍵大。Esc 回主頁。",
  home: "主頁",
  trackLearn: "學習重點",
  catAll: "全部",
  stageAll: "全部",
  stagePrimary: "小學",
  stageJunior: "初中",
  stageSenior: "高中",
  pickStage: "學段",
  pickCat: "類別",
  pickSpeed: "速度",
  pickHint: "先看例句，再選鼓上的手法。學段和類別決定題目，速度決定快慢。可先複習再演奏。",
  speedPractice: "練習",
  speedStandard: "標準",
  speedExpert: "達人",
  poolCount: "本題庫",
  poolUnit: "題",
  emptyPool: "此篩選沒有題目。請改選學段或類別。",
  study: "先複習",
  howto: "玩法",
  howtoTitle: "怎麼玩",
  howto1: "飛來的音符是米色的，對錯不看紅／藍。請讀例句，再看三面鼓上的手法名。",
  howto2: "咚、咔、大各自寫著一個手法。例句對應哪一種，就在重合判定圈時敲那一面。",
  howto3: "鍵盤：1 或 F 咚 · 2 或 J 咔 · 3 或空白鍵 大。答錯暫停時按空白鍵或 Enter 繼續。Esc 回主頁。",
  howto4: "良、可是答對且時機好；時機差是答對但慢了，仍算概念對。答錯、錯過會暫停並顯示正解與作用。",
  howto5: "通關看概念答對是否達到八成，不是看手速。練習會顯示手法名當提示；標準／達人只出例句。後半段 GOGO 分數加倍。",
  howtoClose: "知道了",
  taikoName: "打太鼓",
  taikoLead: "讀例句，敲鼓上正確的手法。通關看概念答對八成；良、全連、全良是節奏獎勵。",
  start: "開始演奏",
  next: "下一題",
  prev: "上一題",
  again: "再來一局",
  retryWeak: "再練錯題",
  recapTitle: "演奏結果",
  keys: "咚 1／F · 咔 2／J · 大 3／空白鍵　鼓上寫手法名",
  example: "例句",
  hitsLabel: "作用",
  nameHint: "手法提示",
  youPicked: "你打了",
  leaveTitle: "本局尚未完成，確定回主頁？",
  leaveStay: "留下",
  leaveHome: "回主頁",
  round: "第",
  of: "/",
  clean: "概念全對",
  keep: "再練這幾題",
  good: "良",
  ok: "可",
  late: "時機差",
  wrong: "答錯",
  combo: "連段",
  score: "分數",
  soul: "魂",
  clearMark: "通關",
  cleared: "通關",
  failed: "未通關",
  fullCombo: "全連",
  dondaful: "全良",
  don: "咚",
  ka: "咔",
  big: "大",
  go: "咚！",
  missedNote: "錯過",
  ghost: "空打",
  correct: "正解",
  continue: "繼續",
  continueHint: "空白鍵繼續",
  pause: "暫停",
  resume: "繼續",
  pausedTitle: "已暫停",
  mute: "靜音",
  unmute: "音效",
  concept: "概念答對",
  conceptNeed: "需八成",
  conceptShort: "概念答對不足八成",
  maxCombo: "最大連段",
  gauge: "魂槽",
  gogoHint: "後半段，分數加倍",
  studyTitle: "複習",
  studyLead: "先看手法、作用和例句，再開始演奏。",
};

const TECHNIQUES = [
  {
    id: "shunxu",
    cat: "敘事",
    name: "順敘法",
    stage: "both",
    hits: ["清楚來龍去脈"],
    confusable: ["daoxu", "chaxu"],
    example: "早上出門，中午到校，傍晚回家。",
  },
  {
    id: "daoxu",
    cat: "敘事",
    name: "倒敘法",
    stage: "both",
    hits: ["製造懸念"],
    confusable: ["shunxu", "chaxu"],
    example: "先寫公布成績的那一刻，再回想備考的日子。",
  },
  {
    id: "chaxu",
    cat: "敘事",
    name: "插敘法",
    stage: "junior",
    hits: ["補充相關事件"],
    confusable: ["daoxu", "shunxu", "sanxu"],
    example: "寫這次旅行途中，插入去年同遊的一段回憶。",
  },
  {
    id: "sanxu",
    cat: "敘事",
    name: "散敘",
    stage: "senior",
    hits: ["多線組織"],
    confusable: ["shunxu", "chaxu"],
    example: "交替寫出校園、家裏和街市三條線索。",
  },
  {
    id: "liuyao",
    cat: "敘事",
    name: "記敘六要素",
    stage: "primary",
    hits: ["交代完整"],
    confusable: ["shunxu", "daoxu"],
    example: "上星期六在公園，我和媽媽因為尋狗而找到牠。",
  },
  {
    id: "first",
    cat: "人稱",
    name: "第一人稱",
    stage: "junior",
    hits: ["親歷其境", "引起共鳴"],
    confusable: ["second", "third"],
    example: "我走進課室，心裡又喜又怕。",
  },
  {
    id: "second",
    cat: "人稱",
    name: "第二人稱",
    stage: "junior",
    hits: ["拉近距離"],
    confusable: ["first", "third"],
    example: "你還記得那天的雨嗎？",
  },
  {
    id: "third",
    cat: "人稱",
    name: "第三人稱",
    stage: "junior",
    hits: ["視角客觀"],
    confusable: ["first", "second"],
    example: "他站在窗前，一句話也不說。",
  },
  {
    id: "buyi",
    cat: "寫景",
    name: "步移法",
    stage: "both",
    hits: ["移步換景"],
    confusable: ["dingdian", "suishi", "yuanjin"],
    example: "轉過長廊，又見荷塘，再走上小丘。",
  },
  {
    id: "suishi",
    cat: "寫景",
    name: "隨時推移法",
    stage: "junior",
    hits: ["隨時間變化"],
    confusable: ["buyi", "dingdian"],
    example: "春花開了，夏雨來了，秋葉落下。",
  },
  {
    id: "dingdian",
    cat: "寫景",
    name: "定點描寫法",
    stage: "junior",
    hits: ["定格同一視點"],
    confusable: ["buyi", "suishi"],
    example: "坐在山頂，只寫眼前這一幅城景。",
  },
  {
    id: "wugan",
    cat: "寫景",
    name: "五感描寫",
    stage: "both",
    hits: ["視聽嗅味觸"],
    confusable: ["tonggan", "dongtai"],
    example: "海風帶鹹，浪聲拍岸，沙粒扎腳。",
  },
  {
    id: "yuanjin",
    cat: "寫景",
    name: "由遠而近",
    stage: "primary",
    hits: ["觀察有層次"],
    confusable: ["buyi", "dingdian"],
    example: "先寫遠處的山影，再寫近處的花圃。",
  },
  {
    id: "zhijie",
    cat: "寫景",
    name: "直接描寫",
    stage: "both",
    hits: ["正面刻畫景物"],
    confusable: ["jianjie", "dongtai"],
    example: "這座山又高又陡，岩石呈鐵灰色。",
  },
  {
    id: "jianjie",
    cat: "寫景",
    name: "間接描寫",
    stage: "junior",
    hits: ["借他物寫景物"],
    confusable: ["zhijie", "cemian", "huanjing"],
    example: "路人紛紛拭汗，可見天氣酷熱。",
  },
  {
    id: "dongtai",
    cat: "寫景",
    name: "動態描寫",
    stage: "both",
    hits: ["景物有生命感"],
    confusable: ["jingtai", "niren"],
    example: "柳枝隨風擺動，溪水不斷奔流。",
  },
  {
    id: "jingtai",
    cat: "寫景",
    name: "靜態描寫",
    stage: "both",
    hits: ["定格畫面"],
    confusable: ["dongtai", "dingdian"],
    example: "古塔矗立湖心，水面平靜如鏡。",
  },
  {
    id: "dingyi",
    cat: "說明",
    name: "下定義",
    stage: "both",
    hits: ["揭示本質"],
    confusable: ["quanshi", "lizi"],
    example: "光合作用是植物把光能轉成化學能的過程。",
  },
  {
    id: "fenlei",
    cat: "說明",
    name: "分類別",
    stage: "junior",
    hits: ["按類劃分"],
    confusable: ["dingyi", "lizi"],
    example: "文具可分為書寫、修正、繪畫三類。",
  },
  {
    id: "lizi",
    cat: "說明",
    name: "舉例子",
    stage: "both",
    hits: ["舉出實例"],
    confusable: ["shuzi", "yinyong"],
    example: "可再生能源如風能、太陽能、水力發電。",
  },
  {
    id: "bijiao",
    cat: "說明",
    name: "作比較",
    stage: "both",
    hits: ["比較同異來說明"],
    confusable: ["duibi", "bifang"],
    example: "火車較慢但平穩，飛機較快但票貴。",
  },
  {
    id: "shuzi",
    cat: "說明",
    name: "列數字",
    stage: "both",
    hits: ["列出數據"],
    confusable: ["lizi", "dingyi"],
    example: "全班四十二人，達標率百分之九十五。",
  },
  {
    id: "bifang",
    cat: "說明",
    name: "打比方",
    stage: "both",
    hits: ["用比喻來說明"],
    confusable: ["biyu", "biyu-lunzheng"],
    example: "互聯網像一條無形的公路，連接各地。",
  },
  {
    id: "yinyong",
    cat: "說明",
    name: "引資料",
    stage: "junior",
    hits: ["引用資料"],
    confusable: ["lizi", "yinyong-xiuci"],
    example: "據氣象台報告，本週降雨量超過一百毫米。",
  },
  {
    id: "quanshi",
    cat: "說明",
    name: "作詮釋",
    stage: "junior",
    hits: ["解釋說明"],
    confusable: ["dingyi", "lizi"],
    example: "所謂堅持，是每天進步一點，不輕易放棄。",
  },
  {
    id: "biyu",
    cat: "修辭",
    name: "比喻",
    stage: "both",
    hits: ["化抽象為具體"],
    confusable: ["niren", "kuazhang", "jiedai", "bifang"],
    example: "希望是黑夜裡的一盞燈。",
  },
  {
    id: "niren",
    cat: "修辭",
    name: "擬人",
    stage: "both",
    hits: ["賦予事物人情"],
    confusable: ["biyu", "tonggan"],
    example: "小草探出頭來，向春天打招呼。",
  },
  {
    id: "kuazhang",
    cat: "修辭",
    name: "誇張／誇飾",
    stage: "both",
    hits: ["言過其實"],
    confusable: ["biyu", "jiedai"],
    example: "他的聲音大得能把屋頂掀翻。",
  },
  {
    id: "paibi",
    cat: "修辭",
    name: "排比",
    stage: "both",
    hits: ["連用句式加強"],
    confusable: ["duiou", "fanfu", "cengdi"],
    example: "我愛山，愛水，愛這片安靜的土地。",
  },
  {
    id: "duiou",
    cat: "修辭",
    name: "對偶",
    stage: "junior",
    hits: ["兩句整齊相對"],
    confusable: ["paibi", "dingzhen"],
    example: "青山橫北郭，白水繞東城。",
  },
  {
    id: "fanwen",
    cat: "修辭",
    name: "反問",
    stage: "both",
    hits: ["以問加強肯定"],
    confusable: ["shewen", "fanfu"],
    example: "這樣的機會，難道你要放棄嗎？",
  },
  {
    id: "shewen",
    cat: "修辭",
    name: "設問",
    stage: "both",
    hits: ["自問自答引導"],
    confusable: ["fanwen", "hugao"],
    example: "什麼才是真正的勇敢？是面對恐懼仍向前走。",
  },
  {
    id: "fanfu",
    cat: "修辭",
    name: "反覆",
    stage: "both",
    hits: ["重複用詞強調"],
    confusable: ["paibi", "fanwen"],
    example: "加油，加油，加油！我們沒有放棄。",
  },
  {
    id: "diezi",
    cat: "修辭",
    name: "疊字",
    stage: "both",
    hits: ["增添音律美"],
    confusable: ["fanfu", "paibi"],
    example: "風兒輕輕吹過，葉子沙沙作響。",
  },
  {
    id: "yinyong-xiuci",
    cat: "修辭",
    name: "引用",
    stage: "both",
    hits: ["增強文采"],
    confusable: ["yinyong", "yinyong-lunzheng"],
    example: "正如古語所說：「有志者事竟成。」",
  },
  {
    id: "cengdi",
    cat: "修辭",
    name: "層遞",
    stage: "senior",
    hits: ["層層加深"],
    confusable: ["paibi", "dingzhen"],
    example: "他會寫，會改，更會把文章寫到讓人記住。",
  },
  {
    id: "dingzhen",
    cat: "修辭",
    name: "頂真",
    stage: "senior",
    hits: ["上下銜接"],
    confusable: ["cengdi", "chengshang"],
    example: "園中有亭，亭邊有柳，柳下有人。",
  },
  {
    id: "fanyu",
    cat: "修辭",
    name: "反語",
    stage: "senior",
    hits: ["諷刺幽默"],
    confusable: ["fanwen", "shewen"],
    example: "你可真「勤快」，作業都拖到深夜。",
  },
  {
    id: "tonggan",
    cat: "修辭",
    name: "通感",
    stage: "senior",
    hits: ["感官互相溝通"],
    confusable: ["wugan", "biyu"],
    example: "這歌聲甜得像蜜。",
  },
  {
    id: "hugao",
    cat: "修辭",
    name: "呼告",
    stage: "senior",
    hits: ["直接呼喚"],
    confusable: ["shewen", "zhijie-shuqing"],
    example: "媽媽，你聽見我在心裏喊你嗎？",
  },
  {
    id: "jiedai",
    cat: "修辭",
    name: "借代",
    stage: "senior",
    hits: ["借相關代本體"],
    confusable: ["biyu", "kuazhang"],
    example: "以「白袍」代醫生，突出職業特徵。",
  },
  {
    id: "duibi",
    cat: "修辭",
    name: "對比",
    stage: "junior",
    hits: ["兩相對照見差"],
    confusable: ["chentuan", "bijiao"],
    example: "一邊是燈火通明，一邊是漆黑小巷。",
  },
  {
    id: "chentuan",
    cat: "修辭",
    name: "襯托",
    stage: "senior",
    hits: ["用賓襯主"],
    confusable: ["duibi", "huanjing"],
    example: "滿堂笑聲裡，只有他低頭不語。",
  },
  {
    id: "waimao",
    cat: "描寫",
    name: "外貌描寫",
    stage: "both",
    hits: ["刻畫外形"],
    confusable: ["yuyan", "dongzuo", "baimiao"],
    example: "她梳着短髮，戴一副圓框眼鏡。",
  },
  {
    id: "yuyan",
    cat: "描寫",
    name: "語言描寫",
    stage: "both",
    hits: ["用對話見性格"],
    confusable: ["dongzuo", "shentai"],
    example: "「我再試一次。」他低聲說。",
  },
  {
    id: "dongzuo",
    cat: "描寫",
    name: "動作描寫",
    stage: "both",
    hits: ["用動作見性格"],
    confusable: ["yuyan", "xinli"],
    example: "他握緊拳頭，一步步走上講台。",
  },
  {
    id: "xinli",
    cat: "描寫",
    name: "心理描寫",
    stage: "junior",
    hits: ["揭示內心"],
    confusable: ["huanjing", "shentai"],
    example: "我心裡七上八下，生怕答錯。",
  },
  {
    id: "shentai",
    cat: "描寫",
    name: "神態描寫",
    stage: "both",
    hits: ["神情傳神"],
    confusable: ["waimao", "xinli"],
    example: "老師微微皺眉，隨即又露出微笑。",
  },
  {
    id: "huanjing",
    cat: "描寫",
    name: "環境描寫",
    stage: "junior",
    hits: ["以環境襯心情"],
    confusable: ["xinli", "jiejing", "cemian"],
    example: "課室靜得只聽見風扇轉動。",
  },
  {
    id: "cemian",
    cat: "描寫",
    name: "側面描寫",
    stage: "senior",
    hits: ["借旁人反應寫人"],
    confusable: ["waimao", "jianjie", "chentuan"],
    example: "同學都靜下來，可見班主任一進門就很有威嚴。",
  },
  {
    id: "baimiao",
    cat: "描寫",
    name: "白描",
    stage: "senior",
    hits: ["簡筆勾勒"],
    confusable: ["waimao", "shentai"],
    example: "他穿一件舊校服，書包斜挎在肩上。",
  },
  {
    id: "zhijie-shuqing",
    cat: "抒情",
    name: "直接抒情",
    stage: "both",
    hits: ["直抒胸臆"],
    confusable: ["jiejing", "jieshi-shuqing"],
    example: "我真的很想念外婆。",
  },
  {
    id: "jiejing",
    cat: "抒情",
    name: "借景抒情",
    stage: "senior",
    hits: ["寓情於景"],
    confusable: ["zhijie-shuqing", "tuowu", "huanjing"],
    example: "看着落葉飄下，我心裡也跟着沉了。",
  },
  {
    id: "jieshi-shuqing",
    cat: "抒情",
    name: "借事抒情",
    stage: "senior",
    hits: ["借事寄情"],
    confusable: ["jiejing", "zhijie-shuqing"],
    example: "寫出送行那一夜，把不捨藏在小事裏。",
  },
  {
    id: "tuowu",
    cat: "抒情",
    name: "托物言志",
    stage: "senior",
    hits: ["以物明志"],
    confusable: ["jiejing", "zhijie-shuqing"],
    example: "寫勁松立在風中，表明自己不肯低頭。",
  },
  {
    id: "lili-lunzheng",
    cat: "議論",
    name: "舉例論證",
    stage: "junior",
    hits: ["舉事例證明"],
    confusable: ["duibi-lunzheng", "yinyong-lunzheng"],
    example: "愛迪生失敗多次仍發明電燈，可見堅持有效。",
  },
  {
    id: "duibi-lunzheng",
    cat: "議論",
    name: "對比論證",
    stage: "junior",
    hits: ["正反對照說理"],
    confusable: ["lili-lunzheng", "duibi"],
    example: "勤奮的人進步，懶惰的人停滯，是非分明。",
  },
  {
    id: "yinyong-lunzheng",
    cat: "議論",
    name: "引用論證",
    stage: "junior",
    hits: ["引言論據取信"],
    confusable: ["lili-lunzheng", "yinyong-xiuci"],
    example: "古語云「讀萬卷書，行萬里路」，可見實踐重要。",
  },
  {
    id: "biyu-lunzheng",
    cat: "議論",
    name: "比喻論證",
    stage: "senior",
    hits: ["用比喻來說理"],
    confusable: ["biyu", "bifang", "leibi-lunzheng"],
    example: "知識如梯子，讓我們一步步升高。",
  },
  {
    id: "leibi-lunzheng",
    cat: "議論",
    name: "類比論證",
    stage: "senior",
    hits: ["以彼喻此"],
    confusable: ["biyu-lunzheng", "bijiao"],
    example: "學游泳要下水，學寫作也要多動筆。",
  },
  {
    id: "kaimen",
    cat: "結構",
    name: "開門見山",
    stage: "both",
    hits: ["開篇點題"],
    confusable: ["zuzhang", "shouwei"],
    example: "開篇就寫：這次旅行改變了我。",
  },
  {
    id: "shouwei",
    cat: "結構",
    name: "首尾呼應",
    stage: "both",
    hits: ["結構完整"],
    confusable: ["kaimen", "zuzhang"],
    example: "開頭寫想家，結尾再回到想家。",
  },
  {
    id: "zongfenzong",
    cat: "結構",
    name: "總分總",
    stage: "primary",
    hits: ["綱目清楚"],
    confusable: ["kaimen", "shouwei"],
    example: "先總說校園很美，再分寫花圃和操場，最後再總結。",
  },
  {
    id: "xiangluo",
    cat: "結構",
    name: "詳寫略寫",
    stage: "both",
    hits: ["安排詳略"],
    confusable: ["fubi", "chengshang"],
    example: "比賽高潮詳寫，等候進場只略提一句。",
  },
  {
    id: "chengshang",
    cat: "結構",
    name: "承上啟下",
    stage: "both",
    hits: ["銜接段落"],
    confusable: ["dingzhen", "shouwei"],
    example: "寫完課室，用一句「走出門外，操場更熱鬧」接到下段。",
  },
  {
    id: "yuyang",
    cat: "結構",
    name: "欲揚先抑",
    stage: "senior",
    hits: ["先抑後揚"],
    confusable: ["kaimen", "zuzhang"],
    example: "先寫他平凡，再寫他在關鍵時刻很勇敢。",
  },
  {
    id: "fubi",
    cat: "結構",
    name: "伏筆",
    stage: "senior",
    hits: ["埋下線索"],
    confusable: ["chaxu", "xiangluo"],
    example: "前文寫鑰匙落在抽屜，後文才揭開秘密。",
  },
  {
    id: "zuzhang",
    cat: "結構",
    name: "卒章顯志",
    stage: "senior",
    hits: ["篇末點旨"],
    confusable: ["kaimen", "shouwei"],
    example: "到最後一句才點出：原來家才是最暖的地方。",
  },
];
