const COPY = {
  title: "打太鼓",
  kicker: "學習重點",
  lead: "左邊金色鼓是手法，右邊三面鼓選作用。可選小學或中學學段。按 1 2 3。Esc 回主頁。",
  home: "主頁",
  trackLearn: "學習重點",
  catAll: "全部",
  stageAll: "全部",
  stagePrimary: "小學",
  stageSecondary: "中學",
  pickStage: "學段",
  pickCat: "類別",
  pickHint: "先選學段和類別，再開始",
  taikoName: "打太鼓",
  taikoLead: "配對手法和作用／好處。左邊金色鼓是出題，右邊鼓選正確的作用。",
  start: "開始",
  next: "下一題",
  again: "再來一局",
  retryWeak: "再練錯題",
  recapTitle: "本局結果",
  firstHits: "首擊答對",
  misses: "打錯",
  prompt: "出題",
  keys: "選正確的作用 · 按 1 2 3",
  example: "例句",
  youPicked: "你選了",
  leaveTitle: "本局尚未完成，確定回主頁？",
  leaveStay: "留下",
  leaveHome: "回主頁",
  round: "第",
  of: "/",
  clean: "全對",
  keep: "再練這幾題",
};

const TECHNIQUES = [
  {
    id: "shunxu",
    cat: "敘事",
    name: "順敘法",
    stage: "both",
    hits: ["清楚來龍去脈"],
    decoys: ["親歷其境", "引起共鳴"],
    example: "早上出門，中午到校，傍晚回家。",
  },
  {
    id: "daoxu",
    cat: "敘事",
    name: "倒敘法",
    stage: "both",
    hits: ["製造懸念"],
    decoys: ["清楚來龍去脈", "親歷其境"],
    example: "先寫公布成績的那一刻，再回想備考的日子。",
  },
  {
    id: "chaxu",
    cat: "敘事",
    name: "插敘法",
    stage: "secondary",
    hits: ["補充相關事件"],
    decoys: ["製造懸念", "清楚來龍去脈"],
    example: "寫這次旅行途中，插入去年同遊的一段回憶。",
  },
  {
    id: "sanxu",
    cat: "敘事",
    name: "散敘",
    stage: "secondary",
    hits: ["多線組織"],
    decoys: ["清楚來龍去脈", "製造懸念"],
    example: "交替寫出校園、家裏和街市三條線索。",
  },
  {
    id: "liuyao",
    cat: "敘事",
    name: "記敘六要素",
    stage: "primary",
    hits: ["交代完整"],
    decoys: ["製造懸念", "補充相關事件"],
    example: "上星期六在公園，我和媽媽因為尋狗而找到牠。",
  },
  {
    id: "first",
    cat: "人稱",
    name: "第一人稱",
    stage: "secondary",
    hits: ["親歷其境", "引起共鳴"],
    decoys: ["製造懸念"],
    example: "我走進課室，心裡又喜又怕。",
  },
  {
    id: "second",
    cat: "人稱",
    name: "第二人稱",
    stage: "secondary",
    hits: ["拉近距離"],
    decoys: ["視角客觀", "親歷其境"],
    example: "你還記得那天的雨嗎？",
  },
  {
    id: "third",
    cat: "人稱",
    name: "第三人稱",
    stage: "secondary",
    hits: ["視角客觀"],
    decoys: ["親歷其境", "拉近距離"],
    example: "他站在窗前，一句話也不說。",
  },
  {
    id: "buyi",
    cat: "寫景",
    name: "步移法",
    stage: "both",
    hits: ["移步換景"],
    decoys: ["定格同一視點", "隨時間變化"],
    example: "轉過長廊，又見荷塘，再走上小丘。",
  },
  {
    id: "suishi",
    cat: "寫景",
    name: "隨時推移法",
    stage: "secondary",
    hits: ["隨時間變化"],
    decoys: ["移步換景", "定格同一視點"],
    example: "春花開了，夏雨來了，秋葉落下。",
  },
  {
    id: "dingdian",
    cat: "寫景",
    name: "定點描寫法",
    stage: "secondary",
    hits: ["定格同一視點"],
    decoys: ["移步換景", "五感立體"],
    example: "坐在山頂，只寫眼前這一幅城景。",
  },
  {
    id: "wugan",
    cat: "寫景",
    name: "五感描寫",
    stage: "both",
    hits: ["視聽嗅味觸"],
    decoys: ["移步換景", "製造懸念"],
    example: "海風帶鹹，浪聲拍岸，沙粒扎腳。",
  },
  {
    id: "yuanjin",
    cat: "寫景",
    name: "由遠而近",
    stage: "primary",
    hits: ["觀察有層次"],
    decoys: ["移步換景", "定格同一視點"],
    example: "先寫遠處的山影，再寫近處的花圃。",
  },
  {
    id: "zhijie",
    cat: "寫景",
    name: "直接描寫",
    stage: "both",
    hits: ["正面刻畫景物"],
    decoys: ["側面烘托", "視角客觀"],
    example: "這座山又高又陡，岩石呈鐵灰色。",
  },
  {
    id: "jianjie",
    cat: "寫景",
    name: "間接描寫",
    stage: "secondary",
    hits: ["側面烘托"],
    decoys: ["正面刻畫景物", "清楚來龍去脈"],
    example: "路人紛紛拭汗，可見天氣酷熱。",
  },
  {
    id: "dongtai",
    cat: "寫景",
    name: "動態描寫",
    stage: "both",
    hits: ["景物有生命感"],
    decoys: ["定格畫面", "列出數據"],
    example: "柳枝隨風擺動，溪水不斷奔流。",
  },
  {
    id: "jingtai",
    cat: "寫景",
    name: "靜態描寫",
    stage: "both",
    hits: ["定格畫面"],
    decoys: ["景物有生命感", "移步換景"],
    example: "古塔矗立湖心，水面平靜如鏡。",
  },
  {
    id: "dingyi",
    cat: "說明",
    name: "下定義",
    stage: "both",
    hits: ["揭示本質"],
    decoys: ["舉出實例", "列出數據"],
    example: "光合作用是植物把光能轉成化學能的過程。",
  },
  {
    id: "fenlei",
    cat: "說明",
    name: "分類別",
    stage: "secondary",
    hits: ["按類劃分"],
    decoys: ["揭示本質", "打比方"],
    example: "文具可分為書寫、修正、繪畫三類。",
  },
  {
    id: "lizi",
    cat: "說明",
    name: "舉例子",
    stage: "both",
    hits: ["舉出實例"],
    decoys: ["列出數據", "引用資料"],
    example: "可再生能源如風能、太陽能、水力發電。",
  },
  {
    id: "bijiao",
    cat: "說明",
    name: "作比較",
    stage: "both",
    hits: ["同異對照"],
    decoys: ["揭示本質", "打比方"],
    example: "火車較慢但平穩，飛機較快但票貴。",
  },
  {
    id: "shuzi",
    cat: "說明",
    name: "列數字",
    stage: "both",
    hits: ["列出數據"],
    decoys: ["舉出實例", "打比方"],
    example: "全班四十二人，達標率百分之九十五。",
  },
  {
    id: "bifang",
    cat: "說明",
    name: "打比方",
    stage: "both",
    hits: ["以熟喻生"],
    decoys: ["揭示本質", "列出數據"],
    example: "互聯網像一條無形的公路，連接各地。",
  },
  {
    id: "yinyong",
    cat: "說明",
    name: "引資料",
    stage: "secondary",
    hits: ["引用資料"],
    decoys: ["舉出實例", "按類劃分"],
    example: "據氣象台報告，本週降雨量超過一百毫米。",
  },
  {
    id: "quanshi",
    cat: "說明",
    name: "作詮釋",
    stage: "secondary",
    hits: ["解釋說明"],
    decoys: ["揭示本質", "列出數據"],
    example: "所謂堅持，是每天進步一點，不輕易放棄。",
  },
  {
    id: "biyu",
    cat: "修辭",
    name: "比喻",
    stage: "both",
    hits: ["化抽象為具體"],
    decoys: ["賦予事物人情", "增強語勢"],
    example: "希望是黑夜裡的一盞燈。",
  },
  {
    id: "niren",
    cat: "修辭",
    name: "擬人",
    stage: "both",
    hits: ["賦予事物人情"],
    decoys: ["化抽象為具體", "突出特點"],
    example: "小草探出頭來，向春天打招呼。",
  },
  {
    id: "kuazhang",
    cat: "修辭",
    name: "誇張／誇飾",
    stage: "both",
    hits: ["突出特點"],
    decoys: ["句式整齊", "引起思考"],
    example: "他的聲音大得能把屋頂掀翻。",
  },
  {
    id: "paibi",
    cat: "修辭",
    name: "排比",
    stage: "both",
    hits: ["增強語勢"],
    decoys: ["句式整齊", "強調重點"],
    example: "我愛山，愛水，愛這片安靜的土地。",
  },
  {
    id: "duiou",
    cat: "修辭",
    name: "對偶",
    stage: "secondary",
    hits: ["句式整齊"],
    decoys: ["增強語勢", "突出差異"],
    example: "青山橫北郭，白水繞東城。",
  },
  {
    id: "fanwen",
    cat: "修辭",
    name: "反問",
    stage: "both",
    hits: ["加強語氣"],
    decoys: ["引起思考", "強調重點"],
    example: "這樣的機會，難道你要放棄嗎？",
  },
  {
    id: "shewen",
    cat: "修辭",
    name: "設問",
    stage: "both",
    hits: ["引起思考"],
    decoys: ["加強語氣", "直抒胸臆"],
    example: "什麼才是真正的勇敢？是面對恐懼仍向前走。",
  },
  {
    id: "fanfu",
    cat: "修辭",
    name: "反覆",
    stage: "both",
    hits: ["強調重點"],
    decoys: ["增強語勢", "加強語氣"],
    example: "加油，加油，加油！我們沒有放棄。",
  },
  {
    id: "diezi",
    cat: "修辭",
    name: "疊字",
    stage: "both",
    hits: ["增添音律美"],
    decoys: ["增強語勢", "強調重點"],
    example: "風兒輕輕吹過，葉子沙沙作響。",
  },
  {
    id: "yinyong-xiuci",
    cat: "修辭",
    name: "引用",
    stage: "both",
    hits: ["增強文采"],
    decoys: ["化抽象為具體", "增添音律美"],
    example: "正如古語所說：「有志者事竟成。」",
  },
  {
    id: "cengdi",
    cat: "修辭",
    name: "層遞",
    stage: "secondary",
    hits: ["層層加深"],
    decoys: ["增強語勢", "句式整齊"],
    example: "他會寫，會改，更會把文章寫到讓人記住。",
  },
  {
    id: "dingzhen",
    cat: "修辭",
    name: "頂真",
    stage: "secondary",
    hits: ["上下銜接"],
    decoys: ["增添音律美", "層層加深"],
    example: "園中有亭，亭邊有柳，柳下有人。",
  },
  {
    id: "fanyu",
    cat: "修辭",
    name: "反語",
    stage: "secondary",
    hits: ["諷刺幽默"],
    decoys: ["加強語氣", "引起思考"],
    example: "你可真「勤快」，作業都拖到深夜。",
  },
  {
    id: "tonggan",
    cat: "修辭",
    name: "通感",
    stage: "secondary",
    hits: ["打通感官"],
    decoys: ["視聽嗅味觸", "化抽象為具體"],
    example: "這歌聲甜得像蜜。",
  },
  {
    id: "hugao",
    cat: "修辭",
    name: "呼告",
    stage: "secondary",
    hits: ["直接呼喚"],
    decoys: ["直抒胸臆", "引起思考"],
    example: "媽媽，你聽見我在心裏喊你嗎？",
  },
  {
    id: "jiedai",
    cat: "修辭",
    name: "借代",
    stage: "secondary",
    hits: ["突出特徵"],
    decoys: ["化抽象為具體", "突出主體"],
    example: "以「白袍」代醫生，突出職業特徵。",
  },
  {
    id: "duibi",
    cat: "修辭",
    name: "對比",
    stage: "secondary",
    hits: ["突出差異"],
    decoys: ["突出主體", "同異對照"],
    example: "一邊是燈火通明，一邊是漆黑小巷。",
  },
  {
    id: "chentuan",
    cat: "修辭",
    name: "襯托",
    stage: "secondary",
    hits: ["突出主體"],
    decoys: ["突出差異", "烘托氣氛"],
    example: "滿堂笑聲裡，只有他低頭不語。",
  },
  {
    id: "waimao",
    cat: "描寫",
    name: "外貌描寫",
    stage: "both",
    hits: ["刻畫外形"],
    decoys: ["展現性格", "揭示內心"],
    example: "她梳着短髮，戴一副圓框眼鏡。",
  },
  {
    id: "yuyan",
    cat: "描寫",
    name: "語言描寫",
    stage: "both",
    hits: ["展現性格"],
    decoys: ["刻畫外形", "表現行為性格"],
    example: "「我再試一次。」他低聲說。",
  },
  {
    id: "dongzuo",
    cat: "描寫",
    name: "動作描寫",
    stage: "both",
    hits: ["表現行為性格"],
    decoys: ["揭示內心", "神情傳神"],
    example: "他握緊拳頭，一步步走上講台。",
  },
  {
    id: "xinli",
    cat: "描寫",
    name: "心理描寫",
    stage: "secondary",
    hits: ["揭示內心"],
    decoys: ["刻畫外形", "烘托氣氛"],
    example: "我心裡七上八下，生怕答錯。",
  },
  {
    id: "shentai",
    cat: "描寫",
    name: "神態描寫",
    stage: "both",
    hits: ["神情傳神"],
    decoys: ["刻畫外形", "展現性格"],
    example: "老師微微皺眉，隨即又露出微笑。",
  },
  {
    id: "huanjing",
    cat: "描寫",
    name: "環境描寫",
    stage: "secondary",
    hits: ["烘托氣氛"],
    decoys: ["揭示內心", "寓情於景"],
    example: "課室靜得只聽見風扇轉動。",
  },
  {
    id: "cemian",
    cat: "描寫",
    name: "側面描寫",
    stage: "secondary",
    hits: ["從旁顯出人物"],
    decoys: ["刻畫外形", "揭示內心"],
    example: "同學都靜下來，可見班主任一進門就很有威嚴。",
  },
  {
    id: "baimiao",
    cat: "描寫",
    name: "白描",
    stage: "secondary",
    hits: ["簡筆勾勒"],
    decoys: ["刻畫外形", "神情傳神"],
    example: "他穿一件舊校服，書包斜挎在肩上。",
  },
  {
    id: "zhijie-shuqing",
    cat: "抒情",
    name: "直接抒情",
    stage: "both",
    hits: ["直抒胸臆"],
    decoys: ["寓情於景", "開篇點題"],
    example: "我真的很想念外婆。",
  },
  {
    id: "jiejing",
    cat: "抒情",
    name: "借景抒情",
    stage: "secondary",
    hits: ["寓情於景"],
    decoys: ["直抒胸臆", "烘托氣氛"],
    example: "看着落葉飄下，我心裡也跟着沉了。",
  },
  {
    id: "jieshi-shuqing",
    cat: "抒情",
    name: "借事抒情",
    stage: "secondary",
    hits: ["借事寄情"],
    decoys: ["寓情於景", "直抒胸臆"],
    example: "寫出送行那一夜，把不捨藏在小事裏。",
  },
  {
    id: "tuowu",
    cat: "抒情",
    name: "托物言志",
    stage: "secondary",
    hits: ["以物明志"],
    decoys: ["寓情於景", "直抒胸臆"],
    example: "寫勁松立在風中，表明自己不肯低頭。",
  },
  {
    id: "lili-lunzheng",
    cat: "議論",
    name: "舉例論證",
    stage: "secondary",
    hits: ["增強說服力"],
    decoys: ["突出是非", "化深為淺"],
    example: "愛迪生失敗多次仍發明電燈，可見堅持有效。",
  },
  {
    id: "duibi-lunzheng",
    cat: "議論",
    name: "對比論證",
    stage: "secondary",
    hits: ["突出是非"],
    decoys: ["增強說服力", "增加可信度"],
    example: "勤奮的人進步，懶惰的人停滯，是非分明。",
  },
  {
    id: "yinyong-lunzheng",
    cat: "議論",
    name: "引用論證",
    stage: "secondary",
    hits: ["增加可信度"],
    decoys: ["增強說服力", "化深為淺"],
    example: "古語云「讀萬卷書，行萬里路」，可見實踐重要。",
  },
  {
    id: "biyu-lunzheng",
    cat: "議論",
    name: "比喻論證",
    stage: "secondary",
    hits: ["化深為淺"],
    decoys: ["化抽象為具體", "突出是非"],
    example: "知識如梯子，讓我們一步步升高。",
  },
  {
    id: "leibi-lunzheng",
    cat: "議論",
    name: "類比論證",
    stage: "secondary",
    hits: ["以彼喻此"],
    decoys: ["增強說服力", "化深為淺"],
    example: "學游泳要下水，學寫作也要多動筆。",
  },
  {
    id: "kaimen",
    cat: "結構",
    name: "開門見山",
    stage: "both",
    hits: ["開篇點題"],
    decoys: ["結構完整", "先抑後揚"],
    example: "開篇就寫：這次旅行改變了我。",
  },
  {
    id: "shouwei",
    cat: "結構",
    name: "首尾呼應",
    stage: "both",
    hits: ["結構完整"],
    decoys: ["開篇點題", "埋下線索"],
    example: "開頭寫想家，結尾再回到想家。",
  },
  {
    id: "zongfenzong",
    cat: "結構",
    name: "總分總",
    stage: "primary",
    hits: ["綱目清楚"],
    decoys: ["開篇點題", "結構完整"],
    example: "先總說校園很美，再分寫花圃和操場，最後再總結。",
  },
  {
    id: "xiangluo",
    cat: "結構",
    name: "詳寫略寫",
    stage: "both",
    hits: ["安排詳略"],
    decoys: ["埋下線索", "銜接段落"],
    example: "比賽高潮詳寫，等候進場只略提一句。",
  },
  {
    id: "chengshang",
    cat: "結構",
    name: "承上啟下",
    stage: "both",
    hits: ["銜接段落"],
    decoys: ["結構完整", "開篇點題"],
    example: "寫完課室，用一句「走出門外，操場更熱鬧」接到下段。",
  },
  {
    id: "yuyang",
    cat: "結構",
    name: "欲揚先抑",
    stage: "secondary",
    hits: ["先抑後揚"],
    decoys: ["開篇點題", "埋下線索"],
    example: "先寫他平凡，再寫他在關鍵時刻很勇敢。",
  },
  {
    id: "fubi",
    cat: "結構",
    name: "伏筆",
    stage: "secondary",
    hits: ["埋下線索"],
    decoys: ["結構完整", "補充相關事件"],
    example: "前文寫鑰匙落在抽屜，後文才揭開秘密。",
  },
  {
    id: "zuzhang",
    cat: "結構",
    name: "卒章顯志",
    stage: "secondary",
    hits: ["篇末點旨"],
    decoys: ["開篇點題", "先抑後揚"],
    example: "到最後一句才點出：原來家才是最暖的地方。",
  },
];

const HIT_OWNER = {};
TECHNIQUES.forEach(function (tech) {
  tech.hits.forEach(function (hit) {
    HIT_OWNER[hit] = tech.name;
  });
});
