const COPY = {
  title: "打太鼓",
  kicker: "學習重點",
  lead: "看例句，只打正解的 1／2／3。其他數字用空白鍵或略過。點對正解才顯示手法名。Esc 回主頁。",
  home: "主頁",
  trackLearn: "學習重點",
  catAll: "全部",
  stageAll: "全部",
  stagePrimary: "小學",
  stageJunior: "初中",
  stageSenior: "高中",
  pickStage: "學段",
  pickCat: "類別",
  pickSpeed: "速度",
  pickHint: "先看例句，只打正解數字；其餘用空白鍵或略過。學段和類別決定題目，速度決定快慢。可先複習再演奏。",
  speedPractice: "練習",
  speedStandard: "標準",
  speedExpert: "達人",
  poolCount: "本題庫",
  poolUnit: "題",
  emptyPool: "此篩選沒有題目。請改選學段或類別。",
  study: "先複習",
  setupNext: "下一步",
  setupBack: "上一步",
  howto: "玩法",
  howtoTitle: "怎麼玩",
  howto1: "飛來的音符是米色的，上面寫 1／2／3。對錯不看顏色。請讀例句，再看三個鍵上的手法名。只打正解數字。",
  howto2: "每題開始前有兩秒看例句。音到判定圈時：正解數字要打；其餘用空白鍵或「略過」。點對正解數字，才顯示手法名。練習每題 10 音，標準 20 音，達人 30 音。答錯只閃一下，歌不會停。",
  howto3: "鍵盤：1 或 C · 2 或 V／B · 3 或 N。略過用空白鍵。打完一題才暫停，看對／錯／命中率和作用。解說時空白鍵繼續。Esc 回主頁。",
  howto4: "良、可是答對且時機好；時機差是答對但慢了，仍算對。錯過也算錯。通關看整局概念八成。",
  howto5: "通關看概念答對是否達到八成，不是看手速。後半段 GOGO 分數加倍。",
  howtoClose: "知道了",
  taikoName: "打太鼓",
  taikoLead: "讀例句，敲鼓上正確的手法。通關看概念答對八成；良、全連、全良是節奏獎勵。",
  start: "開始演奏",
  next: "下一題",
  prev: "上一題",
  again: "再來一局",
  retryWeak: "再練錯題",
  recapTitle: "演奏結果",
  keys: "1／C · 2／V／B · 3／N　只打正解　其餘略過／空白鍵",
  skip: "略過",
  skipKey: "空白鍵",
  letterA: "1",
  letterB: "2",
  letterC: "3",
  example: "例句",
  hitsLabel: "作用",
  youPicked: "你打了",
  leaveTitle: "本局尚未完成，確定回主頁？",
  leaveStay: "留下",
  leaveHome: "回主頁",
  round: "第",
  of: "/",
  clean: "概念全對",
  keep: "再練這幾題",
  good: "良",
  ok: "可",
  late: "時機差",
  wrong: "答錯",
  combo: "連段",
  score: "分數",
  soul: "魂",
  clearMark: "通關",
  cleared: "通關",
  failed: "未通關",
  fullCombo: "全連",
  dondaful: "全良",
  don: "咚",
  ka: "咔",
  big: "大",
  go: "咚！",
  countStart: "開始",
  missedNote: "錯過",
  ghost: "空打",
  correct: "正解",
  explainTitle: "本題解說",
  qHit: "對",
  qMiss: "錯",
  qRate: "命中率",
  continue: "繼續",
  continueHint: "空白鍵繼續",
  pause: "暫停",
  resume: "繼續",
  pausedTitle: "已暫停",
  mute: "靜音",
  unmute: "音效",
  concept: "概念答對",
  conceptNeed: "需八成",
  conceptShort: "概念答對不足八成",
  maxCombo: "最大連段",
  gauge: "魂槽",
  gogoHint: "後半段，分數加倍",
  studyTitle: "複習",
  studyLead: "先看手法、作用和例句，再開始演奏。",
};

const TECHNIQUES = [
  {
    id: "shunxu",
    cat: "敘事",
    name: "順敘法",
    stage: "both",
    hits: ["按時間先後把事情說清楚，讓讀者跟得上來龍去脈"],
    confusable: ["daoxu", "chaxu"],
    examples: [
      "早上出門，中午到校，傍晚回家。",
      "他先排隊買票，再進場找座位，最後才聽見第一聲哨響。",
      "我打開窗，看見雨停了，便拿起傘走下樓。",
    ],
  },
  {
    id: "daoxu",
    cat: "敘事",
    name: "倒敘法",
    stage: "both",
    hits: ["先寫結局或高潮，再回頭補述前因，製造懸念"],
    confusable: ["shunxu", "chaxu"],
    examples: [
      "成績單發下來的那一刻，我的手在抖。那兩個星期，我天天捧着書看到天亮。",
      "救護車開走以後，病房才安靜。三小時前，爺爺還在菜場跟我討價還價。",
      "鑰匙就在門墊下。我這才想起出門前隨手塞進去的動作。",
    ],
  },
  {
    id: "chaxu",
    cat: "敘事",
    name: "插敘法",
    stage: "junior",
    hits: ["在主線中插入一段相關往事，補充背景後再接回當下"],
    confusable: ["daoxu", "shunxu", "sanxu"],
    examples: [
      "這次上山很順。走到半路，我想起去年也是這條小路，阿公在前面喊我慢慢走。回過神，同伴已經走遠了。",
      "球賽還在打。暫停的空檔，教練突然講起自己中學那年也輸過決賽。哨聲一響，大家又跑回場上。",
      "媽媽炒着菜，忽然停下來，說起她小時候也怕切菜。說完，鍋裡的油已熱了。",
    ],
  },
  {
    id: "sanxu",
    cat: "敘事",
    name: "散敘",
    stage: "senior",
    hits: ["同時鋪開幾條線索，讓不同場景並置，組織更有層次"],
    confusable: ["shunxu", "chaxu"],
    examples: [
      "課室裡有人在抄筆記。家裏，弟弟趴在地上畫火車。街市那邊，阿婆還在跟魚販講價。同一時刻，三處都沒停過。",
      "雨打在圖書館的窗上。廚房裡湯還滾着。球場的哨聲遠遠傳來。這一天，城裡各有各的忙。",
      "我寫功課，奶奶織着毛衣，爸爸在陽台上打電話。客廳的鐘一下一下走。",
    ],
  },
  {
    id: "liuyao",
    cat: "敘事",
    name: "記敘六要素",
    stage: "primary",
    hits: ["把時間、地點、人物、起因、經過、結果交代齊，事情才完整"],
    confusable: ["shunxu", "daoxu"],
    examples: [
      "上星期六下午，公園的草坡上，我和媽媽發現小狗鑽進樹叢。我們沿水溝找了半小時，終於在石椅底下抱回牠。",
      "昨天放學後，圖書館三樓，我和同學因為找不到參考書，一格一格翻架，最後在還書車裡找到那本。",
      "清晨六點，碼頭邊，漁夫阿強見網破了，便坐下來補，補好後第一網就撈上幾條仍在跳的魚。",
    ],
  },
  {
    id: "first",
    cat: "人稱",
    name: "第一人稱",
    stage: "junior",
    hits: ["用「我」親述所見所感，讀來像自己經歷，容易引起共鳴"],
    confusable: ["second", "third"],
    examples: [
      "我走進課室，心裡又喜又怕。",
      "我把信疊好，塞進書包最底。",
      "我站在窗前，一句話也不說。",
    ],
  },
  {
    id: "second",
    cat: "人稱",
    name: "第二人稱",
    stage: "junior",
    hits: ["用「你」直接對讀者和筆下的人說話，拉近距離"],
    confusable: ["first", "third"],
    examples: [
      "你還記得那天的雨嗎？",
      "你把車停在老地方，門卻已經上鎖。",
      "你走進課室，心裡又喜又怕。",
    ],
  },
  {
    id: "third",
    cat: "人稱",
    name: "第三人稱",
    stage: "junior",
    hits: ["用「他／她」旁觀敘述，視角較客觀，方便寫多人"],
    confusable: ["first", "second"],
    examples: [
      "他站在窗前，一句話也不說。",
      "她把成績單對摺，推進抽屜深處。",
      "媽媽走進課室，心裡又喜又怕。",
    ],
  },
  {
    id: "buyi",
    cat: "寫景",
    name: "步移法",
    stage: "both",
    hits: ["跟着腳步轉換景物，讓讀者像一路走來看風景"],
    confusable: ["dingdian", "suishi", "yuanjin"],
    examples: [
      "轉過長廊，又見荷塘，再走上小丘。",
      "出了車站，沿着河走，過橋以後便是那間舊麵店。",
      "我從校門走到操場，再走進禮堂後門，每一段路景色都不同。",
    ],
  },
  {
    id: "suishi",
    cat: "寫景",
    name: "隨時推移法",
    stage: "junior",
    hits: ["按時間變化寫同一處景物，見出光影和氣氛的改變"],
    confusable: ["buyi", "dingdian"],
    examples: [
      "春花開了，夏雨來了，秋葉落下。",
      "早晨的海是銀的，中午變成刺眼的白，黃昏又染上一層橘。",
      "轉過長廊時還是清晨，走到小丘，天已經亮透了。",
    ],
  },
  {
    id: "dingdian",
    cat: "寫景",
    name: "定點描寫法",
    stage: "junior",
    hits: ["站在同一位置觀察，把眼前這一幅景寫深"],
    confusable: ["buyi", "suishi"],
    examples: [
      "坐在山頂，只看眼前這一幅城景：對岸的窗一格一格亮着，車燈像一條慢河。",
      "我沒有離開窗邊。樓下的榕樹、郵筒、走過的貓，都從這一個框裡進來。",
      "轉過長廊也能看見荷塘，可我仍坐在原地，只盯着眼前這一角。",
    ],
  },
  {
    id: "wugan",
    cat: "寫景",
    name: "五感描寫",
    stage: "both",
    hits: ["調動視、聽、嗅、味、觸，讓景物可感可觸"],
    confusable: ["tonggan", "dongtai"],
    examples: [
      "海風帶鹹，浪聲拍岸，沙粒扎腳。",
      "食堂裡油煙衝鼻，勺子碰碗叮叮響，湯還燙嘴。",
      "柳枝拍在臉上有點癢，溪水聲一直響，泥土是濕的。",
    ],
  },
  {
    id: "yuanjin",
    cat: "寫景",
    name: "由遠而近",
    stage: "primary",
    hits: ["從遠處看到近處，觀察有層次，景物才立體"],
    confusable: ["buyi", "dingdian"],
    examples: [
      "山影還在天邊，近一點是稻田，腳下已是被露水打濕的花圃。",
      "對岸的燈先亮，然後是橋上的車，最後連腳邊的水聲也聽得見。",
      "山還在遠處時只是一抹影，走近校門，連花圃上的露珠也看清了。",
    ],
  },
  {
    id: "zhijie",
    cat: "寫景",
    name: "直接描寫",
    stage: "both",
    hits: ["正面寫出景物本身的形狀、顏色和特點"],
    confusable: ["jianjie", "dongtai"],
    examples: [
      "這座山又高又陡，岩石呈鐵灰色。",
      "那條河很窄，水是淺綠色的，能看見底下的石子。",
      "這座山又高又陡，爬到半腰的人停下來喘氣。",
    ],
  },
  {
    id: "jianjie",
    cat: "寫景",
    name: "間接描寫",
    stage: "junior",
    hits: ["不直寫景物，而借旁人、他物的反應把景物襯出來"],
    confusable: ["zhijie", "cemian", "huanjing"],
    examples: [
      "路人紛紛拭汗，天氣熱得連影子都懶得動。",
      "狗把舌頭吐得很長，郵差把帽子當扇。",
      "這座山還沒寫完，半腰的人已停下來喘氣。",
    ],
  },
  {
    id: "dongtai",
    cat: "寫景",
    name: "動態描寫",
    stage: "both",
    hits: ["寫出景物的動作和變化，讓畫面有生命感"],
    confusable: ["jingtai", "niren"],
    examples: [
      "柳枝隨風擺動，溪水不斷奔流。",
      "旗在風裡拍打，操場上的球滾到圍欄邊。",
      "古塔矗立湖心，湖面上的漣漪一圈圈散開。",
    ],
  },
  {
    id: "jingtai",
    cat: "寫景",
    name: "靜態描寫",
    stage: "both",
    hits: ["把景物定格成一幅靜畫，氣氛更安定、更可凝視"],
    confusable: ["dongtai", "dingdian"],
    examples: [
      "古塔矗立湖心，水面平靜如鏡。",
      "書櫃靠牆，相框端正地擺在最上一格。",
      "柳枝垂着，像停住了一樣，連葉子也不動。",
    ],
  },
  {
    id: "dingyi",
    cat: "說明",
    name: "下定義",
    stage: "both",
    hits: ["用簡明的話揭示事物本質，讓讀者先抓住概念"],
    confusable: ["quanshi", "lizi"],
    examples: [
      "光合作用是植物把光能轉成化學能的過程。",
      "潮汐是海水受日月引力而定期漲退的現象。",
      "光合作用是植物利用陽光製造養分的過程，菜園因此才綠。",
    ],
  },
  {
    id: "fenlei",
    cat: "說明",
    name: "分類別",
    stage: "junior",
    hits: ["按標準把事物劃成幾類，說明才有條理"],
    confusable: ["dingyi", "lizi"],
    examples: [
      "文具可分為書寫、修正、繪畫三類。",
      "回收垃圾可分為紙類、塑膠、金屬和玻璃。",
      "可再生能源可分為風能、太陽能、水力發電三類。",
    ],
  },
  {
    id: "lizi",
    cat: "說明",
    name: "舉例子",
    stage: "both",
    hits: ["舉出具體實例，把抽象說明變得可想像"],
    confusable: ["shuzi", "yinyong"],
    examples: [
      "可再生能源如風能、太陽能、水力發電。",
      "常見的本地水果，例如荔枝、龍眼、黃皮，夏天特別多。",
      "文具有很多種，例如鉛筆、橡皮、水彩筆。",
    ],
  },
  {
    id: "bijiao",
    cat: "說明",
    name: "作比較",
    stage: "both",
    hits: ["比較同異來說明特點，讓分別一目了然"],
    confusable: ["duibi", "bifang"],
    examples: [
      "火車較慢但平穩，飛機較快但票貴。",
      "紙書可以批註，電子書方便搜尋。",
      "夜市比商場便宜，商場比夜市整齊，兩處功用不同。",
    ],
  },
  {
    id: "shuzi",
    cat: "說明",
    name: "列數字",
    stage: "both",
    hits: ["用確切數據說明規模或程度，增加可信"],
    confusable: ["lizi", "dingyi"],
    examples: [
      "全班四十二人，達標率百分之九十五。",
      "這座橋長一千二百米，來回步行約四十分鐘。",
      "全校去年用了八十萬度電，比前年少一成。",
    ],
  },
  {
    id: "bifang",
    cat: "說明",
    name: "打比方",
    stage: "both",
    hits: ["用比喻來說明陌生事物，讓概念好懂"],
    confusable: ["biyu", "biyu-lunzheng"],
    examples: [
      "互聯網像一條無形的公路，連接各地。",
      "心臟像一台日夜不歇的水泵，把血液送到全身。",
      "細胞壁像一堵圍牆，保護着細胞內部。",
    ],
  },
  {
    id: "yinyong",
    cat: "說明",
    name: "引資料",
    stage: "junior",
    hits: ["引用報告或數據來源，讓說明有根據"],
    confusable: ["lizi", "yinyong-xiuci"],
    examples: [
      "據氣象台報告，本週降雨量超過一百毫米。",
      "衛生署指出，兒童每天應睡九至十一小時。",
      "博物館解說牌寫着：這件瓷器燒於十六世紀。",
    ],
  },
  {
    id: "quanshi",
    cat: "說明",
    name: "作詮釋",
    stage: "junior",
    hits: ["換個說法解釋含義，比定義更展開、更好懂"],
    confusable: ["dingyi", "lizi"],
    examples: [
      "所謂堅持，是每天進步一點，不輕易放棄。",
      "所謂潮汐，簡單說就是海水定時漲上來、退下去。",
      "光合作用，說白了就是葉子靠陽光自己做飯。",
    ],
  },
  {
    id: "biyu",
    cat: "修辭",
    name: "比喻",
    stage: "both",
    hits: ["把抽象的心意寫成具體的事物，讓讀者容易感受"],
    confusable: ["niren", "kuazhang", "jiedai", "bifang"],
    examples: [
      "希望是黑夜裡的一盞燈。",
      "失望像一口沒有底的井。",
      "那句話是一根刺，一直扎在我心裡。",
    ],
  },
  {
    id: "niren",
    cat: "修辭",
    name: "擬人",
    stage: "both",
    hits: ["把事物當人來寫，讓景物有表情、有動作，更親切"],
    confusable: ["biyu", "tonggan"],
    examples: [
      "小草探出頭來，向春天打招呼。",
      "鬧鐘在床頭不耐煩地喊我起床。",
      "風在走廊裡跺腳，門也跟着生氣。",
    ],
  },
  {
    id: "kuazhang",
    cat: "修辭",
    name: "誇張／誇飾",
    stage: "both",
    hits: ["把程度說得遠超事實，以突出感受、加深印象"],
    confusable: ["biyu", "jiedai"],
    examples: [
      "他的聲音大得能把屋頂掀翻。",
      "書包重得像要陷進地裡。",
      "那盞燈亮得能照醒整條街。",
    ],
  },
  {
    id: "paibi",
    cat: "修辭",
    name: "排比",
    stage: "both",
    hits: ["連用結構相近的句子，加強語勢和節奏"],
    confusable: ["duiou", "fanfu", "cengdi"],
    examples: [
      "我愛山，愛水，愛這片安靜的土地。",
      "他會跑，會跳，會在操場上喊到沙啞。",
      "他會寫，會改，也會再寫一遍。",
    ],
  },
  {
    id: "duiou",
    cat: "修辭",
    name: "對偶",
    stage: "junior",
    hits: ["兩句字數、結構相對，讀來整齊，印象更深"],
    confusable: ["paibi", "dingzhen"],
    examples: [
      "牆上掛着舊書包，桌上攤着新功課。",
      "風停了樹還在，人走了燈還亮。",
      "青山橫北郭，白水繞東城。",
    ],
  },
  {
    id: "fanwen",
    cat: "修辭",
    name: "反問",
    stage: "both",
    hits: ["用問句表示確定的意思，語氣比直說更有力"],
    confusable: ["shewen", "fanfu"],
    examples: [
      "這樣的機會，難道你要放棄嗎？",
      "難道沉默就能把錯事抹掉？",
      "你還能當這件事沒發生嗎？",
    ],
  },
  {
    id: "shewen",
    cat: "修辭",
    name: "設問",
    stage: "both",
    hits: ["先自問再自答，引起注意，並帶出自己的看法"],
    confusable: ["fanwen", "hugao"],
    examples: [
      "什麼才是真正的勇敢？是面對恐懼仍向前走。",
      "功課為什麼越拖越重？因為今天推給明天。",
      "這樣的機會，你要放棄嗎？我想了想，還是報了名。",
    ],
  },
  {
    id: "fanfu",
    cat: "修辭",
    name: "反覆",
    stage: "both",
    hits: ["重複關鍵詞語，強調心意，讓節奏更緊"],
    confusable: ["paibi", "fanwen"],
    examples: [
      "加油，加油，加油！我們沒有放棄。",
      "回家，回家，只要能回家。",
      "我愛山，我愛山，我還是愛山。",
    ],
  },
  {
    id: "diezi",
    cat: "修辭",
    name: "疊字",
    stage: "both",
    hits: ["重疊音節，增添音律，把細微感覺寫出來"],
    confusable: ["fanfu", "paibi"],
    examples: [
      "風兒輕輕吹過，葉子沙沙作響。",
      "雨點滴滴答答打在鐵皮上。",
      "大家慢慢走，路還長長的。",
    ],
  },
  {
    id: "yinyong-xiuci",
    cat: "修辭",
    name: "引用",
    stage: "both",
    hits: ["引入名言或成句，增加文采，也讓意思有依憑"],
    confusable: ["yinyong", "yinyong-lunzheng"],
    examples: [
      "正如古語所說：「有志者事竟成。」",
      "他在信末抄了那句「己所不欲，勿施於人」，字寫得很端正。",
      "老師在黑板上寫下：「溫故而知新。」教室忽然靜了一下。",
    ],
  },
  {
    id: "cengdi",
    cat: "修辭",
    name: "層遞",
    stage: "senior",
    hits: ["按程度層層加深或減弱，把推進感寫出來"],
    confusable: ["paibi", "dingzhen"],
    examples: [
      "他會寫，會改，更會把文章寫到讓人記住。",
      "這病先是咳嗽，接着發燒，最後連水也喝不下。",
      "我愛山，愛水，更愛那片連名字也沒有的土地。",
    ],
  },
  {
    id: "dingzhen",
    cat: "修辭",
    name: "頂真",
    stage: "senior",
    hits: ["上一句的尾作下一句的頭，上下銜接，語氣連綿"],
    confusable: ["cengdi", "chengshang"],
    examples: [
      "園中有亭，亭邊有柳，柳下有人。",
      "他打開窗，窗上有霜，霜裡映着一張蒼白的臉。",
      "我愛山，山連着水，水通到那片安靜的土地。",
    ],
  },
  {
    id: "fanyu",
    cat: "修辭",
    name: "反語",
    stage: "senior",
    hits: ["字面說好，實際說反話，帶出諷刺或幽默"],
    confusable: ["fanwen", "shewen"],
    examples: [
      "你可真「勤快」，作業都拖到深夜。",
      "這「好主意」讓全班多留了一節課。",
      "你可真「勇敢」，躲在門後發抖。",
    ],
  },
  {
    id: "tonggan",
    cat: "修辭",
    name: "通感",
    stage: "senior",
    hits: ["把一種感官的感覺寫成另一種，打通體驗，印象更新鮮"],
    confusable: ["wugan", "biyu"],
    examples: [
      "這歌聲又冷又尖，像一條線從脊背劃下去。",
      "咖喱的熱氣是紅的，一進門就撞到臉上。",
      "那句安慰很暖，暖得耳根也熱了。",
    ],
  },
  {
    id: "hugao",
    cat: "修辭",
    name: "呼告",
    stage: "senior",
    hits: ["突然呼喚人或物，情感更急、更直接"],
    confusable: ["shewen", "zhijie-shuqing"],
    examples: [
      "媽媽，你聽見我在心裏喊你嗎？",
      "海啊，把這封信帶給他吧。",
      "老天，求你再下一次那場雨吧。",
    ],
  },
  {
    id: "jiedai",
    cat: "修辭",
    name: "借代",
    stage: "senior",
    hits: ["用相關的特徵代替本名，使形象更醒目、更簡潔"],
    confusable: ["biyu", "kuazhang"],
    examples: [
      "急診室裡，幾件白袍匆匆跑過。",
      "頒獎台上，那塊金牌閃了一下，全場都站起來。",
      "聽診器一進病房，整層樓都安靜了。",
    ],
  },
  {
    id: "duibi",
    cat: "修辭",
    name: "對比",
    stage: "junior",
    hits: ["把相反的兩面放在一起，差別更刺眼"],
    confusable: ["chentuan", "bijiao"],
    examples: [
      "一邊是燈火通明，一邊是漆黑小巷。",
      "早上還在笑，下午連招呼也不回。",
      "自修室燈火通明，對面房間提早關了燈。",
    ],
  },
  {
    id: "chentuan",
    cat: "修辭",
    name: "襯托",
    stage: "senior",
    hits: ["用旁邊的人、景作陪襯，把要寫的主體托得更明顯"],
    confusable: ["duibi", "huanjing"],
    examples: [
      "滿堂笑聲裡，只有他低頭不語。",
      "滿樹新葉之中，那根枯枝特別顯眼。",
      "大廳燈火通明，他站在暗處，更顯得瘦。",
    ],
  },
  {
    id: "waimao",
    cat: "描寫",
    name: "外貌描寫",
    stage: "both",
    hits: ["寫出外形、衣着和特徵，讓人物站到讀者眼前"],
    confusable: ["yuyan", "dongzuo", "baimiao"],
    examples: [
      "她梳着短髮，戴一副圓框眼鏡。",
      "爺爺的眉毛全白了，鼻梁上還有淺淺的眼鏡痕。",
      "他穿一件舊校服，圓框眼鏡有點歪。",
    ],
  },
  {
    id: "yuyan",
    cat: "描寫",
    name: "語言描寫",
    stage: "both",
    hits: ["用對話和口氣見性格，人物自己走出來"],
    confusable: ["dongzuo", "shentai"],
    examples: [
      "「我再試一次。」他低聲說。",
      "「你先走。」奶奶把傘塞過來，「我不怕雨。」",
      "他只丟下一句：「走吧。」",
    ],
  },
  {
    id: "dongzuo",
    cat: "描寫",
    name: "動作描寫",
    stage: "both",
    hits: ["用具體動作見性格和心情，比空說更有力"],
    confusable: ["yuyan", "xinli"],
    examples: [
      "他握緊拳頭，一步步走上講台。",
      "她把椅子拉近，把湯碗推到我面前。",
      "他說着「我再試一次」，把筆握得發白。",
    ],
  },
  {
    id: "xinli",
    cat: "描寫",
    name: "心理描寫",
    stage: "junior",
    hits: ["直接寫出內心活動，讓讀者進入人物的喜懼"],
    confusable: ["huanjing", "shentai"],
    examples: [
      "我心裡七上八下，生怕答錯。",
      "他在門後數自己的心跳，數到二十還是不敢按鈴。",
      "課室亮得刺眼，我卻覺得自己的耳膜在跳。",
    ],
  },
  {
    id: "shentai",
    cat: "描寫",
    name: "神態描寫",
    stage: "both",
    hits: ["寫眉眼、表情的細微變化，把情緒傳出來"],
    confusable: ["waimao", "xinli"],
    examples: [
      "老師微微皺眉，隨即又露出微笑。",
      "他眼角跳了一下，嘴卻仍抿着。",
      "她梳着短髮，眉心卻皺成一小團。",
    ],
  },
  {
    id: "huanjing",
    cat: "描寫",
    name: "環境描寫",
    stage: "junior",
    hits: ["寫周圍景物和氣氛，襯出人物心情或故事背景"],
    confusable: ["xinli", "jiejing", "cemian"],
    examples: [
      "課室靜得只聽見風扇轉動。",
      "走廊的燈管在閃，地板上有一灘未乾的水。",
      "我心裡七上八下，課室卻亮得刺眼。",
    ],
  },
  {
    id: "cemian",
    cat: "描寫",
    name: "側面描寫",
    stage: "senior",
    hits: ["借旁人的反應來寫人，威嚴或魅力不須自己誇"],
    confusable: ["waimao", "jianjie", "chentuan"],
    examples: [
      "同學都靜下來，班主任一進門，連椅子也不敢響。",
      "連最鬧的也把椅子收好，新老師還沒開口。",
      "她梳着短髮，戴圓框眼鏡，後排有人悄悄坐直。",
    ],
  },
  {
    id: "baimiao",
    cat: "描寫",
    name: "白描",
    stage: "senior",
    hits: ["少用形容和修辭，用極簡的線條把人、物勾出來"],
    confusable: ["waimao", "shentai"],
    examples: [
      "他穿一件舊校服，書包斜挎在肩上。",
      "門開着。桌上有一碗冷飯。",
      "她梳短髮，戴眼鏡，沒有再說什麼。",
    ],
  },
  {
    id: "zhijie-shuqing",
    cat: "抒情",
    name: "直接抒情",
    stage: "both",
    hits: ["把感情直說出來，態度明白，感染力強"],
    confusable: ["jiejing", "jieshi-shuqing"],
    examples: [
      "我真的很想念外婆。",
      "我好怕，怕到想轉身逃走。",
      "看着落葉，我只想說：我真的很想家。",
    ],
  },
  {
    id: "jiejing",
    cat: "抒情",
    name: "借景抒情",
    stage: "senior",
    hits: ["把感情寄在景物裡，情與景相生，含蓄而動人"],
    confusable: ["zhijie-shuqing", "tuowu", "huanjing"],
    examples: [
      "看着落葉飄下，我心裡也跟着沉了。",
      "潮水一退，沙上的字也沒了，我忽然不想再等。",
      "我真的很想念外婆。窗外的雨還在下，葉子一片一片掉。",
    ],
  },
  {
    id: "jieshi-shuqing",
    cat: "抒情",
    name: "借事抒情",
    stage: "senior",
    hits: ["借一件小事把感情托出來，不直喊，卻更耐讀"],
    confusable: ["jiejing", "zhijie-shuqing"],
    examples: [
      "他把我的行李箱提上月台，又彎腰把鞋帶重新繫好。車開了，那雙沒繫穩的鞋帶我到現在還記得。",
      "媽媽只是把橙剝開，一瓣一瓣排在我手心。我吃完才發現，自己沒說謝謝。",
      "看着落葉，我把舊車票捏皺。那一夜月台上的腳步，又回來了。",
    ],
  },
  {
    id: "tuowu",
    cat: "抒情",
    name: "托物言志",
    stage: "senior",
    hits: ["借一個物的品性表明心志，讓志向看得見"],
    confusable: ["jiejing", "zhijie-shuqing"],
    examples: [
      "風再大，這棵松也不肯彎腰。",
      "那盞燈殘了，燈芯卻還立着。",
      "落葉滿階，我把脊梁挺直，像那棵不肯彎的松。",
    ],
  },
  {
    id: "lili-lunzheng",
    cat: "議論",
    name: "舉例論證",
    stage: "junior",
    hits: ["舉具體事例證明觀點，道理不再空口說"],
    confusable: ["duibi-lunzheng", "yinyong-lunzheng"],
    examples: [
      "愛迪生失敗多次仍發明電燈，可見堅持有效。",
      "她每天早上六點練球，三年後入選校隊，足見工夫不會白費。",
      "愛迪生就是例子：失敗多次仍不放下，堅持才有效。",
    ],
  },
  {
    id: "duibi-lunzheng",
    cat: "議論",
    name: "對比論證",
    stage: "junior",
    hits: ["用正反兩面對照來說理，是非更分明"],
    confusable: ["lili-lunzheng", "duibi"],
    examples: [
      "勤奮的人進步，懶惰的人停滯，是非分明。",
      "同一道題，肯訂正的人下次會了，抄答案的人下次仍空白。",
      "自修室燈還亮着，對面房間提早關燈，誰在進步一目了然。",
    ],
  },
  {
    id: "yinyong-lunzheng",
    cat: "議論",
    name: "引用論證",
    stage: "junior",
    hits: ["引名言或權威說法作依據，增強說服力"],
    confusable: ["lili-lunzheng", "yinyong-xiuci"],
    examples: [
      "古語云「讀萬卷書，行萬里路」，可見實踐重要。",
      "老師常引「溫故而知新」，所以複習不是浪費時間。",
      "古語說「有志者事竟成」，我們便該把計劃做完。",
    ],
  },
  {
    id: "biyu-lunzheng",
    cat: "議論",
    name: "比喻論證",
    stage: "senior",
    hits: ["用比喻把道理說形象，論點更好懂、更好記"],
    confusable: ["biyu", "bifang", "leibi-lunzheng"],
    examples: [
      "知識如梯子，讓我們一步步升高，所以學習不能跳級貪快。",
      "誠信是存摺，透支一次，信用便難補，因此諾言不能隨口說。",
      "互聯網像一條公路，連接知識，可見我們更該學會判斷真假。",
    ],
  },
  {
    id: "leibi-lunzheng",
    cat: "議論",
    name: "類比論證",
    stage: "senior",
    hits: ["拿相似的事來比附，讓這個道理變得好接受"],
    confusable: ["biyu-lunzheng", "bijiao"],
    examples: [
      "學游泳要下水，學寫作也要多動筆。",
      "花不澆會枯，功課不溫也會忘。",
      "學騎腳踏車要跌過才站得穩，學辯論也一樣，怕開口就永遠不會。",
    ],
  },
  {
    id: "kaimen",
    cat: "結構",
    name: "開門見山",
    stage: "both",
    hits: ["一開頭就點明題旨，立場清楚，不繞彎"],
    confusable: ["zuzhang", "shouwei"],
    examples: [
      "這次旅行改變了我。",
      "我不怕黑，我怕的是一個人吃飯。",
      "我討厭運動。那天的操場卻讓我改了口。",
    ],
  },
  {
    id: "shouwei",
    cat: "結構",
    name: "首尾呼應",
    stage: "both",
    hits: ["開頭與結尾重複或扣緊同一句、同一意象，結構完整"],
    confusable: ["kaimen", "zuzhang"],
    examples: [
      "我想家。在車上數站牌，在旅館聽隔壁的電視，最後一夜，我還是把「想家」寫在明信片第一句。",
      "門前那棵樹很小。三年後我回來，樹還在，我在日記末行又寫了一次：門前那棵樹很小。",
      "這次旅行改變了我。一路上吃了很多沒見過的東西，下車時我又把這句話抄在封面。",
    ],
  },
  {
    id: "zongfenzong",
    cat: "結構",
    name: "總分總",
    stage: "primary",
    hits: ["先總說、再分寫、最後收束，綱目清楚，段落好跟"],
    confusable: ["kaimen", "shouwei"],
    examples: [
      "校園很美。花圃的蘭花開成一排，操場邊的樹也新綠了。這樣一看，處處都乾淨得發亮。",
      "這頓晚飯很暖。湯是熱的，菜是家常的，連筷子都是我慣用的那雙。原來暖就是這些小事。",
      "這次旅行很值得。山很陡，海很亮，夜市也很吵。回想起來，每一段都記得。",
    ],
  },
  {
    id: "xiangluo",
    cat: "結構",
    name: "詳寫略寫",
    stage: "both",
    hits: ["重要處細寫、次要處帶過，重點才站得住"],
    confusable: ["fubi", "chengshang"],
    examples: [
      "進場只用了兩分鐘。真正的比賽裡，他起跑慢了半步，彎道超前，最後十米把牙咬出血，我連呼吸都忘了。",
      "搬家那天，紙箱的事一句帶過。我只記得最後一晚，壁虎還在舊房間的燈下爬。",
      "我想家，這句只出現兩次。中間卻把旅館的肥皂、窗縫的風、隔壁的電視一一寫完。",
    ],
  },
  {
    id: "chengshang",
    cat: "結構",
    name: "承上啟下",
    stage: "both",
    hits: ["用過渡句接住上段、打開下段，文章不致斷裂"],
    confusable: ["dingzhen", "shouwei"],
    examples: [
      "課室的笑聲還沒散。走出門外，操場更熱鬧，哨聲把我們全捲進去。",
      "湯喝完了。碗一放，話題便轉到明天的考試，客廳忽然靜下來。",
      "亭邊的柳還在搖。轉過柳樹，另一段路才開始，蟬聲也換了調。",
    ],
  },
  {
    id: "yuyang",
    cat: "結構",
    name: "欲揚先抑",
    stage: "senior",
    hits: ["先壓低再抬高，轉折後的好處或好處中的人更突出"],
    confusable: ["kaimen", "zuzhang"],
    examples: [
      "他在班上毫不起眼，值日也常忘。火災演習那天，卻是他先把後門打開，讓全層走完。",
      "那家店又窄又暗，菜單發黃。一碗麵端來，湯卻清得讓人想再排隊。",
      "這次旅行很悶，車程又長。下車以後，風一吹，我才明白自己改變了。",
    ],
  },
  {
    id: "fubi",
    cat: "結構",
    name: "伏筆",
    stage: "senior",
    hits: ["先輕輕放下一個細節，後文再應，讀來有呼應、有驚喜"],
    confusable: ["chaxu", "xiangluo"],
    examples: [
      "出門前，他把生鏽的鑰匙丟進抽屜。深夜回來，抽屜裡那把鑰匙卻成了唯一能開門的東西。",
      "她隨口說自己不怕狗。公園轉角出現那隻大黃狗時，她的腳先停了。",
      "門墊下鼓起一小塊。整晚過後，醉掉的主人就是用那把備用鑰匙回了家。",
    ],
  },
  {
    id: "zuzhang",
    cat: "結構",
    name: "卒章顯志",
    stage: "senior",
    hits: ["到篇末才點明主旨，前文的人、事、物忽然有了着落"],
    confusable: ["kaimen", "shouwei"],
    examples: [
      "車票、收據、一顆捂熱的糖果，我把它們倒在桌上。原來家才是最暖的地方。",
      "燈關了，樓道還有人在走。我這才懂，安靜也是一種陪伴。",
      "玩到最後一天，日記只剩一行：原來家才是最暖的地方。",
    ],
  },
];
