/** Ch2 Cellular Organizations — pages 1–15 (bilingual EN + 中文) */
export const FLASHCARD_TAGS = ["Biology", "Ch2", "Cells", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "細胞理論與顯微鏡",
    front: "Cell theory 細胞理論: cells are the ____ of life. 細胞是生命的____。",
    back: "<strong>Smallest functioning units 最小功能單位</strong>",
  },
  {
    id: 2,
    subtopic: "細胞理論與顯微鏡",
    front: "Cell theory 細胞理論: all organisms consist of? 所有生物由什麼組成？",
    back: "<strong>One or more cells 一個或多個細胞</strong>",
  },
  {
    id: 3,
    subtopic: "細胞理論與顯微鏡",
    front: "Cell theory 細胞理論: cells arise from? Example? 細胞從何而來？例子？",
    back: "<strong>Pre-existing cells 已存在的細胞</strong>（for example 例如: cell division 細胞分裂）",
  },
  {
    id: 4,
    subtopic: "細胞理論與顯微鏡",
    front: "Unicellular 單細胞 versus multicellular 多細胞? 單細胞與多細胞有何分別？",
    back: "Unicellular 單細胞: <strong>one cell 一個細胞</strong>；Multicellular 多細胞: <strong>many cells 許多細胞</strong>",
  },
  {
    id: 5,
    subtopic: "細胞理論與顯微鏡",
    front: "Light microscope 光學顯微鏡 versus electron microscopes 電子顯微鏡: image formation? 影像如何形成？",
    back: "Light 光學: <strong>visible light 可見光</strong>（naked eyes 肉眼）；Electron 電子: <strong>electron beams 電子束</strong>（computer 電腦）",
  },
  {
    id: 6,
    subtopic: "細胞理論與顯微鏡",
    front: "Transmission Electron Microscope 透射電子顯微鏡 versus Scanning Electron Microscope 掃描電子顯微鏡: max magnification roughly? 最高放大倍數大約？",
    back: "Transmission 透射: up to 最高約 <strong>10,000,000×</strong>；Scanning 掃描: up to 最高約 <strong>500,000×</strong>；（Light 光學: up to 最高約 <strong>2,000×</strong>）",
  },
  {
    id: 7,
    subtopic: "細胞理論與顯微鏡",
    front: "Can electron microscopes 電子顯微鏡 view living cells 活細胞? Why? 能觀察活細胞嗎？為何？",
    back: "<strong>No 不能</strong> — fixation 固定 <strong>kills 殺死</strong> cells 細胞",
  },
  {
    id: 8,
    subtopic: "細胞理論與顯微鏡",
    front: "Common stains 常用染色劑: plant cells 植物細胞 versus animal cells 動物細胞?",
    back: "Plant 植物: <strong>iodine solution 碘液</strong>；Animal 動物: <strong>methylene blue 亞甲藍</strong>",
  },
  {
    id: 9,
    subtopic: "光學顯微鏡使用與計算",
    front: "Before high power 高倍, what must you do first? 用高倍鏡前必須先做什麼？",
    back: "★Focus under <strong>low power 低倍</strong> first　先在低倍對焦",
  },
  {
    id: 10,
    subtopic: "光學顯微鏡使用與計算",
    front: "Coarse versus fine adjustment knob: when used? 粗準焦與微準焦螺旋：何時使用？",
    back: "Coarse 粗準焦: <strong>raise/lower to find focus 升降以找焦點</strong>（low power 低倍）；Fine 微準焦: <strong>sharpen 調銳</strong>（especially high power 尤其高倍）",
  },
  {
    id: 11,
    subtopic: "光學顯微鏡使用與計算",
    front: "Field of view 視野: low power 低倍 versus high power 高倍?",
    back: "Low 低倍: <strong>larger area, less detail 較大範圍、較少細節</strong>；High 高倍: <strong>smaller area, more detail 較小範圍、較多細節</strong>",
  },
  {
    id: 12,
    subtopic: "光學顯微鏡使用與計算",
    front: "Which needs more light: low or high power? Why? 低倍還是高倍需要更多光線？為何？",
    back: "<strong>High power 高倍</strong> — smaller field of view 視野較小 = less light 光線較少",
  },
  {
    id: 13,
    subtopic: "光學顯微鏡使用與計算",
    front: "Actual length 實際長度 formula (from magnified image 由放大影像)? 公式是什麼？",
    back: "<strong>Actual length = measured length ÷ magnification</strong>　實際長度 = 量度長度 ÷ 放大倍數",
  },
  {
    id: 14,
    subtopic: "光學顯微鏡使用與計算",
    front: "How get magnification 放大倍數 from a scale bar 比例尺? 如何由比例尺求放大倍數？",
    back: "Magnification 放大倍數 = <strong>image length of scale ÷ actual length of scale</strong>　比例尺影像長度 ÷ 比例尺實際長度",
  },
  {
    id: 15,
    subtopic: "光學顯微鏡使用與計算",
    front: "1 cm = ? mm = ? μm　1 厘米等於多少毫米、微米？",
    back: "<strong>10 mm</strong> = <strong>10,000 μm</strong>　10 毫米 = 10,000 微米",
  },
  {
    id: 16,
    subtopic: "光學顯微鏡使用與計算",
    front: "1 mm = ? μm；1 μm = ? cm　1 毫米等於多少微米？1 微米等於多少厘米？",
    back: "<strong>1,000 μm</strong>；<strong>0.0001 cm</strong>　1,000 微米；0.0001 厘米",
  },
  {
    id: 17,
    subtopic: "真核與原核",
    front: "Eukaryotic 真核 versus prokaryotic 原核: true nucleus 真正細胞核?",
    back: "Eukaryotic 真核: <strong>with true nucleus 有真正細胞核</strong>（nuclear membrane 核膜）；Prokaryotic 原核: <strong>no true nucleus 無真正細胞核</strong>（circular DNA 環狀 DNA free in cytoplasm 游離於細胞質）",
  },
  {
    id: 18,
    subtopic: "真核與原核",
    front: "Membrane-bounded organelles 膜性胞器: eukaryotic 真核 versus prokaryotic 原核?",
    back: "Eukaryotic 真核: <strong>present 有</strong>；Prokaryotic 原核: <strong>absent 無</strong>",
  },
  {
    id: 19,
    subtopic: "真核與原核",
    front: "Cell wall 細胞壁: plant eukaryotic cells 植物真核細胞 versus bacteria 細菌?",
    back: "Plant 植物: <strong>cellulose 纖維素</strong>；Bacteria 細菌: <strong>peptidoglycan 肽聚醣</strong>（non-cellulose 非纖維素）",
  },
  {
    id: 20,
    subtopic: "真核與原核",
    front: "Ribosomes 核糖體 location 位置: eukaryotic 真核 versus prokaryotic 原核?",
    back: "Eukaryotic 真核: free 游離 and/or on <strong>rough endoplasmic reticulum 粗面內質網</strong>；Prokaryotic 原核: <strong>free in cytoplasm 只游離於細胞質</strong> only",
  },
  {
    id: 21,
    subtopic: "真核與原核",
    front: "Identify these cells. 辨認這些細胞。",
    back: "<strong>Bacteria (prokaryotes) 細菌（原核）</strong>",
    imageFront: "./assets/pm_bacteria_a.jpeg",
    imageFrontAlt: "Rod-shaped stained bacteria under light microscope 光學顯微鏡下的桿狀染色細菌",
  },
  {
    id: 22,
    subtopic: "細胞器",
    front: "Cell membrane 細胞膜 permeability type 通透性類型? Function 功能?",
    back: "<strong>Differentially permeable 差異滲透性</strong> — controls substance movement 控制物質進出",
  },
  {
    id: 23,
    subtopic: "細胞器",
    front: "Fluid mosaic model 流動鑲嵌模型: main two components 主要兩種成分?",
    back: "<strong>Phospholipid bilayer 磷脂雙層</strong> + <strong>proteins 蛋白質</strong>",
  },
  {
    id: 24,
    subtopic: "細胞器",
    front: "Cell wall 細胞壁: permeability 通透性? Present in animal cells 動物細胞有沒有?",
    back: "<strong>Fully permeable 全透性</strong>；<strong>absent 沒有</strong> in animal cells 動物細胞（plant 植物: cellulose 纖維素）",
  },
  {
    id: 25,
    subtopic: "細胞器",
    front: "Cytoplasm 細胞質: two roles 兩項功能?",
    back: "Site of <strong>metabolic reactions 代謝反應場所</strong>；<strong>transport medium 運輸介質</strong>",
  },
  {
    id: 26,
    subtopic: "細胞器",
    front: "Vacuole 液泡: animal 動物 versus plant 植物?",
    back: "Animal 動物: <strong>small/none 細小／沒有</strong>；Plant 植物: <strong>large & central 大型中央液泡</strong>",
  },
  {
    id: 27,
    subtopic: "細胞器",
    front: "Nucleus 細胞核: main roles 主要功能?",
    back: "<strong>Genetic control 遺傳控制</strong>；DNA replication DNA 複製；control protein synthesis 控制蛋白質合成",
  },
  {
    id: 28,
    subtopic: "細胞器",
    front: "Nucleolus 核仁 makes? 核仁製造什麼？",
    back: "<strong>Ribosomes 核糖體</strong>",
  },
  {
    id: 29,
    subtopic: "細胞器",
    front: "Mature red blood cells 成熟紅血球: nucleus 細胞核?",
    back: "★<strong>Absent 沒有</strong>",
  },
  {
    id: 30,
    subtopic: "細胞器",
    front: "Ribosomes 核糖體: function 功能? Composition 組成?",
    back: "<strong>Protein synthesis 蛋白質合成</strong>；<strong>RNA + proteins RNA + 蛋白質</strong>",
  },
  {
    id: 31,
    subtopic: "細胞器",
    front: "Rough endoplasmic reticulum 粗面內質網: ribosomes 核糖體? Function 功能?",
    back: "Membrane <strong>with ribosomes 有核糖體的膜</strong>；<strong>protein 蛋白質</strong> synthesis & transport 合成與運輸",
  },
  {
    id: 32,
    subtopic: "細胞器",
    front: "Smooth endoplasmic reticulum 滑面內質網: ribosomes 核糖體? Function 功能?",
    back: "Membrane <strong>without ribosomes 沒有核糖體的膜</strong>；<strong>lipid 脂質</strong> synthesis & transport 合成與運輸",
  },
  {
    id: 33,
    subtopic: "細胞器",
    front: "Mitochondria 粒線體: function 功能? Membrane layers 膜層數?",
    back: "<strong>Aerobic respiration 有氧呼吸</strong> → ATP；<strong>double 雙層</strong> membrane 膜",
  },
  {
    id: 34,
    subtopic: "細胞器",
    front: "Chloroplast 葉綠體: function 功能? Stores product as 產物貯存為何?",
    back: "<strong>Photosynthesis 光合作用</strong>；stores <strong>starch 澱粉</strong>",
  },
  {
    id: 35,
    subtopic: "細胞器",
    front: "Chloroplast 葉綠體 found in 見於? Not found in 不見於?",
    back: "Found 見於: mesophyll / guard cells 葉肉／保衛細胞；<strong>Not 不見於</strong> leaf epidermis / onion skin 葉表皮／洋蔥表皮",
  },
  {
    id: 36,
    subtopic: "動植物細胞比較",
    front: "Shape 形狀: animal versus plant cells 動物細胞與植物細胞?",
    back: "Animal 動物: usually <strong>irregular 不規則</strong>；Plant 植物: <strong>fixed by cell wall 由細胞壁固定</strong>",
  },
  {
    id: 37,
    subtopic: "動植物細胞比較",
    front: "Cell wall 細胞壁: animal versus plant 動物與植物?",
    back: "Animal 動物: <strong>absent 沒有</strong>；Plant 植物: <strong>present 有</strong>",
  },
  {
    id: 38,
    subtopic: "動植物細胞比較",
    front: "Vacuole 液泡: animal versus plant 動物與植物?",
    back: "Animal 動物: none or few small 沒有或少數細小；Plant 植物: <strong>large central vacuole 大型中央液泡</strong>",
  },
  {
    id: 39,
    subtopic: "動植物細胞比較",
    front: "Chloroplast 葉綠體: animal versus plant 動物與植物?",
    back: "Animal 動物: <strong>absent 沒有</strong>；Plant 植物: present in <strong>green 綠色</strong> plant cells 植物細胞",
  },
  {
    id: 40,
    subtopic: "顯微照片辨認",
    front: "Identify the <strong>green organelles</strong> in these plant cells. 辨認這些植物細胞中的<strong>綠色細胞器</strong>。",
    back: "<strong>Chloroplast 葉綠體</strong>",
    imageFront: "./assets/pm_chloroplast_c.jpeg",
    imageFrontAlt: "Light micrograph of green plant cells with chloroplasts 綠色植物細胞與葉綠體的光學顯微照片",
  },
  {
    id: 41,
    subtopic: "顯微照片辨認",
    front: "Identify this organelle (note internal folds / cristae). 辨認此細胞器（注意內摺／嵴）。",
    back: "<strong>Mitochondria 粒線體</strong>",
    imageFront: "./assets/pm_mitochondria_b.png",
    imageFrontAlt: "Electron micrograph showing mitochondria with cristae 顯示粒線體嵴的電子顯微照片",
  },
  {
    id: 42,
    subtopic: "顯微照片辨認",
    front: "Identify the <strong>dark dense body</strong> inside the nucleus (marked on the figure). 辨認細胞核內的<strong>深色緻密體</strong>（圖中標示）。",
    back: "<strong>Nucleolus 核仁</strong>",
    imageFront: "./assets/pm_nucleus.jpeg",
    imageFrontAlt: "Electron micrograph of nucleus with nucleolus marked on the figure 標示核仁的細胞核電子顯微照片",
  },
  {
    id: 43,
    subtopic: "顯微照片辨認",
    front: "Identify the membrane system with <strong>attached ribosomes</strong> (dots). 辨認附有<strong>核糖體</strong>的膜系統。",
    back: "<strong>Rough endoplasmic reticulum 粗面內質網</strong>",
    imageFront: "./assets/pm_rough_er.png",
    imageFrontAlt: "Electron micrograph of rough endoplasmic reticulum with ribosomes 附核糖體的粗面內質網電子顯微照片",
  },
  {
    id: 44,
    subtopic: "顯微照片辨認",
    front: "Identify the membrane stacks (<strong>no ribosomes</strong>). 辨認<strong>無核糖體</strong>的膜堆疊。",
    back: "<strong>Smooth endoplasmic reticulum 滑面內質網</strong>",
    imageFront: "./assets/pm_smooth_er.gif",
    imageFrontAlt: "Electron micrograph showing smooth endoplasmic reticulum 滑面內質網電子顯微照片",
  },
  {
    id: 45,
    subtopic: "顯微照片辨認",
    front: "Identify the <strong>large empty space</strong> and the <strong>dark oval bodies</strong> with stacks. 辨認<strong>大空腔</strong>與具堆疊的<strong>深色橢圓體</strong>。",
    back: "<strong>Vacuole 液泡</strong> + <strong>chloroplast 葉綠體</strong>",
    imageFront: "./assets/pm_vacuole_chloro.png",
    imageFrontAlt: "Electron micrograph of plant cell with vacuole and chloroplasts 植物細胞液泡與葉綠體的電子顯微照片",
  },
];
