/** Ch2 Cellular Organizations — pages 1–15 (bilingual EN + 中文) */
export const FLASHCARD_TAGS = ["Biology", "Ch2", "Cells", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "細胞理論與顯微鏡",
    front: "Cell theory 細胞理論: cells are the ____ of life.",
    back: "<strong>Smallest functioning units 最小功能單位</strong>",
  },
  {
    id: 2,
    subtopic: "細胞理論與顯微鏡",
    front: "Cell theory: all organisms consist of?",
    back: "<strong>One or more cells</strong>　一個或多個細胞",
  },
  {
    id: 3,
    subtopic: "細胞理論與顯微鏡",
    front: "Cell theory: cells arise from? Example?",
    back: "<strong>Pre-existing cells 已存在的細胞</strong> (for example: cell division 細胞分裂)",
  },
  {
    id: 4,
    subtopic: "細胞理論與顯微鏡",
    front: "Unicellular 單細胞 versus multicellular 多細胞?",
    back: "Unicellular: <strong>one cell</strong>；Multicellular: <strong>many cells</strong>",
  },
  {
    id: 5,
    subtopic: "細胞理論與顯微鏡",
    front: "Light microscope 光學顯微鏡 versus electron microscopes: image formation?",
    back: "Light: <strong>visible light</strong> (naked eyes)；Electron: <strong>electron beams</strong> (computer)",
  },
  {
    id: 6,
    subtopic: "細胞理論與顯微鏡",
    front: "Transmission Electron Microscope versus Scanning Electron Microscope: max magnification roughly?",
    back: "Transmission: up to <strong>10,000,000×</strong>；Scanning: up to <strong>500,000×</strong>；(Light: up to <strong>2,000×</strong>)",
  },
  {
    id: 7,
    subtopic: "細胞理論與顯微鏡",
    front: "Can electron microscopes view living cells? Why?",
    back: "<strong>No</strong> — fixation 固定 <strong>kills</strong> cells",
  },
  {
    id: 8,
    subtopic: "細胞理論與顯微鏡",
    front: "Common stains: plant cells versus animal cells?",
    back: "Plant: <strong>iodine solution 碘液</strong>；Animal: <strong>methylene blue 亞甲藍</strong>",
  },
  {
    id: 9,
    subtopic: "光學顯微鏡使用與計算",
    front: "Before high power, what must you do first?",
    back: "★Focus under <strong>low power</strong> first　先在低倍對焦",
  },
  {
    id: 10,
    subtopic: "光學顯微鏡使用與計算",
    front: "Coarse versus fine adjustment knob: when used?",
    back: "Coarse 粗準焦: <strong>raise/lower to find focus</strong> (low power)；Fine 微準焦: <strong>sharpen</strong> (especially high power)",
  },
  {
    id: 11,
    subtopic: "光學顯微鏡使用與計算",
    front: "Field of view: low power versus high power?",
    back: "Low: <strong>larger area, less detail</strong>；High: <strong>smaller area, more detail</strong>",
  },
  {
    id: 12,
    subtopic: "光學顯微鏡使用與計算",
    front: "Which needs more light: low or high power? Why?",
    back: "<strong>High power</strong> — smaller field of view = less light",
  },
  {
    id: 13,
    subtopic: "光學顯微鏡使用與計算",
    front: "Actual length formula (from magnified image)?",
    back: "<strong>Actual length = measured length ÷ magnification</strong>",
  },
  {
    id: 14,
    subtopic: "光學顯微鏡使用與計算",
    front: "How get magnification from a scale bar?",
    back: "Magnification = <strong>image length of scale ÷ actual length of scale</strong>",
  },
  {
    id: 15,
    subtopic: "光學顯微鏡使用與計算",
    front: "1 cm = ? mm = ? μm",
    back: "<strong>10 mm</strong> = <strong>10,000 μm</strong>",
  },
  {
    id: 16,
    subtopic: "光學顯微鏡使用與計算",
    front: "1 mm = ? μm；1 μm = ? cm",
    back: "<strong>1,000 μm</strong>；<strong>0.0001 cm</strong>",
  },
  {
    id: 17,
    subtopic: "真核與原核",
    front: "Eukaryotic 真核 versus prokaryotic 原核: true nucleus?",
    back: "Eukaryotic: <strong>with true nucleus</strong> (nuclear membrane 核膜)；Prokaryotic: <strong>no true nucleus</strong> (circular DNA free in cytoplasm)",
  },
  {
    id: 18,
    subtopic: "真核與原核",
    front: "Membrane-bounded organelles 膜性胞器: eukaryotic versus prokaryotic?",
    back: "Eukaryotic: <strong>present</strong>；Prokaryotic: <strong>absent</strong>",
  },
  {
    id: 19,
    subtopic: "真核與原核",
    front: "Cell wall: plant eukaryotic cells versus bacteria?",
    back: "Plant: <strong>cellulose 纖維素</strong>；Bacteria: <strong>peptidoglycan 肽聚醣</strong> (non-cellulose)",
  },
  {
    id: 20,
    subtopic: "真核與原核",
    front: "Ribosomes location: eukaryotic versus prokaryotic?",
    back: "Eukaryotic: free and/or on <strong>rough endoplasmic reticulum</strong>；Prokaryotic: <strong>free in cytoplasm</strong> only",
  },
  {
    id: 21,
    subtopic: "真核與原核",
    front: "Identify these cells. 辨認這些細胞。",
    back: "<strong>Bacteria (prokaryotes) 細菌（原核）</strong>",
    imageFront: "./assets/pm_bacteria_a.jpeg",
    imageFrontAlt: "Rod-shaped stained bacteria under light microscope",
  },
  {
    id: 22,
    subtopic: "細胞器",
    front: "Cell membrane 細胞膜 permeability type? Function?",
    back: "<strong>Differentially permeable 差異滲透性</strong> — controls substance movement",
  },
  {
    id: 23,
    subtopic: "細胞器",
    front: "Fluid mosaic model 流動鑲嵌模型: main two components?",
    back: "<strong>Phospholipid bilayer 磷脂雙層</strong> + <strong>proteins</strong>",
  },
  {
    id: 24,
    subtopic: "細胞器",
    front: "Cell wall 細胞壁: permeability? Present in animal cells?",
    back: "<strong>Fully permeable</strong>；<strong>absent</strong> in animal cells (plant: cellulose)",
  },
  {
    id: 25,
    subtopic: "細胞器",
    front: "Cytoplasm 細胞質: two roles?",
    back: "Site of <strong>metabolic reactions</strong>；<strong>transport medium</strong>",
  },
  {
    id: 26,
    subtopic: "細胞器",
    front: "Vacuole 液泡: animal versus plant?",
    back: "Animal: <strong>small/none</strong>；Plant: <strong>large & central</strong>",
  },
  {
    id: 27,
    subtopic: "細胞器",
    front: "Nucleus 細胞核: main roles?",
    back: "<strong>Genetic control</strong>；DNA replication；control protein synthesis",
  },
  {
    id: 28,
    subtopic: "細胞器",
    front: "Nucleolus 核仁 makes?",
    back: "<strong>Ribosomes 核糖體</strong>",
  },
  {
    id: 29,
    subtopic: "細胞器",
    front: "Mature red blood cells: nucleus?",
    back: "★<strong>Absent</strong>",
  },
  {
    id: 30,
    subtopic: "細胞器",
    front: "Ribosomes 核糖體: function? Composition?",
    back: "<strong>Protein synthesis</strong>；<strong>RNA + proteins</strong>",
  },
  {
    id: 31,
    subtopic: "細胞器",
    front: "Rough endoplasmic reticulum: ribosomes? Function?",
    back: "Membrane <strong>with ribosomes</strong>；<strong>protein</strong> synthesis & transport",
  },
  {
    id: 32,
    subtopic: "細胞器",
    front: "Smooth endoplasmic reticulum: ribosomes? Function?",
    back: "Membrane <strong>without ribosomes</strong>；<strong>lipid</strong> synthesis & transport",
  },
  {
    id: 33,
    subtopic: "細胞器",
    front: "Mitochondria 粒線體: function? Membrane layers?",
    back: "<strong>Aerobic respiration</strong> → ATP；<strong>double</strong> membrane",
  },
  {
    id: 34,
    subtopic: "細胞器",
    front: "Chloroplast 葉綠體: function? Stores product as?",
    back: "<strong>Photosynthesis</strong>；stores <strong>starch</strong>",
  },
  {
    id: 35,
    subtopic: "細胞器",
    front: "Chloroplast found in? Not found in?",
    back: "Found: mesophyll / guard cells；<strong>Not</strong> in leaf epidermis / onion skin",
  },
  {
    id: 36,
    subtopic: "動植物細胞比較",
    front: "Shape: animal versus plant cells?",
    back: "Animal: usually <strong>irregular</strong>；Plant: <strong>fixed by cell wall</strong>",
  },
  {
    id: 37,
    subtopic: "動植物細胞比較",
    front: "Cell wall: animal versus plant?",
    back: "Animal: <strong>absent</strong>；Plant: <strong>present</strong>",
  },
  {
    id: 38,
    subtopic: "動植物細胞比較",
    front: "Vacuole: animal versus plant?",
    back: "Animal: none or few small；Plant: <strong>large central vacuole</strong>",
  },
  {
    id: 39,
    subtopic: "動植物細胞比較",
    front: "Chloroplast: animal versus plant?",
    back: "Animal: <strong>absent</strong>；Plant: present in <strong>green</strong> plant cells",
  },
  {
    id: 40,
    subtopic: "顯微照片辨認",
    front: "Identify the <strong>green organelles</strong> in these plant cells. 辨認這些植物細胞中的<strong>綠色細胞器</strong>。",
    back: "<strong>Chloroplast 葉綠體</strong>",
    imageFront: "./assets/pm_chloroplast_c.jpeg",
    imageFrontAlt: "Light micrograph of green plant cells with chloroplasts",
  },
  {
    id: 41,
    subtopic: "顯微照片辨認",
    front: "Identify this organelle (note internal folds / cristae). 辨認此細胞器（注意內摺）。",
    back: "<strong>Mitochondria 粒線體</strong>",
    imageFront: "./assets/pm_mitochondria_b.png",
    imageFrontAlt: "Electron micrograph showing mitochondria with cristae",
  },
  {
    id: 42,
    subtopic: "顯微照片辨認",
    front: "Identify the <strong>dark dense body</strong> inside the nucleus (marked on the figure). 辨認細胞核內的<strong>深色緻密體</strong>（圖中標示）。",
    back: "<strong>Nucleolus 核仁</strong>",
    imageFront: "./assets/pm_nucleus.jpeg",
    imageFrontAlt: "Electron micrograph of nucleus with nucleolus marked on the figure",
  },
  {
    id: 43,
    subtopic: "顯微照片辨認",
    front: "Identify the membrane system with <strong>attached ribosomes</strong> (dots). 辨認附有<strong>核糖體</strong>的膜系統。",
    back: "<strong>Rough endoplasmic reticulum 粗面內質網</strong>",
    imageFront: "./assets/pm_rough_er.png",
    imageFrontAlt: "Electron micrograph of rough endoplasmic reticulum with ribosomes",
  },
  {
    id: 44,
    subtopic: "顯微照片辨認",
    front: "Identify the membrane stacks (<strong>no ribosomes</strong>). 辨認<strong>無核糖體</strong>的膜堆疊。",
    back: "<strong>Smooth endoplasmic reticulum 滑面內質網</strong>",
    imageFront: "./assets/pm_smooth_er.gif",
    imageFrontAlt: "Electron micrograph showing smooth endoplasmic reticulum",
  },
  {
    id: 45,
    subtopic: "顯微照片辨認",
    front: "Identify the <strong>large empty space</strong> and the <strong>dark oval bodies</strong> with stacks. 辨認<strong>大空腔</strong>與具堆疊的<strong>深色橢圓體</strong>。",
    back: "<strong>Vacuole 液泡</strong> + <strong>chloroplast 葉綠體</strong>",
    imageFront: "./assets/pm_vacuole_chloro.png",
    imageFrontAlt: "Electron micrograph of plant cell with vacuole and chloroplasts",
  },
];
