/** Ch2 Cellular Organizations — pages 1–15 (bilingual EN + 中文) */
export const FLASHCARD_TAGS = ["Biology", "Ch2", "Cells", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "細胞理論與顯微鏡",
    front: "According to cell theory, cells are the ____ of life.<br>根據細胞理論，細胞是生命的____。",
    back: "Cells are the <strong>smallest functioning units</strong> of life.<br>細胞是生命的<strong>最小功能單位</strong>。",
  },
  {
    id: 2,
    subtopic: "細胞理論與顯微鏡",
    front: "According to cell theory, what do all organisms consist of?<br>根據細胞理論，所有生物由什麼組成？",
    back: "All organisms consist of <strong>one or more cells</strong>.<br>所有生物由<strong>一個或多個細胞</strong>組成。",
  },
  {
    id: 3,
    subtopic: "細胞理論與顯微鏡",
    front: "According to cell theory, where do cells arise from, and what is one example?<br>根據細胞理論，細胞從何而來？試舉一例。",
    back: "Cells arise from <strong>pre-existing cells</strong>, for example by cell division.<br>細胞來自<strong>已存在的細胞</strong>，例如細胞分裂。",
  },
  {
    id: 4,
    subtopic: "細胞理論與顯微鏡",
    front: "What is the difference between unicellular and multicellular organisms?<br>單細胞生物與多細胞生物有何分別？",
    back: "Unicellular organisms have <strong>one cell</strong>; multicellular organisms have <strong>many cells</strong>.<br>單細胞生物有<strong>一個細胞</strong>；多細胞生物有<strong>許多細胞</strong>。",
  },
  {
    id: 5,
    subtopic: "細胞理論與顯微鏡",
    front: "How do light microscopes and electron microscopes form an image?<br>光學顯微鏡和電子顯微鏡如何形成影像？",
    back: "A light microscope uses <strong>visible light</strong> (seen with the eyes); an electron microscope uses <strong>electron beams</strong> (shown on a computer).<br>光學顯微鏡用<strong>可見光</strong>（肉眼觀看）；電子顯微鏡用<strong>電子束</strong>（在電腦顯示）。",
  },
  {
    id: 6,
    subtopic: "細胞理論與顯微鏡",
    front: "What are the approximate maximum magnifications of a transmission electron microscope and a scanning electron microscope?<br>透射電子顯微鏡和掃描電子顯微鏡的最高放大倍數大約是多少？",
    back: "A transmission electron microscope can reach about <strong>10,000,000×</strong>; a scanning electron microscope about <strong>500,000×</strong> (a light microscope about 2,000×).<br>透射電子顯微鏡最高約 <strong>10,000,000×</strong>；掃描電子顯微鏡約 <strong>500,000×</strong>（光學顯微鏡約 2,000×）。",
  },
  {
    id: 7,
    subtopic: "細胞理論與顯微鏡",
    front: "Can electron microscopes be used to view living cells, and why?<br>電子顯微鏡能用來觀察活細胞嗎？為何？",
    back: "<strong>No</strong>, because fixation <strong>kills</strong> the cells.<br><strong>不能</strong>，因為固定會<strong>殺死</strong>細胞。",
  },
  {
    id: 8,
    subtopic: "細胞理論與顯微鏡",
    front: "What common stains are used for plant cells and animal cells?<br>植物細胞和動物細胞常用甚麼染色劑？",
    back: "Plant cells are stained with <strong>iodine solution</strong>; animal cells are stained with <strong>methylene blue</strong>.<br>植物細胞用<strong>碘液</strong>染色；動物細胞用<strong>亞甲藍</strong>染色。",
  },
  {
    id: 9,
    subtopic: "光學顯微鏡使用與計算",
    front: "What must you do before using high power on a light microscope?<br>使用高倍鏡前必須先做什麼？",
    back: "You must first focus under <strong>low power</strong>.<br>必須先在<strong>低倍</strong>對焦。",
  },
  {
    id: 10,
    subtopic: "光學顯微鏡使用與計算",
    front: "When are the coarse and fine adjustment knobs used?<br>粗準焦螺旋和微準焦螺旋分別在何時使用？",
    back: "The coarse knob is used to <strong>find focus</strong> under low power; the fine knob is used to <strong>sharpen</strong> the image, especially under high power.<br>粗準焦用於低倍<strong>找焦點</strong>；微準焦用於<strong>調銳</strong>影像，尤其在高倍時。",
  },
  {
    id: 11,
    subtopic: "光學顯微鏡使用與計算",
    front: "How does the field of view change from low power to high power?<br>由低倍轉到高倍時，視野有何變化？",
    back: "Low power shows a <strong>larger area with less detail</strong>; high power shows a <strong>smaller area with more detail</strong>.<br>低倍看到<strong>較大範圍、較少細節</strong>；高倍看到<strong>較小範圍、較多細節</strong>。",
  },
  {
    id: 12,
    subtopic: "光學顯微鏡使用與計算",
    front: "Which needs more light, low power or high power, and why?<br>低倍還是高倍需要更多光線？為何？",
    back: "<strong>High power</strong> needs more light, because the field of view is smaller so less light enters.<br><strong>高倍</strong>需要更多光線，因為視野較小，進入的光較少。",
  },
  {
    id: 13,
    subtopic: "光學顯微鏡使用與計算",
    front: "What is the formula for actual length from a magnified image?<br>由放大影像求實際長度的公式是什麼？",
    back: "<strong>Actual length = measured length ÷ magnification</strong>.<br><strong>實際長度 = 量度長度 ÷ 放大倍數</strong>。",
  },
  {
    id: 14,
    subtopic: "光學顯微鏡使用與計算",
    front: "How do you find magnification from a scale bar?<br>如何由比例尺求出放大倍數？",
    back: "Magnification = <strong>image length of the scale ÷ actual length of the scale</strong>.<br>放大倍數 = <strong>比例尺的影像長度 ÷ 比例尺的實際長度</strong>。",
  },
  {
    id: 15,
    subtopic: "光學顯微鏡使用與計算",
    front: "How many millimetres and micrometres are in 1 cm?<br>1 厘米等於多少毫米和多少微米？",
    back: "1 cm = <strong>10 mm</strong> = <strong>10,000 μm</strong>.<br>1 厘米 = <strong>10 毫米</strong> = <strong>10,000 微米</strong>。",
  },
  {
    id: 16,
    subtopic: "光學顯微鏡使用與計算",
    front: "How many micrometres are in 1 mm, and how many centimetres are in 1 μm?<br>1 毫米等於多少微米？1 微米等於多少厘米？",
    back: "1 mm = <strong>1,000 μm</strong>, and 1 μm = <strong>0.0001 cm</strong>.<br>1 毫米 = <strong>1,000 微米</strong>，1 微米 = <strong>0.0001 厘米</strong>。",
  },
  {
    id: 17,
    subtopic: "真核與原核",
    front: "Do eukaryotic cells and prokaryotic cells have a true nucleus?<br>真核細胞和原核細胞有沒有真正的細胞核？",
    back: "Eukaryotic cells have a <strong>true nucleus</strong> with a nuclear membrane; prokaryotic cells have <strong>no true nucleus</strong>, and circular DNA is free in the cytoplasm.<br>真核細胞有<strong>真正的細胞核</strong>（有核膜）；原核細胞<strong>沒有真正的細胞核</strong>，環狀 DNA 游離於細胞質。",
  },
  {
    id: 18,
    subtopic: "真核與原核",
    front: "Do eukaryotic cells and prokaryotic cells have membrane-bounded organelles?<br>真核細胞和原核細胞有沒有膜性胞器？",
    back: "Membrane-bounded organelles are <strong>present</strong> in eukaryotic cells and <strong>absent</strong> in prokaryotic cells.<br>真核細胞<strong>有</strong>膜性胞器；原核細胞<strong>沒有</strong>膜性胞器。",
  },
  {
    id: 19,
    subtopic: "真核與原核",
    front: "What is the cell wall of plant eukaryotic cells made of, compared with bacteria?<br>植物真核細胞的細胞壁由什麼組成？細菌又如何？",
    back: "Plant cell walls are made of <strong>cellulose</strong>; bacterial cell walls are made of <strong>peptidoglycan</strong> (not cellulose).<br>植物細胞壁由<strong>纖維素</strong>組成；細菌細胞壁由<strong>肽聚醣</strong>組成（不是纖維素）。",
  },
  {
    id: 20,
    subtopic: "真核與原核",
    front: "Where are ribosomes found in eukaryotic cells and in prokaryotic cells?<br>真核細胞和原核細胞的核糖體分別在哪裏？",
    back: "In eukaryotic cells they are free and/or on the <strong>rough endoplasmic reticulum</strong>; in prokaryotic cells they are <strong>free in the cytoplasm</strong> only.<br>真核細胞中，核糖體可游離及／或附在<strong>粗面內質網</strong>；原核細胞中，核糖體<strong>只游離於細胞質</strong>。",
  },
  {
    id: 21,
    subtopic: "真核與原核",
    front: "Identify these cells.<br>辨認這些細胞。",
    back: "They are <strong>bacteria (prokaryotes)</strong>.<br>它們是<strong>細菌（原核生物）</strong>。",
    imageFront: "./assets/pm_bacteria_a.jpeg",
    imageFrontAlt: "Rod-shaped stained bacteria under a light microscope.",
  },
  {
    id: 22,
    subtopic: "細胞器",
    front: "What type of permeability does the cell membrane have, and what is its function?<br>細胞膜屬於哪一種通透性？它的功能是什麼？",
    back: "It is <strong>differentially permeable</strong> and controls the movement of substances.<br>它具<strong>差異滲透性</strong>，用以控制物質進出。",
  },
  {
    id: 23,
    subtopic: "細胞器",
    front: "What are the two main components of the fluid mosaic model?<br>流動鑲嵌模型的兩個主要成分是什麼？",
    back: "A <strong>phospholipid bilayer</strong> and <strong>proteins</strong>.<br><strong>磷脂雙層</strong>和<strong>蛋白質</strong>。",
  },
  {
    id: 24,
    subtopic: "細胞器",
    front: "What type of permeability does the cell wall have, and is it present in animal cells?<br>細胞壁屬於哪一種通透性？動物細胞有沒有細胞壁？",
    back: "It is <strong>fully permeable</strong>, and it is <strong>absent</strong> in animal cells (plant cell walls are cellulose).<br>它是<strong>全透性</strong>的，而且動物細胞<strong>沒有</strong>細胞壁（植物細胞壁是纖維素）。",
  },
  {
    id: 25,
    subtopic: "細胞器",
    front: "What are two roles of the cytoplasm?<br>細胞質有哪兩項功能？",
    back: "It is the site of <strong>metabolic reactions</strong> and acts as a <strong>transport medium</strong>.<br>它是<strong>代謝反應的場所</strong>，也是<strong>運輸介質</strong>。",
  },
  {
    id: 26,
    subtopic: "細胞器",
    front: "How do vacuoles differ in animal cells and plant cells?<br>動物細胞和植物細胞的液泡有何分別？",
    back: "Animal cells have <strong>small vacuoles or none</strong>; plant cells have a <strong>large central vacuole</strong>.<br>動物細胞的液泡<strong>細小或沒有</strong>；植物細胞有<strong>大型中央液泡</strong>。",
  },
  {
    id: 27,
    subtopic: "細胞器",
    front: "What are the main roles of the nucleus?<br>細胞核的主要功能是什麼？",
    back: "It provides <strong>genetic control</strong>, replicates DNA, and controls protein synthesis.<br>它負責<strong>遺傳控制</strong>、複製 DNA，並控制蛋白質合成。",
  },
  {
    id: 28,
    subtopic: "細胞器",
    front: "What does the nucleolus make?<br>核仁製造什麼？",
    back: "It makes <strong>ribosomes</strong>.<br>它製造<strong>核糖體</strong>。",
  },
  {
    id: 29,
    subtopic: "細胞器",
    front: "Do mature red blood cells have a nucleus?<br>成熟紅血球有沒有細胞核？",
    back: "A nucleus is <strong>absent</strong>.<br>細胞核是<strong>沒有</strong>的。",
  },
  {
    id: 30,
    subtopic: "細胞器",
    front: "What is the function of ribosomes, and what are they made of?<br>核糖體的功能是什麼？它們由什麼組成？",
    back: "They carry out <strong>protein synthesis</strong> and are made of <strong>RNA and proteins</strong>.<br>它們進行<strong>蛋白質合成</strong>，由<strong>RNA 和蛋白質</strong>組成。",
  },
  {
    id: 31,
    subtopic: "細胞器",
    front: "Does rough endoplasmic reticulum have ribosomes, and what is its function?<br>粗面內質網有沒有核糖體？它的功能是什麼？",
    back: "It is membrane <strong>with ribosomes</strong>, used for <strong>protein</strong> synthesis and transport.<br>它是<strong>附有核糖體</strong>的膜，用於<strong>蛋白質</strong>合成和運輸。",
  },
  {
    id: 32,
    subtopic: "細胞器",
    front: "Does smooth endoplasmic reticulum have ribosomes, and what is its function?<br>滑面內質網有沒有核糖體？它的功能是什麼？",
    back: "It is membrane <strong>without ribosomes</strong>, used for <strong>lipid</strong> synthesis and transport.<br>它是<strong>沒有核糖體</strong>的膜，用於<strong>脂質</strong>合成和運輸。",
  },
  {
    id: 33,
    subtopic: "細胞器",
    front: "What is the function of mitochondria, and how many membrane layers do they have?<br>粒線體的功能是什麼？它有幾層膜？",
    back: "They carry out <strong>aerobic respiration</strong> to make ATP, and they have a <strong>double</strong> membrane.<br>它們進行<strong>有氧呼吸</strong>以製造 ATP，並且有<strong>雙層</strong>膜。",
  },
  {
    id: 34,
    subtopic: "細胞器",
    front: "What is the function of chloroplasts, and in what form do they store the product?<br>葉綠體的功能是什麼？產物以什麼形式貯存？",
    back: "They carry out <strong>photosynthesis</strong> and store the product as <strong>starch</strong>.<br>它們進行<strong>光合作用</strong>，並把產物貯存為<strong>澱粉</strong>。",
  },
  {
    id: 35,
    subtopic: "細胞器",
    front: "Where are chloroplasts found, and where are they not found?<br>葉綠體見於哪些細胞？不見於哪些細胞？",
    back: "They are found in mesophyll and guard cells, but <strong>not</strong> in leaf epidermis or onion skin.<br>它們見於葉肉細胞和保衛細胞，但<strong>不見於</strong>葉表皮或洋蔥表皮。",
  },
  {
    id: 36,
    subtopic: "動植物細胞比較",
    front: "How does the shape of animal cells compare with plant cells?<br>動物細胞和植物細胞的形狀有何分別？",
    back: "Animal cells are usually <strong>irregular</strong>; plant cells have a shape <strong>fixed by the cell wall</strong>.<br>動物細胞通常<strong>不規則</strong>；植物細胞的形狀<strong>由細胞壁固定</strong>。",
  },
  {
    id: 37,
    subtopic: "動植物細胞比較",
    front: "Do animal cells and plant cells have a cell wall?<br>動物細胞和植物細胞有沒有細胞壁？",
    back: "A cell wall is <strong>absent</strong> in animal cells and <strong>present</strong> in plant cells.<br>動物細胞<strong>沒有</strong>細胞壁；植物細胞<strong>有</strong>細胞壁。",
  },
  {
    id: 38,
    subtopic: "動植物細胞比較",
    front: "How do vacuoles compare in animal cells and plant cells?<br>動物細胞和植物細胞的液泡如何比較？",
    back: "Animal cells have none or a few small vacuoles; plant cells have a <strong>large central vacuole</strong>.<br>動物細胞沒有或只有少數細小液泡；植物細胞有<strong>大型中央液泡</strong>。",
  },
  {
    id: 39,
    subtopic: "動植物細胞比較",
    front: "Do animal cells and plant cells have chloroplasts?<br>動物細胞和植物細胞有沒有葉綠體？",
    back: "Chloroplasts are <strong>absent</strong> in animal cells and present in <strong>green</strong> plant cells.<br>動物細胞<strong>沒有</strong>葉綠體；<strong>綠色</strong>植物細胞有葉綠體。",
  },
  {
    id: 40,
    subtopic: "顯微照片辨認",
    front: "Identify the green organelles in these plant cells.<br>辨認這些植物細胞中的綠色細胞器。",
    back: "They are <strong>chloroplasts</strong>.<br>它們是<strong>葉綠體</strong>。",
    imageFront: "./assets/pm_chloroplast_c.jpeg",
    imageFrontAlt: "Light micrograph of green plant cells with chloroplasts.",
  },
  {
    id: 41,
    subtopic: "顯微照片辨認",
    front: "Identify this organelle. Note the internal folds (cristae).<br>辨認此細胞器。注意內摺（嵴）。",
    back: "It is a <strong>mitochondrion</strong>.<br>它是<strong>粒線體</strong>。",
    imageFront: "./assets/pm_mitochondria_b.png",
    imageFrontAlt: "Electron micrograph showing mitochondria with cristae.",
  },
  {
    id: 42,
    subtopic: "顯微照片辨認",
    front: "Identify the dark dense body inside the nucleus (marked on the figure).<br>辨認細胞核內的深色緻密體（圖中有標示）。",
    back: "It is the <strong>nucleolus</strong>.<br>它是<strong>核仁</strong>。",
    imageFront: "./assets/pm_nucleus.jpeg",
    imageFrontAlt: "Electron micrograph of a nucleus with the nucleolus marked.",
  },
  {
    id: 43,
    subtopic: "顯微照片辨認",
    front: "Identify the membrane system with attached ribosomes (the dots).<br>辨認附有核糖體（小點）的膜系統。",
    back: "It is <strong>rough endoplasmic reticulum</strong>.<br>它是<strong>粗面內質網</strong>。",
    imageFront: "./assets/pm_rough_er.png",
    imageFrontAlt: "Electron micrograph of rough endoplasmic reticulum with ribosomes.",
  },
  {
    id: 44,
    subtopic: "顯微照片辨認",
    front: "Identify these membrane stacks, which have no ribosomes.<br>辨認這些沒有核糖體的膜堆疊。",
    back: "It is <strong>smooth endoplasmic reticulum</strong>.<br>它是<strong>滑面內質網</strong>。",
    imageFront: "./assets/pm_smooth_er.gif",
    imageFrontAlt: "Electron micrograph showing smooth endoplasmic reticulum.",
  },
  {
    id: 45,
    subtopic: "顯微照片辨認",
    front: "Identify the large empty space and the dark oval bodies with stacks.<br>辨認大空腔，以及帶有堆疊的深色橢圓體。",
    back: "The empty space is a <strong>vacuole</strong> and the dark bodies are <strong>chloroplasts</strong>.<br>空腔是<strong>液泡</strong>，深色橢圓體是<strong>葉綠體</strong>。",
    imageFront: "./assets/pm_vacuole_chloro.png",
    imageFrontAlt: "Electron micrograph of a plant cell with a vacuole and chloroplasts.",
  },
];
