/** Ch6 Nutrition in humans (bilingual EN + 中文). PDF header says Ch7; labelled Ch6 as requested. */
export const FLASHCARD_TAGS = ["Biology", "Ch6", "Nutrition", "S3"];

export const FLASHCARD_DECK = [
  {
    id: 1,
    subtopic: "營養過程與方式",
    front: "What is ingestion?<br>甚麼是攝食？",
    back: "Food is <strong>taken in through the mouth</strong>.<br>食物<strong>經口腔攝入</strong>。",
  },
  {
    id: 2,
    subtopic: "營養過程與方式",
    front: "What is digestion for?<br>消化的目的是什麼？",
    back: "To break food into <strong>small, simple, soluble</strong> molecules ready for absorption.<br>把食物分解成<strong>細小、簡單、可溶</strong>的分子，以便吸收。",
  },
  {
    id: 3,
    subtopic: "營養過程與方式",
    front: "What is absorption?<br>甚麼是吸收？",
    back: "Digested molecules <strong>enter blood or lymph</strong>.<br>已消化分子<strong>進入血液或淋巴</strong>。",
  },
  {
    id: 4,
    subtopic: "營養過程與方式",
    front: "What is assimilation?<br>甚麼是同化？",
    back: "Cells <strong>take up</strong> molecules for metabolism (growth, repair, energy).<br>細胞<strong>攝取</strong>分子進行代謝（生長、修復、能量）。",
  },
  {
    id: 5,
    subtopic: "營養過程與方式",
    front: "How is egestion different from excretion?<br>排遺與排泄有何分別？",
    back: "Egestion removes <strong>undigested faeces</strong>; excretion removes <strong>metabolic waste</strong> such as urea.<br>排遺排出<strong>未消化糞便</strong>；排泄排出<strong>代謝廢物</strong>如尿素。",
  },
  {
    id: 6,
    subtopic: "營養過程與方式",
    front: "Which nutrition types are shown by mould, a green plant, and a dog?<br>黴菌、綠色植物和狗分別屬於哪種營養方式？",
    back: "Mould: <strong>saprophytic</strong>. Plant: <strong>autotrophic</strong>. Dog: <strong>holozoic</strong>.<br>黴菌：<strong>腐生</strong>。植物：<strong>自養</strong>。狗：<strong>動物式營養</strong>。",
    image: "./assets/img001.jpg",
    imageAlt: "Mould on bread, a green plant, and a dog as examples of nutrition types.",
  },
  {
    id: 7,
    subtopic: "營養過程與方式",
    front: "What is parasitic nutrition?<br>甚麼是寄生營養？",
    back: "The organism <strong>absorbs food from a living host</strong> and does not directly kill it.<br>生物從<strong>活宿主吸收食物</strong>，並不直接殺死宿主。",
  },
  {
    id: 8,
    subtopic: "營養過程與方式",
    front: "Food is taken in through the mouth. Which process is this?<br>食物經口腔攝入，這是哪個過程？",
    back: "<strong>Ingestion</strong>.<br><strong>攝食</strong>。",
  },
  {
    id: 9,
    subtopic: "消化道與蠕動",
    front: "Name four digestive glands.<br>寫出四個消化腺。",
    back: "<strong>Salivary glands, liver, pancreas, and gall bladder</strong>.<br><strong>唾腺、肝、胰和膽囊</strong>。",
  },
  {
    id: 10,
    subtopic: "消化道與蠕動",
    front: "What is peristalsis?<br>甚麼是蠕動？",
    back: "<strong>Alternate contraction and relaxation</strong> of circular and longitudinal muscles, pushing food one way.<br>環肌和縱肌<strong>交替收縮與舒張</strong>，把食物單向推前。",
  },
  {
    id: 11,
    subtopic: "消化道與蠕動",
    front: "Which muscle layer is inside, circular or longitudinal?<br>哪一層肌在內：環肌還是縱肌？",
    back: "<strong>Circular</strong> muscle is inside; <strong>longitudinal</strong> muscle is outside.<br><strong>環肌</strong>在內；<strong>縱肌</strong>在外。",
  },
  {
    id: 12,
    subtopic: "消化道與蠕動",
    front: "Does the oesophagus do chemical digestion of new enzymes?<br>食道有沒有新的消化酶？",
    back: "<strong>No new enzymes</strong> are added; salivary amylase from the mouth may still work on the bolus.<br><strong>沒有加入新酶</strong>；口腔帶來的唾液澱粉酶仍可作用於食團。",
  },
  {
    id: 13,
    subtopic: "消化道與蠕動",
    front: "Physical digestion of a boiled egg begins where?<br>熟蛋的物理消化由哪裏開始？",
    back: "In the <strong>mouth cavity</strong> (chewing).<br>在<strong>口腔</strong>（咀嚼）。",
  },
  {
    id: 14,
    subtopic: "牙齒",
    front: "What is the function of incisors?<br>門齒的功能是什麼？",
    back: "They have a chisel edge for <strong>biting and cutting</strong>.<br>它們有鑿形邊緣，用來<strong>咬切</strong>。",
    image: "./assets/img008.jpg",
    imageAlt: "Four human tooth types: incisor, canine, premolar, and molar.",
  },
  {
    id: 15,
    subtopic: "牙齒",
    front: "What is the function of canines?<br>犬齒的功能是什麼？",
    back: "They are pointed and curved for <strong>tearing flesh</strong>.<br>它們尖而彎，用來<strong>撕裂肉類</strong>。",
  },
  {
    id: 16,
    subtopic: "牙齒",
    front: "What are premolars and molars for?<br>前臼齒和臼齒有何用途？",
    back: "They have cusps for <strong>crushing and grinding</strong>.<br>它們有尖突，用來<strong>壓碎和研磨</strong>。",
    image: "./assets/img012.jpg",
    imageAlt: "Herbivore, carnivore, and omnivore teeth compared.",
  },
  {
    id: 17,
    subtopic: "牙齒",
    front: "How many milk teeth and permanent teeth does a human have?<br>人有多少顆乳齒和恆齒？",
    back: "Milk: <strong>20</strong> (2102). Permanent: <strong>32</strong> (2123).<br>乳齒：<strong>20</strong> 顆（2102）。恆齒：<strong>32</strong> 顆（2123）。",
  },
  {
    id: 18,
    subtopic: "牙齒",
    front: "What is enamel made of, and is it living?<br>琺瑯質由什麼組成？它是活的嗎？",
    back: "It is the hardest part, mainly <strong>calcium salts</strong>, and it is <strong>non-living</strong>.<br>它是最硬部分，主要是<strong>鈣鹽</strong>，而且是<strong>非活</strong>的。",
  },
  {
    id: 19,
    subtopic: "牙齒",
    front: "What does the pulp cavity contain?<br>髓腔含有什麼？",
    back: "<strong>Living cells, blood vessels, and nerves</strong>.<br><strong>活細胞、血管和神經</strong>。",
  },
  {
    id: 20,
    subtopic: "牙齒",
    front: "How does tooth decay start?<br>蛀牙如何開始？",
    back: "Bacteria in plaque use food to make <strong>acid</strong>, which dissolves calcium salts.<br>牙菌斑中的細菌利用食物製造<strong>酸</strong>，溶解鈣鹽。",
  },
  {
    id: 21,
    subtopic: "牙齒",
    front: "How does fluoride in toothpaste protect teeth?<br>牙膏中的氟化物如何護齒？",
    back: "It <strong>strengthens enamel</strong>; it does <strong>not</strong> work by killing bacteria.<br>它<strong>強化琺瑯質</strong>；<strong>不是</strong>靠殺菌。",
  },
  {
    id: 22,
    subtopic: "牙齒",
    front: "Why can alcohol mouthwash harm mouth cells as well as bacteria?<br>為何含酒精漱口水也會傷害口腔細胞？",
    back: "Alcohol <strong>dissolves cell membranes</strong>.<br>酒精會<strong>溶解細胞膜</strong>。",
  },
  {
    id: 23,
    subtopic: "消化",
    front: "How does physical digestion help chemical digestion?<br>物理消化如何幫助化學消化？",
    back: "It makes <strong>smaller pieces</strong> and <strong>increases surface area</strong> for enzymes.<br>它把食物變成<strong>較小塊</strong>，並<strong>增加表面積</strong>讓酶作用。",
  },
  {
    id: 24,
    subtopic: "消化",
    front: "What does salivary amylase digest starch into?<br>唾液澱粉酶把澱粉分解成什麼？",
    back: "<strong>Maltose</strong>.<br><strong>麥芽糖</strong>。",
  },
  {
    id: 25,
    subtopic: "消化",
    front: "Name three roles of hydrochloric acid in gastric juice.<br>寫出胃液中鹽酸的三項作用。",
    back: "It gives <strong>pH ~2 for pepsin</strong>, <strong>kills microbes</strong>, and <strong>denatures proteins</strong>.<br>它提供胃蛋白酶所需的 <strong>pH 約 2</strong>、<strong>殺死微生物</strong>，並使<strong>蛋白質變性</strong>。",
  },
  {
    id: 26,
    subtopic: "消化",
    front: "What does pepsin digest, and where?<br>胃蛋白酶在哪裏消化什麼？",
    back: "It digests <strong>proteins to peptides</strong> in the <strong>stomach</strong>.<br>它在<strong>胃</strong>中把<strong>蛋白質分解成肽</strong>。",
  },
  {
    id: 27,
    subtopic: "消化",
    front: "Is bile chemical digestion?<br>膽汁是化學消化嗎？",
    back: "<strong>No.</strong> Bile salts <strong>emulsify</strong> lipids (physical digestion) and contain <strong>no enzyme</strong>.<br><strong>不是。</strong>膽鹽<strong>乳化</strong>脂質（物理消化），而且<strong>不含酶</strong>。",
  },
  {
    id: 28,
    subtopic: "消化",
    front: "Why does emulsification speed up lipid digestion?<br>為何乳化能加快脂質消化？",
    back: "Smaller droplets have a <strong>larger surface area</strong> for lipase.<br>較小油滴有<strong>更大表面積</strong>讓脂肪酶作用。",
  },
  {
    id: 29,
    subtopic: "消化",
    front: "Where is bile made and stored?<br>膽汁在哪裏製造和貯存？",
    back: "Made in the <strong>liver</strong>, stored in the <strong>gall bladder</strong>, sent to the <strong>duodenum</strong>.<br>在<strong>肝</strong>製造，在<strong>膽囊</strong>貯存，送到<strong>十二指腸</strong>。",
  },
  {
    id: 30,
    subtopic: "消化",
    front: "Which pancreatic enzymes digest carbs, lipids, and proteins?<br>胰液中哪些酶分別消化糖、脂、蛋白質？",
    back: "<strong>Amylase</strong>, <strong>lipase</strong>, and <strong>protease</strong>.<br><strong>澱粉酶</strong>、<strong>脂肪酶</strong>和<strong>蛋白酶</strong>。",
  },
  {
    id: 31,
    subtopic: "消化",
    front: "Do intestinal wall enzymes include lipase?<br>腸壁酶有沒有脂肪酶？",
    back: "<strong>No lipase</strong> on the intestinal wall; they digest carbohydrates and peptides.<br>腸壁<strong>沒有脂肪酶</strong>；它們消化碳水化合物和肽。",
  },
  {
    id: 32,
    subtopic: "消化",
    front: "Which digestive juice contains no digestive enzyme?<br>哪一種消化液不含消化酶？",
    back: "<strong>Bile</strong> from the liver.<br>肝臟產生的<strong>膽汁</strong>。",
  },
  {
    id: 33,
    subtopic: "小腸吸收",
    front: "Name three features that increase absorption surface area in the ileum.<br>寫出迴腸三項增加吸收面積的構造。",
    back: "It is <strong>very long</strong>, has <strong>villi</strong>, and has <strong>microvilli</strong>.<br>它<strong>很長</strong>，有<strong>絨毛</strong>和<strong>微絨毛</strong>。",
  },
  {
    id: 34,
    subtopic: "小腸吸收",
    front: "Why do absorptive cells have many mitochondria?<br>為何吸收細胞有很多粒線體？",
    back: "To make <strong>ATP</strong> for <strong>active transport</strong>.<br>用來製造 <strong>ATP</strong> 進行<strong>主動運輸</strong>。",
  },
  {
    id: 35,
    subtopic: "小腸吸收",
    front: "Why is villus epithelium one cell thick?<br>為何絨毛上皮只有一層細胞厚？",
    back: "It <strong>shortens the diffusion distance</strong>.<br>它<strong>縮短擴散距離</strong>。",
  },
  {
    id: 36,
    subtopic: "小腸吸收",
    front: "Which substances go into capillaries, and which into lacteals?<br>哪些物質進入微血管？哪些進入乳糜管？",
    back: "Water-soluble nutrients → <strong>capillaries</strong>. Lipids and vitamins A, D, E, K → <strong>lacteals</strong>.<br>水溶性養分 → <strong>微血管</strong>。脂質和維生素 A、D、E、K → <strong>乳糜管</strong>。",
  },
  {
    id: 37,
    subtopic: "小腸吸收",
    front: "What happens to fatty acids and glycerol in epithelial cells?<br>脂肪酸和甘油在上皮細胞中會怎樣？",
    back: "They <strong>recombine into triglycerides</strong> before entering lacteals.<br>它們先<strong>重新結合成三酸甘油酯</strong>，再進入乳糜管。",
  },
  {
    id: 38,
    subtopic: "小腸吸收",
    front: "How does flattened villi cause diarrhoea?<br>絨毛變平坦如何導致腹瀉？",
    back: "Less food is absorbed, so lumen water potential stays low and <strong>less water is absorbed</strong>.<br>吸收的食物減少，腸腔水勢仍低，<strong>吸收的水也較少</strong>。",
    image: "./assets/img040.jpg",
    imageAlt: "Normal versus blunted intestinal villi under the microscope.",
  },
  {
    id: 39,
    subtopic: "小腸吸收",
    front: "Amino acids are absorbed by which processes?<br>胺基酸以哪些過程被吸收？",
    back: "<strong>Diffusion and active transport</strong> (not vitamin A / fatty acids only).<br><strong>擴散和主動運輸</strong>（不是只有維生素 A／脂肪酸）。",
  },
  {
    id: 40,
    subtopic: "小腸吸收",
    front: "Why does a lacteal plus capillaries speed diffusion?<br>乳糜管加微血管為何加快擴散？",
    back: "Absorbed food is <strong>carried away</strong>, keeping a <strong>steep gradient</strong>.<br>已吸收食物被<strong>運走</strong>，維持<strong>陡梯度</strong>。",
  },
  {
    id: 41,
    subtopic: "運輸、肝與大腸",
    front: "After a meal, which vessel has the highest water-soluble nutrient level?<br>進食後，哪條血管的水溶性養分最高？",
    back: "The <strong>hepatic portal vein</strong>, from the small intestine to the liver.<br><strong>肝門靜脈</strong>，由小腸到肝。",
  },
  {
    id: 42,
    subtopic: "運輸、肝與大腸",
    front: "In starvation, which vessel has the highest glucose?<br>饑餓時，哪條血管葡萄糖最高？",
    back: "The <strong>hepatic vein</strong>, because the liver breaks glycogen into glucose.<br><strong>肝靜脈</strong>，因為肝把肝醣分解成葡萄糖。",
  },
  {
    id: 43,
    subtopic: "運輸、肝與大腸",
    front: "What happens to excess amino acids in the liver?<br>過量胺基酸在肝中會怎樣？",
    back: "They are <strong>deaminated</strong>: amino group → <strong>urea</strong>; the rest → glucose or lipid.<br>它們被<strong>脫氨</strong>：氨基變成<strong>尿素</strong>；其餘變成葡萄糖或脂質。",
  },
  {
    id: 44,
    subtopic: "運輸、肝與大腸",
    front: "Name four liver functions besides deamination.<br>除脫氨外，寫出肝的四項功能。",
    back: "<strong>Regulate blood glucose</strong>, <strong>store glycogen / iron / ADEK</strong>, <strong>make bile</strong>, and <strong>detoxify</strong>.<br><strong>調節血糖</strong>、<strong>貯存肝醣／鐵／ADEK</strong>、<strong>製造膽汁</strong>和<strong>解毒</strong>。",
  },
  {
    id: 45,
    subtopic: "運輸、肝與大腸",
    front: "Does the large intestine digest food?<br>大腸有沒有消化食物？",
    back: "<strong>No.</strong> Most digestion is finished in the small intestine; the colon mainly <strong>absorbs water</strong>.<br><strong>沒有。</strong>消化多在小腸完成；結腸主要<strong>吸收水分</strong>。",
  },
  {
    id: 46,
    subtopic: "運輸、肝與大腸",
    front: "What does oily faeces suggest?<br>油膩糞便暗示什麼？",
    back: "A <strong>pancreas / lipase</strong> problem, so lipids are not digested.<br><strong>胰／脂肪酶</strong>有問題，脂質未被消化。",
  },
  {
    id: 47,
    subtopic: "運輸、肝與大腸",
    front: "Why does too little fibre cause constipation?<br>為何纖維太少會引致便秘？",
    back: "Peristalsis is <strong>too slow</strong>, so too much water is absorbed.<br>蠕動<strong>太慢</strong>，吸收了過多水分。",
  },
  {
    id: 48,
    subtopic: "運輸、肝與大腸",
    front: "Iron from spinach used to make haemoglobin is which nutrition process?<br>菠菜中的鐵被用來製造血紅蛋白，屬於哪個營養過程？",
    back: "<strong>Assimilation</strong>.<br><strong>同化</strong>。",
  },
];
